Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2018-12, with the labels that each got.

#3826 add book subtitles
  content/webapp/pages/book.js
Labels: improvement

#3828 use PageLayout on work page
  catalogue/webapp/pages/work.js
Labels: bug

#3827 Trailing slash redirect
  router/webapp/redirector.js
  router/webapp/redirector.test.js
  router/webapp/redirects.json
Labels: improvement

#3805 move over to V2 with errors
  catalogue/webapp/app.js
  catalogue/webapp/pages/_app.js
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  catalogue/webapp/pages/worksv2.js
  catalogue/webapp/pages/workv2.js
  catalogue/webapp/services/catalogue/links.js
  catalogue/webapp/services/catalogue/works.js
  catalogue/webapp/services/catalogue/worksv2.js
  catalogue/webapp/test/WorksPage.test.js
  catalogue/webapp/test/services/catalogue/__snapshots__/works.test.js.snap
  catalogue/webapp/test/services/catalogue/works.test.js
  common/styles/works.scss
Labels: improvement

#3765 November 2018 release notes
  catalogue/webapp/pages/PROGRESS_NOTES.md
Labels: improvement

#3850 add deploy script to root directory
  package.json
Labels: improvement

#3852 start adding workType filters
  catalogue/webapp/pages/worksv2.js
  common/views/components/SearchBox/SearchBox.js
  dash/webapp/pages/toggles.js
Labels: improvement

#3810 Work merge redirect
  catalogue/webapp/pages/workv2.js
  catalogue/webapp/services/catalogue/works.js
Labels: improvement

#3849 set the canonical without page and rel=prev|next in head
  cardigan/stories/components/Promos.js
  catalogue/webapp/components/WorkRedesign/WorkRedesign.js
  catalogue/webapp/pages/worksv2.js
  catalogue/webapp/pages/workv2.js
  catalogue/webapp/services/catalogue/urls.js
  common/model/url.js
  common/utils/convert-url-to-string.js
  common/views/components/PageLayout/PageLayout.js
Labels: improvement

#3859 get jest working on cmmon
  catalogue/webapp/package.json
  catalogue/webapp/yarn.lock
  common/.babelrc
  common/.flowconfig
  common/Thing.js
  common/babel.config.js
  common/jest.config.js
  common/package.json
  common/yarn.lock
  content/webapp/yarn.lock
  yarn.lock
Labels: improvement

#3708 update flow
  common/services/prismic/parsers.js
  common/utils/convert-image-uri.js
  common/views/components/ContentPage/ContentPage.js
  common/views/components/EventSchedule/EventSchedule.js
  package.json
  yarn.lock
Labels: improvement

#3863 workspaces working in dev
  .circleci/config.yml
  catalogue/webapp/Dockerfile
  catalogue/webapp/package.json
  catalogue/webapp/pages/_document.js
  catalogue/webapp/styles.scss
  common/next/next.config.js
  common/styles/vendor/_normalize.scss
  content/webapp/Dockerfile
  content/webapp/package.json
  content/webapp/pages/_document.js
  content/webapp/styles.scss
  package.json
  yarn.lock
Labels: improvement

#3866 add markdown heading renderer to give headings IDs
  catalogue/webapp/pages/progress.js
Labels: bug

#3861 add removal message for a work
  catalogue/webapp/pages/worksv2.js
  catalogue/webapp/pages/workv2.js
  common/views/components/ErrorPage/ErrorPage.js
  content/webapp/yarn.lock
Labels: improvement

#3870 use next links for back to search
  cardigan/stories/components/Links.js
  catalogue/webapp/components/StaticWorksContent/StaticWorksContent.js
  catalogue/webapp/pages/worksv2.js
  catalogue/webapp/pages/workv2.js
  catalogue/webapp/services/catalogue/urls.js
  catalogue/webapp/services/catalogue/works.js
  common/model/next-link-type.js
  common/model/url.js
  common/views/components/LinkLabels/LinkLabels.js
  common/views/components/Links/SecondaryLink/SecondaryLink.js
  common/views/components/StaticWorksContent/StaticWorksContent.config.js
  common/views/components/Tags/Tags.js
  common/views/components/WorkPromo/WorkPromo.js
  common/views/global/typography/typography.js
  content/webapp/pages/event.js
  content/webapp/pages/whats-on.js
Labels: bug

#3879 remove coupling of state and showing tasl
  common/views/components/Images/Images.js
Labels: bug

#3878 Fix cardy build
  .circleci/config.yml
  common/views/components/BookPromo/BookPromo.js
Labels: bug

#3874 create SearchForm component
  cardigan/stories/components/SearchBox.js
  catalogue/webapp/babel.config.js
  catalogue/webapp/components/SearchForm/SearchForm.js
  catalogue/webapp/components/WorkRedesign/WorkRedesign.js
  catalogue/webapp/package.json
  catalogue/webapp/pages/worksv2.js
  catalogue/webapp/services/catalogue/urls.js
  common/styles/components/_search_box.scss
  common/styles/content.scss
  common/styles/critical.scss
  common/styles/works.scss
  common/views/components/SearchBox/README.md
  common/views/components/SearchBox/SearchBox.config.js
  common/views/components/SearchBox/SearchBox.js
  common/views/components/SearchBoxV2/SearchBoxV2.js
  common/views/components/TextInput/TextInput.js
  common/views/pages/_document.js
  common/views/themes/default.js
  content/webapp/babel.config.js
  content/webapp/package.json
  yarn.lock
Labels: improvement

#3875 Babel consolidation
  catalogue/webapp/babel.config.js
  catalogue/webapp/package.json
  common/babel.config.js
  common/babel.js
  common/package.json
  content/webapp/babel.config.js
  content/webapp/package.json
Labels: improvement

#3885 only error when we override the status code from getInitialProps
  common/views/pages/_app.js
  content/webapp/pages/articles.js
  content/webapp/pages/events.js
  content/webapp/pages/exhibitions.js
Labels: bug

#3886 don’t render ErrorPage component unless there is a pageProps.statusCode
  common/views/pages/_app.js
Labels: bug

#3891 Remove references to V2 and Unleash
  catalogue/webapp/app.js
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  catalogue/webapp/services/catalogue/urls.js
  catalogue/webapp/yarn.lock
  common/package.json
  common/services/unleash/feature-toggles.js
  common/test/services/unleash/feature-flags.test.js
  common/yarn.lock
  content/webapp/yarn.lock
  docs/feature-toggles.md
  yarn.lock
Labels: improvement

#3894 Cached values handler
  catalogue/webapp/app.js
  common/koa-middleware/withCachedValues.js
  content/webapp/app.js
Labels: bug

#3897 trigger engagement event after 10 seconds has elapsed
  common/views/pages/_app.js
Labels: bug, wip
