Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2018-11, with the labels that each got.

#3662 stories hyperlink on correct part of text
  content/webapp/pages/stories.js
Labels: bug

#3663 Responsive hero-image-bg
  common/styles/utilities/_root-scope-classes.scss
  common/views/components/PageHeader/PageHeader.js
Labels: bug

#3665 Use 16:9 crop for promo image if available
  common/views/components/Image/Image.js
  common/views/components/Promo/Promo.js
Labels: improvement

#3668 Add url query parser util
  common/utils/parse-query-string.js
  content/webapp/pages/newsletter.js
Labels: bug

#3669 Account for webcomics being in the outro
  common/services/prismic/articles.js
Labels: bug

#3651 remove featuresCohort cookie
  build/nginx.conf
  catalogue/webapp/server.js
  nginx-proxy/nginx.conf
  nginx_webapp/nginx.conf
Labels: improvement

#3670 add composed middleware and add helper route to avoid duplication, and buggy, code
  catalogue/webapp/server.js
  common/koa-middleware/withCachedValues.js
  common/package.json
  common/yarn.lock
  content/webapp/server.js
Labels: bug, improvement

#3671 remove name from series model
  prismic-model/js/series.js
  prismic-model/json/series.json
Labels: bug

#3674 add more of the 404s to the list
  router/redirects.conf
Labels: improvement

#3673 remove all the legacy app_cluster infra
  .circleci/config.yml
  app_cluster/terraform/ami.tf
  app_cluster/terraform/asg.tf
  app_cluster/terraform/ecs.tf
  app_cluster/terraform/iam.tf
  app_cluster/terraform/locals.tf
  app_cluster/terraform/terraform.tf
  app_cluster/terraform/topics.tf
  app_cluster/terraform/userdata.tf
  app_cluster/terraform/variables.tf
  deploy/deploy_service.js
  eventbrite/terraform/locals.tf
  eventbrite/terraform/service.tf
  eventbrite/terraform/templates/eventbrite.ini.template
  eventbrite/terraform/terraform.tf
  eventbrite/terraform/topics.tf
  eventbrite/terraform/variables.tf
  infra/terraform/prod/wellcomecollection.tf
  infra/terraform/templates/alb.tf
  infra/terraform/templates/vars.tf
Labels: improvement

#3659 remove old tracking and reinstate with new
  common/views/components/BackToTop/BackToTop.js
  common/views/components/CopyUrl/CopyUrl.js
  common/views/components/FacilityPromo/FacilityPromo.js
  common/views/components/InstallationPromo/InstallationPromo.js
  common/views/components/Links/PrimaryLink/PrimaryLink.js
  common/views/components/Links/SecondaryLink/SecondaryLink.js
  common/views/components/SearchBox/SearchBox.js
  common/views/components/SegmentedControl/SegmentedControl.js
  common/views/components/StoryPromo/StoryPromo.js
  common/views/components/Tags/Tags.js
Labels: bug

#3658 reinstate prismic validations
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
Labels: bug

#3678 update stories serial to be hidden persuaders
  content/webapp/pages/stories.js
Labels: improvement

#3679 add redirects for some wordpress articles
  router/redirects.conf
Labels: improvement

#3682 use page URL for ticket ts and cs
  content/webapp/pages/event.js
  router/redirects.conf
Labels: bug

#3684 add v2 pages to catalogue app
  catalogue/webapp/pages/worksv2.js
  catalogue/webapp/pages/workv2.js
  catalogue/webapp/server.js
  catalogue/webapp/services/catalogue/worksv2.js
Labels: improvement

#3687 put hotjar back in
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
Labels: bug

#3688 check for length to reinstate pageState tracking
  common/utils/analytics.js
Labels: bug

#3689 add work links to catalogue app
  cardigan/.cache/325c8f456729b912b0d2134054eb7448-dfeeb2271cc2857eb0a45a5003c8bbee
  cardigan/stories/components/Promos.js
  catalogue/webapp/pages/works.js
  catalogue/webapp/pages/worksv2.js
  catalogue/webapp/pages/workv2.js
  catalogue/webapp/services/catalogue/links.js
  catalogue/webapp/services/catalogue/worksv2.js
  common/views/components/WorkPromo/WorkPromo.js
Labels: improvement

#3685 Static deployment
  .DS_Store
  .circleci/config.yml
  toggles/webapp/next.config.js
Labels: improvement

#3695 filter worksv2 results
  catalogue/webapp/services/catalogue/worksv2.js
Labels: bug

#3697 get manifest as iiif-presentation type
  catalogue/webapp/pages/workv2.js
Labels: improvement, wip

#3691 make progress almost availalbe
  catalogue/webapp/package.json
  catalogue/webapp/pages/PROGRESS_NOTES.md
  catalogue/webapp/pages/progress.js
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  catalogue/webapp/pages/worksv2.js
  catalogue/webapp/pages/workv2.js
  catalogue/webapp/server.js
  catalogue/webapp/yarn.lock
  common/next/next.config.js
  common/package.json
  common/styles/works.scss
  common/yarn.lock
  content/webapp/package.json
  content/webapp/yarn.lock
  flow-typed/npm/react-markdown_vx.x.x.js
  package.json
  yarn.lock
Labels: bug

#3703 Add plain-text class to contributor to add link-hover style
  common/views/components/Contributor/Contributor.js
Labels: bug

#3704 Update green hex to have enough contrast on cream
  common/styles/utilities/compiled_variables/_colors.scss
  server/ui-config/colors.js
Labels: accessibility

#3709 update babel / webpack config for storybook to mend our cardigan
  cardigan/.cache/325c8f456729b912b0d2134054eb7448-dfeeb2271cc2857eb0a45a5003c8bbee
  cardigan/.storybook/.babelrc
  cardigan/.storybook/config.js
  cardigan/.storybook/webpack.config.js
  cardigan/package.json
  cardigan/yarn.lock
Labels: bug

#3683 add server.js testing to catalogue
  .DS_Store
  catalogue/webapp/.dockerignore
  catalogue/webapp/Dockerfile
  catalogue/webapp/__mocks__/next.js
  catalogue/webapp/app.js
  catalogue/webapp/jest.config.js
  catalogue/webapp/package.json
  catalogue/webapp/server.js
  catalogue/webapp/test/WorkPage.test.js
  catalogue/webapp/test/app.test.js
  catalogue/webapp/test/services/catalogue/works.test.js
  catalogue/webapp/yarn.lock
  common/package.json
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
  common/views/components/SegmentedControl/SegmentedControl.js
  common/yarn.lock
Labels: wip

#3729 /works/progress Routes
  catalogue/webapp/app.js
  catalogue/webapp/test/app.test.js
Labels: bug

#3732 add webcomic-series redirect
  router/redirects.conf
Labels: bug

#3713 remove toggles from cache and add tests
  content/webapp/pages/article.js
  content/webapp/test/articles.test.js
  router/webapp/ab_testing.js
  router/webapp/ab_testing.test.js
  router/webapp/package.json
  router/webapp/yarn.lock
Labels: improvement

#3731 Add filter toggle
  catalogue/webapp/pages/worksv2.js
  catalogue/webapp/services/catalogue/worksv2.js
  toggles/webapp/pages/index.js
Labels: improvement

#3750 remove cardigan theme
  server/cardigan-theme/assets/favicon.ico
  server/cardigan-theme/assets/images/cardigan.jpg
  server/cardigan-theme/assets/images/cardigan.svg
  server/cardigan-theme/assets/images/temp/books.jpg
  server/cardigan-theme/assets/images/temp/gallery.jpg
  server/cardigan-theme/assets/images/temp/objects.jpg
  server/cardigan-theme/assets/images/temp/reviews.jpg
  server/cardigan-theme/partials/head.nunj
  server/cardigan-theme/partials/header.nunj
Labels: improvement

#3710 Cardigan build prior to master
  .circleci/config.yml
  build_and_deploy_cardigan.sh
  cardigan/.storybook/config.js
  cardigan/.storybook/webpack.config.js
  cardigan/package.json
  cardigan/postcss.config.js
  cardigan/yarn.lock
Labels: improvement

#3733 fix webcomic resolver
  common/services/prismic/link-resolver.js
Labels: bug

#3734 add router service to deploy script
  deploy/deploy_service.js
  router/terraform/services.tf
  router/terraform/variables.tf
Labels: improvement

#3747 add published date to books
  content/webapp/pages/book.js
Labels: bug

#3736 add articles to content list
  prismic-model/js/parts/body.js
  prismic-model/json/books.json
  prismic-model/json/event-series.json
  prismic-model/json/events.json
  prismic-model/json/exhibitions.json
  prismic-model/json/installations.json
  prismic-model/json/pages.json
  prismic-model/json/places.json
  prismic-model/json/series.json
  prismic-model/json/webcomics.json
Labels: improvement

#3752 remove old server and client steps from the build
  .circleci/config.yml
Labels: improvement

#3753 remove built static assets
  .stylelintrc
  client/.babelrc
  client/README.md
  client/embed.js
  client/gulpfile.js
  client/js/actions.js
  client/js/app.js
  client/js/components/async-content.js
  client/js/components/back-to-top.js
  client/js/components/content-slider.js
  client/js/components/copy-url.js
  client/js/components/eventbrite-ticket-button.js
  client/js/components/eventbrite-ticket-status.js
  client/js/components/feature-flags.js
  client/js/components/focus-trap.js
  client/js/components/gif-video.js
  client/js/components/header/burger.js
  client/js/components/header/search.js
  client/js/components/iframe-container.js
  client/js/components/image-viewer.js
  client/js/components/info-banner.js
  client/js/components/instagram.js
  client/js/components/join-cohort.js
  client/js/components/make-sticky.js
  client/js/components/map.js
  client/js/components/newsletter-signup.js
  client/js/components/opening-hours.js
  client/js/components/scroll-to-info.js
  client/js/components/search-box.js
  client/js/components/segmented-control.js
  client/js/components/show-hide.js
  client/js/components/shrink-stories-nav.js
  client/js/components/sort-search.js
  client/js/components/tabs.js
  client/js/components/toggle-show-hide.js
  client/js/components/wobbly-edge.js
  client/js/polyfills.js
  client/js/reducers/app.js
  client/js/reducers/sticky-nav-height.js
  client/js/store.js
  client/js/tracking.js
  client/js/util.js
  client/js/utils/dom-events.js
  client/js/utils/fastdom-promise.js
  client/js/utils/flag-status.js
  client/js/utils/font-observer.js
  client/libs/ga-scroll-depth.js
  client/libs/picturefill.min.js
  client/package.json
  client/scss
  client/webpack.config.js
  client/yarn.lock
Labels: improvement

#3755 install aws on cardigan
  .circleci/config.yml
Labels: bug

#3754 autodeploy content app
  .circleci/config.yml
  deploy/deploy_service.js
  deploy/package.json
  deploy/yarn.lock
Labels: feature

#3764 add hooks to worksv2 to tidy up the code
  catalogue/webapp/package.json
  catalogue/webapp/pages/works.js
  catalogue/webapp/pages/worksv2.js
  catalogue/webapp/yarn.lock
  common/views/components/HTMLInput/HTMLInput.config.js
  common/views/components/HTMLInput/HTMLInput.js
  common/views/components/LayoutPaginatedResults/LayoutPaginatedResults.js
  common/views/components/Pagination/Pagination.js
  common/views/components/SearchBox/SearchBox.js
Labels: improvement

#3769 make sure pagination works with the new hooks
  catalogue/webapp/pages/worksv2.js
Labels: bug

#3768 add metadata description override to promoText
  common/data/our-voice-our-way.js
  common/data/the-pharmacy-of-colour.js
  common/model/generic-content-fields.js
  common/services/prismic/parsers.js
  common/views/components/DailyTourPromo/DailyTourPromo.js
  content/webapp/pages/article-series.js
  content/webapp/pages/article.js
  content/webapp/pages/book.js
  content/webapp/pages/event-series.js
  content/webapp/pages/event.js
  content/webapp/pages/exhibition.js
  content/webapp/pages/installation.js
  content/webapp/pages/page.js
  content/webapp/pages/place.js
  prismic-model/js/articles.js
  prismic-model/js/books.js
  prismic-model/js/event-series.js
  prismic-model/js/events.js
  prismic-model/js/exhibitions.js
  prismic-model/js/installations.js
  prismic-model/js/pages.js
  prismic-model/js/series.js
  prismic-model/js/webcomic-series.js
  prismic-model/js/webcomics.js
  prismic-model/json/articles.json
  prismic-model/json/books.json
  prismic-model/json/event-series.json
  prismic-model/json/events.json
  prismic-model/json/exhibitions.json
  prismic-model/json/installations.json
  prismic-model/json/pages.json
  prismic-model/json/series.json
  prismic-model/json/webcomic-series.json
  prismic-model/json/webcomics.json
Labels: feature

#3779 kill the server dependencies
  cardigan/stories/global/palette/palette.js
  common/views/components/Promo/Promo.config.js
  common/views/global/palette/palette.config.js
  eventbrite/app/.babelrc
  eventbrite/webapp/.babelrc
  eventbrite/webapp/app.js
  eventbrite/webapp/config.js
  eventbrite/webapp/controllers.js
  eventbrite/webapp/package.json
  eventbrite/webapp/views/components/eventbrite-button/eventbrite-button.njk
  eventbrite/webapp/views/components/eventbrite-button/eventbrite-ticket-status.njk
  eventbrite/webapp/webpack.config.js
  eventbrite/webapp/yarn.lock
Labels: improvement

#3775 add paginator to catalogue
  catalogue/webapp/pages/worksv2.js
  common/views/components/Buttons/Control/Control.js
  common/views/components/Pagination/Pagination.js
  common/views/components/Paginator/Paginator.js
  common/views/components/Paginator/README.md
Labels: improvement

#3795 apply lambda functions to @edge
  router/terraform/cloudfront.tf
Labels: improvement

#3796 add beacon to V2 API
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  common/koa-middleware/withToggles.js
  toggles/.DS_Store
  toggles/webapp/.DS_Store
  toggles/webapp/defaultToggleValues.json
Labels: improvement

#3793 Story promos and spacing sections
  cardigan/.cache/325c8f456729b912b0d2134054eb7448-dfeeb2271cc2857eb0a45a5003c8bbee
  cardigan/stories/components/Promos.js
  common/styles/base/_row.scss
  common/styles/components/_grid_placeholder.scss
  common/styles/components/_numbered_list.scss
  common/styles/components/_promo.scss
  common/styles/content.scss
  common/styles/critical.scss
  common/styles/utilities/_mixins.scss
  common/styles/utilities/_root-scope-classes.scss
  common/styles/works.scss
  common/views/components/SectionHeader/SectionHeader.js
  common/views/components/StoryPromo/StoryPromo.js
  common/views/components/StoryPromoFeatured/StoryPromoFeatured.js
  common/views/grid/container_queries/README.md
  common/views/grid/container_queries/container_queries.config.js
  common/views/grid/container_queries/container_queries.js
  content/webapp/pages/homepage.js
  content/webapp/pages/stories.js
  content/webapp/pages/whats-on.js
Labels: wip

#3799 Toggles state
  toggles/webapp/babel.config.js
  toggles/webapp/package.json
  toggles/webapp/pages/index.js
  toggles/webapp/yarn.lock
Labels: improvement

#3804 add promo styles back for works
  common/styles/components/_promo.scss
  common/styles/works.scss
Labels: bug

#3798 remove nginx way of redirecting
  router/nginx.conf
  router/redirects.conf
Labels: improvement

#3792 Deprecate DefaultPageLayout and PageWrapper for _app and PageLayout
  catalogue/webapp/package.json
  catalogue/webapp/pages/_app.js
  catalogue/webapp/pages/progress.js
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  catalogue/webapp/pages/worksv2.js
  catalogue/webapp/pages/workv2.js
  catalogue/webapp/services/catalogue/links.js
  catalogue/webapp/yarn.lock
  common/services/prismic/opening-times.js
  common/utils/json-ld.js
  common/views/components/Header/Header.js
  common/views/components/InfoBanner/InfoBanner.js
  common/views/components/MetaUnit/MetaUnit.js
  common/views/components/OpenGraphMetadata/OpenGraphMetadata.js
  common/views/components/PageLayout/PageLayout.js
  common/views/components/TwitterMetadata/TwitterMetadata.js
  common/views/pages/_document.js
  flow-typed/npm/fontfaceobserver_vx.x.x.js
  flow-typed/npm/lazysizes_vx.x.x.js
  flow-typed/npm/next_v7.x.x.js
  flow-typed/npm/next_vx.x.x.js
  package.json
Labels: improvement

#3797 remove some useless query params and add toggle_* cookie to cloudfront
  router/terraform/cloudfront.tf
Labels: improvement

#3806 add some redirects for the old drupal content
  router/nginx.conf
  router/webapp/redirects.json
Labels: improvement

#3811 update React universally
  cardigan/package.json
  cardigan/yarn.lock
  catalogue/webapp/yarn.lock
  common/package.json
  common/yarn.lock
  content/webapp/package.json
  content/webapp/yarn.lock
  pa11y/webapp/package.json
  pa11y/webapp/yarn.lock
Labels: improvement

#3818 add some redirects
  router/webapp/redirects.json
Labels: improvement

#3817 null check fields that make up physical description
  catalogue/webapp/pages/workv2.js
Labels: bug

#3820 unsupport wordpress articles in the listnerns
  content/terraform/terraform.tf
Labels: improvement

#3822 ensure toggles is null, so null check works in _app contructor
  catalogue/webapp/pages/_app.js
  catalogue/webapp/pages/workv2.js
  package.json
Labels: bug

#3821 use marc subfield ordering for Physical description
  catalogue/webapp/pages/workv2.js
Labels: improvement

#3824 add opening date to exhibition info box
  common/icons/calendar.js
  common/icons/index.js
  common/utils/dates.js
  content/webapp/pages/exhibition.js
Labels: improvement

#3819 Dash index
  .circleci/config.yml
  common/koa-middleware/withToggles.js
  dash/webapp/babel.config.js
  dash/webapp/components/Header.js
  dash/webapp/next.config.js
  dash/webapp/package.json
  dash/webapp/pages/index.js
  dash/webapp/pages/pa11y.js
  dash/webapp/pages/toggles.js
  dash/webapp/yarn.lock
  flow-typed/npm/next-cookies_vx.x.x.js
  flow-typed/npm/styled-components_vx.x.x.js
  pa11y/webapp/babel.config.js
  pa11y/webapp/package.json
  pa11y/webapp/pages/index.js
  pa11y/webapp/write-report.js
  pa11y/webapp/yarn.lock
  toggles/README.md
  toggles/webapp/defaults.json
  toggles/webapp/next.config.js
Labels: improvement
