Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2018-04, with the labels that each got.

#2428 upgrade to next5.1
  catalogue/webapp/package.json
  catalogue/webapp/yarn-error.log
  catalogue/webapp/yarn.lock
Labels: health

#2407 move /exhibitions/{id} to whats_on app
  common/model/exhibitions.js
  common/model/installations.js
  common/services/prismic/exhibitions.js
  common/services/prismic/installations.js
  common/services/prismic/parsers.js
  whats_on/app/controllers.js
  whats_on/app/routes.js
  whats_on/app/views/pages/exhibition.njk
  whats_on/app/views/pages/installation.njk
Labels: health

#2422 add page headers as a component type
  cardigan/docs/BodyBlock.jsx
  common/icons/index.js
  common/icons/status_indicator.js
  common/utils/classnames.js
  common/utils/format-date.js
  common/views/components/Index/index.js
  common/views/components/PageHeaders/ExhibitionPageHeader/ExhibitionPageHeader.config.js
  common/views/components/PageHeaders/ExhibitionPageHeader/ExhibitionPageHeader.js
  common/views/components/PageHeaders/Hero/Hero.config.js
  common/views/components/PageHeaders/Hero/Hero.js
  common/views/components/Picture/Picture.config.js
  common/views/components/WobblyEdge/WobblyEdge.config.js
  common/views/components/WobblyEdge/WobblyEdge.js
  common/views/components/layout/Container.js
  common/views/components/layout/Grid.js
  exhibitions/app/views/pages/exhibition.njk
Labels: techprofit

#2434 Add space for JSX
  common/views/components/CaptionedImage/CaptionedImage.js
  common/views/components/ImageGallery/ImageGallery.js
Labels: bug

#2435 Use 'ui' instead of 'display' for consistency
  server/content-model/events.js
  server/services/prismic-parsers.js
Labels: techprofit

#2433 Cardigan framed header
  common/styles/base/_container.scss
  common/styles/components/_framed_header.scss
  common/views/components/Index/index.js
  common/views/components/PageHeaders/FramedHeader/FramedHeader.config.js
  common/views/components/PageHeaders/FramedHeader/FramedHeader.js
  common/views/components/PageHeaders/PageHeaders.config.json
  common/views/hocs/hocs.config.js
  server/services/prismic.js
Labels: cardigan, feature

#2416 Exhibits in exhibitions
  client/js/components/async-content.js
  common/model/exhibitions.js
  common/package.json
  common/services/prismic/api.js
  common/services/prismic/exhibitions.js
  common/services/prismic/fetch-links.js
  common/services/prismic/installations.js
  common/services/prismic/parsers.js
  common/services/prismic/types.js
  common/views/components/Index/index.js
  common/views/components/InstallationPromo/InstallationPromo.js
  common/yarn.lock
  server/views/components/async/async.njk
  whats_on/app/controllers.js
  whats_on/app/package.json
  whats_on/app/routes.js
  whats_on/app/views/components/exhibits/exhibits.njk
  whats_on/app/views/pages/exhibition.njk
  whats_on/app/yarn.lock
  yarn.lock
Labels: feature

#2432 setup route for individual exhibitions to be served from whats_on app
  exhibitions/terraform/services.tf
  whats_on/terraform/services.tf
Labels: health

#2438 rename path rules uniquely in whats_on
  whats_on/terraform/services.tf
Labels: bug

#2437 null check text document before setting it's size
  common/services/prismic/exhibitions.js
Labels: bug

#2436 move installations to use event template
  cardigan/yarn-error.log
  common/views/components/Tags/Tags.js
  whats_on/app/controllers.js
  whats_on/app/views/pages/installation.njk
  yarn.lock
Labels: feature

#2439 Body on installations
  common/model/installations.js
  common/services/prismic/installations.js
  common/services/prismic/parsers.js
  prismic-model/js/installations.js
  prismic-model/js/parts/body.js
  prismic-model/js/parts/captioned-image-gallery-slice.js
  prismic-model/js/parts/captioned-image-slice.js
  prismic-model/js/parts/captioned-image.js
  prismic-model/js/parts/image.js
  prismic-model/js/parts/structured-text.js
  prismic-model/json/installations.json
  prismic-model/yarn-error.log
  whats_on/app/views/pages/installation.njk
Labels: feature, wip

#2448 only try to run the hack when you're on the event page
  client/js/components/eventbrite-ticket-button.js
  events/app/yarn-error.log
Labels: bug

#2442 Move `getUiEventSeries` into common
  common/model/background-texture.js
  common/services/prismic/events.js
  common/services/prismic/parsers.js
  common/styles/base/_container.scss
  events/app/controllers.js
  events/app/package.json
  events/app/webpack.config.js
  events/app/yarn-error.log
  events/app/yarn.lock
  server/index.js
  server/services/prismic.js
Labels: techprofit

#2450 be more protective before rendering installations and exhibitions
  whats_on/app/controllers.js
Labels: bug

#2452 add preview properly to exhibitions
  server/controllers/content.js
  server/views/layout/default.njk
  server/views/pages/article.njk
  whats_on/app/controllers.js
  whats_on/app/views/pages/exhibition.njk
Labels: bug

#2451 remove getExhibition from exhibitions app
  exhibitions/app/controllers.js
  exhibitions/app/views/pages/exhibition.njk
  server/content-model/exhibition.js
  server/index.js
  server/model/exhibition-and-related-content.js
  server/services/prismic-parsers.js
  server/services/prismic.js
Labels: health

#2462 make articlebody more basic and less right raily
  server/views/pages/article.njk
Labels: feature, wip

#2463 add link resovler and preview for installations
  server/controllers/content.js
  server/services/prismic-parsers.js
Labels: health

#2464 add opening hours props to exhibition opening hours
  server/views/layout/default.njk
  whats_on/app/views/pages/exhibition.njk
Labels: bug

#2459 order content old => new then new => old
  server/services/prismic.js
Labels: health

#2466 use 7 rather than 8 digita b number for sierra records
  catalogue/webapp/pages/work.js
  server/controllers/work.js
Labels: bug

#2465 at least tell the console where the error is when we have a JSX error
  server/extensions/component-jsx.js
Labels: health

#2456 create info page type
  common/model/info-page.js
  common/services/prismic/info-page.js
  common/services/prismic/parsers.js
  prismic-model/js/info-pages.js
  prismic-model/js/parts/body.js
  prismic-model/json/info-pages.json
  prismic-model/json/installations.json
  prismic-model/yarn-error.log
  server/controllers/content.js
  server/routes/index.js
  server/views/layout/default.njk
  server/views/pages/basic.njk
Labels: feature

#2457 Standfirst jsx
  common/views/components/Body/Body.config.json
  common/views/components/Body/Standfirst/Standfirst.config.js
  common/views/components/Body/Standfirst/Standfirst.js
  common/views/components/Index/index.js
  server/views/components/article-body/article-body.njk
  server/views/components/basic-body/basic-body.njk
  server/views/components/standfirst/standfirst.config.js
  server/views/components/standfirst/standfirst.njk
  whats_on/app/views/pages/exhibition.njk
Labels: techprofit

#2458 Jsx footer social map
  .gitignore
  common/styles/base/_fonts.scss
  common/styles/non-critical.scss
  common/styles/works.scss
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
  common/views/components/OpeningHours/OpeningHours.js
  common/views/components/OpeningHoursTable/OpeningHoursTable.js
  events/app/yarn-error.log
Labels: feature

#2468 add preview for info pages
  common/services/prismic/parsers.js
  server/controllers/content.js
  server/services/prismic-parsers.js
Labels: health

#2467 add spacing beneath installation tags
  whats_on/app/views/pages/installation.njk
Labels: bug

#2445 Start moving all wobbly line logic into the React component
  catalogue/webapp/yarn-error.log
  catalogue/webapp/yarn.lock
  common/package.json
  common/utils/prefixed-property-style-object.js
  common/views/components/Index/index.js
  common/views/components/WobblyEdge/WobblyEdge.config.js
  common/views/components/WobblyEdge/WobblyEdge.js
  common/yarn.lock
  events/app/views/pages/event-series.njk
  events/app/views/partials/event_with_schedule.njk
  flow-typed/npm/lodash.debounce_vx.x.x.js
  server/views/components/main-media/main-media.njk
  server/views/components/wobbly-edge/wobbly-edge.config.js
  server/views/components/wobbly-edge/wobbly-edge.njk
  server/views/pages/article.njk
  server/views/templates/article.njk
  whats_on/app/views/pages/exhibition.njk
Labels: wip

#2473 Add toggler to Tasl
  common/views/components/Tasl/Tasl.js
  common/views/hocs/withToggler.js
  server/extensions/component-jsx.js
Labels: bug

#2482 check for URI before running regex on it
  server/routes/index.js
Labels: bug

#2479 fix typing on withToggler HOC
  catalogue/webapp/pages/work.js
  common/views/hocs/withToggler.js
Labels: bug

#2486 only render image if it has an contentUrl
  server/views/components/article-body/article-body.njk
Labels: bug

#2487 set featuresCohort cookie on infra project
  nginx-proxy/nginx.conf
Labels: bug

#2494 remove instagram list and add contentList
  prismic-model/js/parts/body.js
  prismic-model/js/parts/captioned-image.js
  prismic-model/json/info-pages.json
  server/controllers/async-controllers.js
  server/routes/index.js
  server/services/instagram.js
  whats_on/app/views/components/exhibits/exhibits.njk
Labels: feature

#2498 Remapper service
  prismic-model/json/exhibitions.json
  prismic_remapper/README.md
  prismic_remapper/_eg-promo-split/after.json
  prismic_remapper/_eg-promo-split/before.json
  prismic_remapper/_eg-promo-split/remap.js
  prismic_remapper/package.json
  prismic_remapper/remap.js
  prismic_remapper/yarn.lock
Labels: feature

#2488 run a really rudimentary pa11y report
  .circleci/config.yml
  .gitignore
  pa11y_report.js
  package.json
  yarn.lock
Labels: feature

#2500 JSXy Quote component
  common/views/components/Index/index.js
  common/views/components/PrismicHtmlBlock/PrismicHtmlBlock.config.js
  common/views/components/PrismicHtmlBlock/PrismicHtmlBlock.js
  common/views/components/Quote/Quote.config.js
  common/views/components/Quote/Quote.js
  server/services/prismic-body-parser.js
  server/views/components/article-body/article-body.njk
  server/views/components/basic-body/basic-body.njk
  server/views/components/quote/quote.config.js
  server/views/components/quote/quote.njk
Labels: health

#2501 couple of fixes to make installations work
  common/services/prismic/fetch-links.js
  common/services/prismic/installations.js
  prismic-model/js/installations.js
  prismic-model/js/parts/description.js
  prismic-model/json/installations.json
Labels: bug

#2496 Render content list
  .eslintrc.json
  common/model/info-pages.js
  common/model/multi-content.js
  common/services/prismic/fetch-links.js
  common/services/prismic/info-page.js
  common/services/prismic/info-pages.js
  common/services/prismic/multi-content.js
  common/services/prismic/parsers.js
  common/views/components/BasicBody/BasicBody.js
  common/views/components/BasicPromo/BasicPromo.js
  common/views/components/CaptionedImage/CaptionedImage.js
  common/views/components/ContentList/ContentList.js
  common/views/components/ContentList/ContentListItems.js
  common/views/components/Image/Image.js
  common/views/components/Index/index.js
  prismic-model/js/parts/body.js
  prismic-model/json/info-pages.json
  server/controllers/async-controllers.js
  server/controllers/content.js
  server/package.json
  server/routes/index.js
  server/views/components/basic-body/basic-body.njk
  server/views/pages/article.njk
  server/views/pages/basic.njk
  server/yarn.lock
  whats_on/app/views/pages/installation.njk
Labels: feature

#2502 upgrade all packages in catalogue app
  catalogue/webapp/package.json
  catalogue/webapp/yarn.lock
Labels: health

#2524 simplify the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: health

#2522 only run event series code once we know there is an event series
  events/app/controllers.js
Labels: bug

#2515 add basic skeleton for image model
  common/model/events.js
  common/services/prismic/parsers.js
  common/views/components/ImageGallery/ImageGallery.js
  common/views/components/Images/Images.js
  common/views/components/PrismicHtmlBlock/PrismicHtmlBlock.js
  common/views/components/Tasl/Tasl.js
  server/services/prismic-body-parser.js
  server/utils/body-parser.js
Labels: techprofit

#2532 add prototype route for basicPages
  server/controllers/content.js
  server/routes/index.js
Labels: feature

#2523 move nextjs catalogue app to /catalogue
  catalogue/terraform/terraform.tf
  catalogue/webapp/pages/catalogue/work.js
  catalogue/webapp/pages/catalogue/works.js
Labels: health

#2470 beginnings of pally
  dash/pa11y_dashboard/Dockerfile
  dash/pa11y_dashboard/Makefile
  dash/pa11y_dashboard/README.md
  dash/pa11y_dashboard/docker-compose.yml
  dash/pa11y_dashboard/docker-entrypoint.sh
  dash/pa11y_dashboard/terraform/iam.tf
  dash/pa11y_dashboard/terraform/locals.tf
  dash/pa11y_dashboard/terraform/services.tf
  dash/pa11y_dashboard/terraform/task_definition.json.template
  dash/pa11y_dashboard/terraform/terraform.tf
  dash/pa11y_dashboard/terraform/topics.tf
  dash/terraform/ami.tf
  dash/terraform/asg.tf
  dash/terraform/ecs.tf
  dash/terraform/iam.tf
  dash/terraform/locals.tf
  dash/terraform/terraform.tf
  dash/terraform/topics.tf
  dash/terraform/userdata.tf
  dash/terraform/variables.tf
Labels: accessibility

#2536 Use secondary link for 'Search results'
  common/views/components/Links/SecondaryLink/SecondaryLink.js
  common/views/components/WorkMedia/WorkMedia.js
  common/views/components/WorkMedia/WorkMedia2.js
  server/views/components/work-media/work-media.config.js
  server/views/components/work-media/work-media.njk
Labels: bug

#2504 Installation contributors
  common/model/contributors.js
  common/model/events.js
  common/model/people.js
  common/model/picture.js
  common/services/prismic/parsers.js
  common/views/components/Contributor/Contributor.js
  common/views/components/Image/Image.js
  common/views/components/Index/index.js
  events/app/views/partials/event_with_schedule.njk
  whats_on/app/views/pages/installation.njk
Labels: feature

#2543 remove exhibitions service
  .circleci/config.yml
  app_cluster/terraform/asg.tf
  build/exhibitions_webapp.yml
  exhibitions/app/.babelrc
  exhibitions/app/app.js
  exhibitions/app/controllers.js
  exhibitions/app/package.json
  exhibitions/app/routes.js
  exhibitions/app/setup-app.js
  exhibitions/app/test/app.js
  exhibitions/app/views/pages/exhibitions.njk
  exhibitions/app/webpack.config.js
  exhibitions/app/yarn.lock
  whats_on/app/views/pages/exhibitions.njk
  whats_on/terraform/services.tf
Labels: techprofit

#2530 Button styles
  common/icons/check.js
  common/icons/chevron.js
  common/icons/email.js
  common/icons/index.js
  common/styles/components/_back-to-top.scss
  common/styles/components/_buttons.scss
  common/styles/components/_control.scss
  common/styles/non-critical.scss
  common/styles/works.scss
  common/views/components/Buttons/Button/Button.config.js
  common/views/components/Buttons/Button/Button.js
  common/views/components/Buttons/Button/README.md
  common/views/components/Buttons/ButtonButton/ButtonButton.config.js
  common/views/components/Buttons/ButtonButton/ButtonButton.js
  common/views/components/Buttons/Control/Control.config.js
  common/views/components/Buttons/Control/Control.js
  common/views/components/Buttons/Control/README.md
  common/views/components/CopyUrl/CopyUrl.js
  common/views/components/EventBookingButton/EventBookingButton.js
  common/views/components/ImageViewer/ImageViewer.js
  common/views/components/ImageViewer/ImageViewer2.js
  common/views/components/Index/index.js
  common/views/components/PageHeaders/Hero/Hero.js
  common/views/components/Pagination/Pagination.js
  common/views/components/ScrollToInfo/ScrollToInfo.config.js
  common/views/components/ScrollToInfo/ScrollToInfo.js
  common/views/components/WorkMedia/WorkMedia.js
  common/views/components/WorkMedia/WorkMedia2.js
  eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
  events/app/views/partials/event_without_schedule.njk
  server/views/components/back-to-top/back-to-top.njk
  server/views/components/button-button/button-button.config.js
  server/views/components/button-input/button-input.config.js
  server/views/components/button-input/button-input.njk
  server/views/components/button-link/button-link.config.js
  server/views/components/button-link/button-link.njk
  server/views/components/copy-url/copy-url.njk
  server/views/components/image-viewer/image-viewer.njk
  server/views/components/pagination/pagination.config.js
  server/views/components/pagination/pagination.njk
  server/views/icons/email.svg
  server/views/pages/flags.njk
  server/views/pages/search.njk
  server/views/pages/work.njk
Labels: feature, techprofit

#2546 Catalogue urls
  catalogue/webapp/pages/catalogue/work.js
  catalogue/webapp/pages/catalogue/works.js
  catalogue/webapp/server.js
Labels: health

#2548 Offset the transporter by the same amount as if it were in an .article
  common/styles/components/_body_part.scss
Labels: bug

#2549 Space out event-series promos
  events/app/views/pages/event-series.njk
Labels: bug

#2551 Use a secondary link for opening hours
  whats_on/app/views/components/whats-on-list-header/whats-on-list-header.njk
Labels: bug

#2550 Show three past events, not two
  events/app/controllers.js
Labels: bug

#2553 add tags to info pages
  prismic-model/js/info-pages.js
  prismic-model/js/tag-types.js
  prismic-model/js/tags.js
  prismic-model/json/info-pages.json
  prismic-model/json/tag-types.json
  prismic-model/json/tags.json
Labels: feature

#2552 Prepare info page for migration
  common/model/info-pages.js
  common/services/prismic/info-pages.js
  prismic-model/js/info-pages.js
  prismic-model/js/parts/link.js
  prismic-model/js/parts/text.js
  prismic-model/json/info-pages.json
  server/controllers/content.js
Labels: feature

#2560 Fix Node version on catalogue docker file
  catalogue/webapp/Dockerfile
Labels: bug

#2562 push /catalogue through to v2
  router/nginx.conf
Labels: health
