Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2018-06, with the labels that each got.

#2767 put promos on articles
  common/services/prismic/parsers.js
  common/utils/json-ld.js
  server/controllers/content.js
  server/services/prismic-parsers.js
  server/utils/body-parser.js
  server/utils/json-ld.js
  server/utils/prismic-parser.js
  server/views/components/twitter-card/twitter-card.njk
  server/views/pages/article.njk
  server/views/pages/curated-lists.njk
Labels: bug

#2771 use UiImage for contributors
  common/model/contributors.js
  common/model/events.js
  common/model/people.js
  common/services/prismic/parsers.js
  common/views/components/BasePage/BookPage.js
  common/views/components/Contributor/Contributor.js
  common/views/components/Contributors/Contributors.js
  common/views/components/Index/index.js
  events/app/views/partials/event_without_schedule.njk
Labels: techprofit

#2770 Retire njk captioned image
  common/services/prismic/parsers.js
  common/views/components/ChapterIndicator/ChapterIndicator.js
  common/views/components/Images/Images.js
  common/views/components/Index/index.js
  common/views/components/MainMedia/MainMedia.js
  common/views/components/StaticWorksContent/StaticWorksContent.js
  server/filters/get-principle-main-media.js
  server/model/media.js
  server/services/prismic-parsers.js
  server/views/components/main-media-comic/main-media-comic.config.js
  server/views/components/main-media-comic/main-media-comic.njk
  server/views/components/main-media/main-media.config.js
  server/views/components/main-media/main-media.njk
  server/views/pages/article.njk
  server/views/pages/catalogue-item.njk
Labels: techprofit

#2772 remove captioned-image and chapter-indicator components
  server/views/components/captioned-image/captioned-image.config.js
  server/views/components/captioned-image/captioned-image.njk
  server/views/components/chapter-indicator/chapter-indicator.config.js
  server/views/components/chapter-indicator/chapter-indicator.njk
Labels: techprofit

#2773 track catalogue ga on both accounts
  common/utils/analytics.js
Labels: health

#2777 Work embed
  catalogue/terraform/terraform.tf
  catalogue/webapp/pages/embed.js
  catalogue/webapp/server.js
  common/styles/utilities/_root-scope-classes.scss
  common/views/components/ImageViewer/ImageViewer2.js
  common/views/components/ImageViewer/ImageViewerImage.js
Labels: feature

#2788 bye tumblr
  common/views/components/FooterSocial/FooterSocial.js
Labels: health

#2787 add books to v2 route
  router/nginx.conf
Labels: drupal 🤢

#2795 use JSON.stringify on tracking for clear search
  common/views/components/SearchBox/SearchBox.js
Labels: bug

#2797 fix scroll to info tracking
  common/views/components/PageHeaders/Hero/Hero.js
  common/views/components/WorkMedia/WorkMedia.js
  common/views/components/WorkMedia/WorkMedia2.js
  server/views/components/scroll-to-info/scroll-to-info.config.js
  server/views/components/scroll-to-info/scroll-to-info.njk
Labels: bug

#2790 add a hypothetical embed script to be included with the oembed endpoint
  client/embed.js
  client/gulpfile.js
  client/js/components/image-viewer.js
Labels: feature

#2786 Add oEmbed endpoint and update embed endpoint to have credit.
  catalogue/webapp/pages/embed.js
  catalogue/webapp/server.js
  common/data/licenses.js
  common/model/work.js
  common/styles/utilities/_root-scope-classes.scss
  common/views/components/ImageViewer/ImageViewer2.js
  common/views/components/WorkCredit/WorkCredit.js
  common/views/components/WorkEmbed/WorkEmbed.js
  common/views/components/WorkImage/WorkImage.js
  server/controllers/work.js
  server/routes/index.js
Labels: feature

#2812 add caption to images
  common/services/prismic/parsers.js
Labels: bug

#2799 add unleash for feature flags
  common/package.json
  common/services/unleash/feature-flags.js
  common/test/services/unleash/feature-flags.test.js
  common/yarn.lock
Labels: feature

#2813 contributing labels update
  CONTRIBUTING.md
Labels: improvement

#2819 add oembed to works page
  common/views/components/WorkEmbed/WorkEmbed.js
  common/views/components/WorkImage/WorkImage.js
  server/controllers/work.js
  server/views/pages/work.njk
Labels: feature

#2815 Remove njk components
  common/styles/benched.scss
  common/styles/components/_new_site_notice.scss
  server/views/components/new-site-notice/new-site-notice.config.js
  server/views/components/new-site-notice/new-site-notice.njk
  server/views/components/organization-list/organization-list.config.js
  server/views/components/organization-list/organization-list.njk
  server/views/components/search-box/search-box.config.js
  server/views/components/search-box/search-box.njk
  server/views/components/tags/tags.config.js
  server/views/components/tags/tags.njk
  server/views/components/tasl/tasl.config.js
  server/views/components/tasl/tasl.njk
  server/views/components/work-drawer/work-drawer.config.js
  server/views/components/work-drawer/work-drawer.njk
  server/views/pages/search.njk
  whats_on/app/views/pages/exhibition.njk
Labels: techprofit

#2810 Remove ticket reference from PR template we're using projects.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: improvement

#2805 Api v2 test
  catalogue/webapp/package.json
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  catalogue/webapp/server.js
  catalogue/webapp/yarn.lock
  common/model/flags.js
  common/services/unleash/feature-flags.js
  common/views/components/Links/SecondaryLink/SecondaryLink.js
  common/views/components/PageWrapper/PageWrapper.js
  common/views/components/Pagination/Pagination.js
  common/views/components/WorkMedia/WorkMedia2.js
Labels: test

#2821 Check font declaration exists
  common/styles/utilities/_mixins.scss
Labels: bug

#2823 Order the button tracking arguments correctly so ga data isn't junk
  common/views/components/ImageViewer/ImageViewer.js
Labels: bug

#2824 add better, more colourful deploy script
  .circleci/config.yml
  deploy/deploy_service.js
  deploy/deploy_service.py
  deploy/package.js
  package.json
  yarn.lock
Labels: feature

#2832 make sure we store flags in clientStore
  common/views/components/PageWrapper/PageWrapper.js
Labels: test, wip

#2831 Wp series
  server/controllers/async-controllers.js
  server/model/article.js
Labels: bug

#2830 add book tag to books
  common/views/components/BasePage/BookPage.js
  common/views/components/BasePage/InstallationPage.js
Labels: health

#2825 handle errors from 404 exhibition lookup on installations
  client/js/components/async-content.js
  whats_on/app/controllers.js
Labels: bug

#2814 add title and favicon to storybook
  cardigan_beta/.storybook/manager-head.html
Labels: health

#2837 put the order link behind the books switch
  common/views/components/BasePage/BookPage.js
Labels: bug

#2838 send HTMLString to standfirst from prismic
  server/services/prismic-body-parser.js
  server/views/components/article-body/article-body.njk
Labels: bug

#2842 use primihtmlblock for article body text
  common/views/components/Index/index.js
  server/views/components/article-body/article-body.njk
Labels: bug

#2844 Wrap PrismicHtmlBlock component in 'body-text' class
  server/views/components/article-body/article-body.njk
Labels: bug

#2846 add whats_on tests to cirleci
  .circleci/config.yml
  .gitignore
  common/package.json
  server/middleware/error.js
Labels: health

#2836 Api v2 test api call
  catalogue/webapp/package.json
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  catalogue/webapp/utils/remap-v2-to-v1.js
  catalogue/webapp/yarn.lock
  common/views/components/PageWrapper/PageWrapper.js
Labels: test

#2849 Standalone design QA amends
  common/styles/components/_divider.scss
  common/styles/utilities/_root-scope-classes.scss
  common/views/components/EventPromo/EventPromo.js
  common/views/components/ExhibitionPromo/ExhibitionPromo.js
  common/views/components/NewsletterPromo/NewsletterPromo.js
  server/views/pages/homepage.njk
Labels: bug

#2850 actually push catalogue app to docker
  .circleci/config.yml
Labels: bug

#2866 remove datePublished from books template
  common/views/components/BasePage/BookPage.js
Labels: health

#2868 check for image on work before trying to render
  catalogue/webapp/pages/work.js
Labels: bug

#2865 allow setting of cohort from query string in next app
  catalogue/webapp/server.js
Labels: feature

#2829 Books contributor model
  common/model/books.js
  common/services/prismic/books.js
  common/views/components/BasePage/BookPage.js
  deploy/package.json
  prismic-model/js/books.js
  prismic-model/json/books.json
  prismic-model/json/events.json
Labels: health

#2854 remove title from contributors component
  common/views/components/Contributors/Contributors.js
  events/app/views/partials/event_with_schedule.njk
  events/app/views/partials/event_without_schedule.njk
Labels: improvement

#2869 change image dependant on cohort and ID of event for A/B test
  server/services/prismic-parsers.js
  server/services/prismic.js
  server/utils/flags.js
Labels: test

#2856 add research template to issue template and description of research tags
  CONTRIBUTING.md
  ISSUE_TEMPLATE/feature.md
  ISSUE_TEMPLATE/research.md
Labels: feature

#2861 Events service in common
  common/model/events.js
  common/services/prismic/event-series.js
  common/services/prismic/events.js
  common/services/prismic/fetch-links.js
  common/services/prismic/multi-content.js
  common/services/prismic/parsers.js
  common/views/components/BasePage/EventPage.js
  common/views/components/Index/index.js
  events/app/controllers.js
  whats_on/app/controllers.js
  whats_on/app/routes.js
  whats_on/app/views/pages/event.njk
Labels: feature

#2857 remove books metadata flag
  common/views/components/BasePage/BookPage.js
  server/views/pages/book.njk
Labels: test

#2873 Remove cream bg from image on article page
  server/views/components/article-body/article-body.njk
Labels: bug

#2875 add eventbrite service to deploy script with config fetch
  deploy/deploy_service.js
  deploy/terraform_apply_service.sh
  deploy/yarn.lock
Labels: improvement

#2877 chnge label of contribution description
  prismic-model/js/parts/contributors.js
  prismic-model/json/books.json
  prismic-model/json/events.json
  prismic-model/json/exhibitions.json
  prismic-model/json/installations.json
Labels: health

#2876 Use the Caption component in the gif-video
  common/styles/components/_gif_video.scss
  common/views/components/Index/index.js
  server/services/prismic-body-parser.js
  server/views/components/article-body/article-body.njk
  server/views/components/gif-video/gif-video.njk
Labels: techprofit

#2880 show installations tag
  whats_on/app/controllers.js
Labels: bug

#2878 Contributors heading
  common/test/components/Contributors.test.js
  common/views/components/BasePage/BookPage.js
  common/views/components/BasePage/EventPage.js
  common/views/components/BasePage/InstallationPage.js
  common/views/components/Contributors/Contributors.js
Labels: improvement

#2881 add body to places
  prismic-model/js/parts/geolocation.js
  prismic-model/js/places.js
  prismic-model/json/places.json
Labels: feature

#2882 add places rendering
  common/model/places.js
  common/services/prismic/parsers.js
  common/services/prismic/places.js
  common/views/components/BasePage/PlacePage.js
  common/views/components/Index/index.js
  server/controllers/content.js
  server/routes/index.js
  server/views/pages/place.njk
Labels: feature

#2884 add flags for publis access and free to Wellcome organisation
  common/model/organization.js
  yarn.lock
Labels: health

#2887 remove links to past events and exhibitions
  events/app/views/pages/events.njk
  whats_on/app/views/pages/exhibitions.njk
Labels: health

#2890 Declare normal letter-spacing if not defined
  common/styles/utilities/_mixins.scss
Labels: bug

#2891 set cohort cookie properly from catalogue app
  catalogue/webapp/server.js
Labels: bug

#2895 QA tweaks
  common/icons/arrow_small.js
  common/icons/index.js
  common/views/components/Links/PrimaryLink/PrimaryLink.js
  server/views/pages/homepage.njk
Labels: improvement

#2899 add tracking to email address
  events/app/views/partials/event_without_schedule.njk
Labels: analytics

#2903 remove comma
  events/app/views/partials/event_without_schedule.njk
Labels: bug

#2907 set preview on preview.
  server/middleware/error.js
Labels: bug

#2905 serve an error when we get one back from the API
  catalogue/webapp/pages/works.js
Labels: bug

#2906 restore most of the works analytics
  catalogue/webapp/pages/work.js
  common/utils/analytics.js
  common/views/components/CopyUrl/CopyUrl.js
  common/views/components/ImageViewer/ImageViewer2.js
  common/views/components/PageWrapper/PageWrapper.js
  common/views/components/WorkMedia/WorkMedia2.js
Labels: bug

#2897 remove redundant listener in catalogue app
  catalogue/terraform/terraform.tf
Labels: health

#2911 preview on error page
  server/middleware/error.js
Labels: bug

#2913 add logging to see where the problem is with preview
  server/middleware/error.js
Labels: bug

#2916 add pocket meta tag
  server/views/layout/default.njk
Labels: feature

#2920 add contributor title flag to installations
  common/views/components/BasePage/InstallationPage.js
  whats_on/app/views/pages/installation.njk
Labels: test

#2918 remove pocket site verification
  server/views/layout/default.njk
Labels: bug

#2915 add Host header to weapp nginx and remove logging
  nginx_webapp/nginx.conf
  server/middleware/error.js
Labels: bug

#2934 remove event ordering on event series
  common/services/prismic/event-series.js
  events/app/controllers.js
Labels: bug
