Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2018-03, with the labels that each got.

#2283 add event title to event mailto links
  common/views/components/Tags/Tags.js
  events/app/views/pages/event.njk
  server/extensions/component-jsx.js
Labels: feature, health

#2285 Added global message about early closing
  server/views/layout/default.njk
Labels: wip

#2298 Next footer
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
  common/views/components/Footer/Footer.js
  common/views/components/OpeningHours/OpeningHours.js
Labels: feature

#2299 Use componentJsx for the v2 footer
  server/views/layout/default.njk
Labels: health

#2300 Update active nav item
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
  common/views/components/Header/Header.js
Labels: bug

#2282 Metaunit next links
  common/views/components/MetaUnit/MetaUnit.js
  common/views/components/Pagination/Pagination.js
  common/views/components/WorkPromo/WorkPromo.js
Labels: health

#2297 add infra for catalogue
  catalogue/terraform/terraform.tf
  router/terraform/asg.tf
  router/terraform/cloudfront.tf
  router/terraform/services.tf
  router/terraform/terraform.tf
Labels: feature

#2309 update the origin IDs being used by the cache behavoiurs
  router/terraform/cloudfront.tf
Labels: bug

#2302 add toggler HOC for work drawer
  catalogue/webapp/pages/work.js
  catalogue/webapp/yarn.lock
  common/.babelrc
  common/package.json
  common/views/components/Header/HeadJs.js
  common/views/components/WorkDrawer/WorkDrawer.js
  common/views/hocs/withToggler.js
  common/yarn.lock
  events/app/yarn.lock
  server/extensions/component-jsx.js
Labels: feature

#2311 allow HTML in contributor description
  server/services/prismic-parsers.js
Labels: bug

#2310 add event series to Google analytics
  events/app/controllers.js
Labels: health

#2308 add event series to promo
  server/views/components/event-promo/event-promo.njk
Labels: feature

#2314 trim momentjs
  catalogue/webapp/next.config.js
  catalogue/webapp/timezones.json
Labels: health

#2315 make really critical scss
  catalogue/webapp/next.config.js
  catalogue/webapp/pages/_document.js
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  common/data/series.js
  common/package.json
  common/utils/image-sizes.js
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
  common/views/components/Header/Header.js
  common/views/components/Promo/Promo.config.js
  common/views/pages/_document.js
Labels: health

#2316 reinstate lazysizes and fontobservers
  catalogue/webapp/package.json
  common/package.json
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
  common/views/components/FindUs/FindUs.js
  common/views/components/Header/NastyJs.js
  common/views/components/Image/Image.js
  common/views/components/layout/preview-no-container.js
  common/views/components/layout/preview.js
  common/yarn.lock
Labels: health

#2326 include node_modules in docker builds
  .dockerignore
Labels: bug

#2317 _document as function to be able to pass specific CSS through
  catalogue/webapp/pages/_document.js
  common/styles/works.scss
  common/views/pages/_document.js
Labels: health

#2318 use JS to make fancy burgers
  common/views/components/Header/Header.js
Labels: health

#2313 Bundle analyzer static reporting
  .circleci/config.yml
  catalogue/webapp/docker-compose.yml
  catalogue/webapp/next.config.js
  catalogue/webapp/package.json
  catalogue/webapp/yarn.lock
  common/package.json
Labels: health

#2335 fix repo caching in circle on the catalogue
  .circleci/config.yml
Labels: bug

#2337 s/seats/spaces
  events/app/views/partials/event_without_schedule.njk
Labels: health

#2331 update parsers for wordpress
  prismic-model/articles.json
  server/services/prismic-parsers.js
  server/utils/body-parser.js
Labels: health

#2342 check for article before retrieving displayType
  prismic-model/articles.json
  server/controllers/content.js
Labels: health

#2336 track event booking buttons
  events/app/views/partials/event_without_schedule.njk
Labels: health

#2346 remove page display
  prismic-model/articles.json
Labels: health

#2364 add prismic model JS => JSON converter and installations type
  prismic-model/.babelrc
  prismic-model/README.md
  prismic-model/convert.js
  prismic-model/js/installations.js
  prismic-model/js/parts/contributors.js
  prismic-model/js/parts/description.js
  prismic-model/js/parts/promo.js
  prismic-model/js/parts/title.js
  prismic-model/json/articles.json
  prismic-model/json/audiences.json
  prismic-model/json/books.json
  prismic-model/json/curated-lists.json
  prismic-model/json/editorial-contributor-roles.json
  prismic-model/json/event-formats.json
  prismic-model/json/event-series.json
  prismic-model/json/events.json
  prismic-model/json/exhibitions.json
  prismic-model/json/featureflag.json
  prismic-model/json/featurescohort.json
  prismic-model/json/installations.json
  prismic-model/json/interpretation-types.json
  prismic-model/json/organisations.json
  prismic-model/json/people.json
  prismic-model/json/places.json
  prismic-model/json/series.json
  prismic-model/json/teams.json
  prismic-model/json/webcomic-series.json
  prismic-model/json/webcomics.json
  prismic-model/package.json
  prismic-model/yarn.lock
Labels: feature

#2369 Common flow
  common/data/series.js
  common/model/content-blocks.js
  common/model/editorial-series.js
  common/model/events.js
  common/model/organization.js
  common/utils/camelize.js
  common/utils/classnames.js
  common/utils/convert-image-uri.js
  common/utils/get-icon-for-content-type.js
  common/utils/get-license-info.js
  common/utils/get-series-title.js
  common/utils/image-sizes.js
  common/utils/json-ld.js
  common/utils/striptags.js
  common/utils/tracking.js
  common/utils/truncate.js
  common/views/components/Author/Author.js
  common/views/components/EventBookingButton/EventBookingButton.js
  common/views/components/EventScheduleItem/EventScheduleItem.js
  common/views/components/FooterWellcomeLogo/FooterWellcomeLogo.js
  common/views/components/Header/Header.js
  common/views/components/InfoBanner/InfoBanner.js
  common/views/components/License/License.js
  common/views/components/Promo/Promo.js
  common/views/components/StaticWorksContent/StaticWorksContent.js
  common/views/components/Tags/Tags.js
  common/views/hocs/withToggler.js
  events/app/controllers.js
  events/app/views/partials/event_with_schedule.njk
  events/app/views/partials/event_without_schedule.njk
  server/content-model/events.js
  server/services/prismic-parsers.js
Labels: techprofit

#2365 Installations from prismic
  common/model/content-blocks.js
  common/model/contributors.js
  common/model/events.js
  common/model/image-promo.js
  common/model/installations.js
  common/model/license.js
  common/model/people.js
  common/model/person.js
  common/model/picture.js
  common/model/tasl.js
  common/package.json
  common/services/prismic/api.js
  common/services/prismic/fetch-links.js
  common/services/prismic/installations.js
  common/services/prismic/parsers.js
  common/services/prismic/types.js
  common/utils/breakpoints.js
  common/views/components/Index/index.js
  common/views/components/License/License.config.js
  common/views/components/Picture/Picture.config.js
  common/views/components/Picture/Picture.js
  common/views/components/Tasl/Tasl.js
  common/yarn.lock
  exhibitions/app/views/pages/exhibition.njk
  flow-typed/npm/prismic-dom_vx.x.x.js
  server/filters/format-date.js
  server/package.json
  server/views/components/picture/picture.njk
  server/yarn.lock
  whats_on/app/.babelrc
  whats_on/app/controllers.js
  whats_on/app/package.json
  whats_on/app/routes.js
  whats_on/app/views/pages/installation.njk
  whats_on/app/webpack.config.js
  whats_on/app/yarn.lock
  yarn.lock
Labels: feature

#2379 remove reference to exhibition body
  exhibitions/app/views/pages/exhibition.njk
  server/content-model/exhibition.js
  server/services/prismic-parsers.js
Labels: bug

#2352 Additional text on more info links, specifically for screen readers
  common/views/components/EventScheduleItem/EventScheduleItem.js
  common/views/components/MoreInfoLink/MoreInfoLink.js
Labels: wip

#2377 Event schedule contributors
  events/app/views/partials/event_with_schedule.njk
  server/services/prismic-parsers.js
Labels: feature

#2373 Installation ui dates
  common/model/installations.js
  common/services/prismic/installations.js
  common/services/prismic/parsers.js
  prismic-model/js/installations.js
  prismic-model/js/parts/timestamp.js
  prismic-model/json/installations.json
  whats_on/app/views/pages/installation.njk
Labels: feature

#2383 add prismic preview toolbar as test to articles
  common/styles/components/_prismic_toolbar.scss
  common/styles/non-critical.scss
  server/services/prismic-parsers.js
  server/views/pages/article.njk
Labels: feature

#2381 upgrade flow
  catalogue/webapp/pages/works.js
  common/services/prismic/article.js
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
  common/views/components/EventScheduleItem/EventScheduleItem.js
  common/views/components/Header/Header.js
  common/views/components/Pagination/Pagination.js
  events/app/views/partials/event_with_schedule.njk
  package.json
  yarn.lock
Labels: techprofit

#2389 Type check image gallery and move to JSX
  common/model/picture.js
  common/utils/get-license-info.js
  common/views/components/CaptionedImage/CaptionedImage.js
  common/views/components/ImageGallery/ImageGallery.config.js
  common/views/components/ImageGallery/ImageGallery.js
  common/views/components/Index/index.js
  exhibitions/app/views/pages/exhibition.njk
  server/model/exhibition-and-related-content.js
  server/model/license.js
  server/views/components/article-body/article-body.njk
  server/views/components/basic-body/basic-body.njk
  server/views/components/image-gallery/image-gallery.config.js
  server/views/components/image-gallery/image-gallery.njk
  server/views/components/license/license.config.js
Labels: bug

#2392 add prismic preview code onto 4040 pages
  server/middleware/error.js
  server/views/pages/error.njk
Labels: bug

#2334 add heading to stories page as test
  prismic-model/json/curated-lists.json
  server/views/pages/curated-lists.njk
Labels: test

#2390 add description and place to installation
  common/model/installations.js
  common/model/place.js
  common/services/prismic/fetch-links.js
  common/services/prismic/installations.js
  common/services/prismic/parsers.js
  prismic-model/json/events.json
  whats_on/app/views/pages/installation.njk
Labels: feature

#2391 add listener to what_on service for installations
  whats_on/terraform/services.tf
Labels: feature

#2398 Add space in footer address
  common/views/components/FindUs/FindUs.js
Labels: bug

#2405 run test on cookie notification position
  common/styles/components/_cookie_notification.scss
  server/views/components/cookie-notification/cookie-notification.njk
  server/views/layout/default.njk
Labels: test

#2404 remove search for now
  common/views/components/Header/Header.js
  server/views/components/header/header.njk
Labels: health

#2396 Installation exhibition relations
  prismic-model/js/exhibitions.js
  prismic-model/js/parts/contributors.js
  prismic-model/js/parts/description.js
  prismic-model/js/parts/link.js
  prismic-model/js/parts/list.js
  prismic-model/js/parts/number.js
  prismic-model/js/parts/place.js
  prismic-model/js/parts/promo.js
  prismic-model/js/parts/structured-text.js
  prismic-model/js/parts/timestamp.js
  prismic-model/js/parts/title.js
  prismic-model/json/exhibitions.json
Labels: feature

#2410 use the correct tasl stuff on article body
  server/views/components/article-body/article-body.njk
Labels: bug

#2403 Global alert message
  client/js/components/info-banner.js
  common/model/global-alert.js
  common/views/components/Index/index.js
  common/views/components/InfoBanner/InfoBanner.js
  prismic-model/json/global-alert.json
  server/controllers/content.js
  server/controllers/work.js
  server/index.js
  server/services/interval-cache.js
  server/services/prismic.js
  server/view/render.js
  server/views/layout/default.njk
Labels: feature

#2418 use contributor model for events contributors
  events/app/views/partials/event_without_schedule.njk
Labels: bug

#2419 s/every one/everyone
  events/app/views/partials/event_without_schedule.njk
Labels: bug

#2420 s/exceptional/modified
  common/views/components/OpeningHours/OpeningHours.js
  server/views/pages/opening-times.njk
Labels: health

#2424 add scroll to exhibition content
  common/views/components/Index/index.js
  common/views/components/ScrollToInfo/ScrollToInfo.js
  exhibitions/app/views/pages/exhibition.njk
Labels: feature

#2425 better event labelling on event schedules
  common/views/components/EventScheduleItem/EventScheduleItem.js
Labels: health

#2423 only use the event once we know it exists
  server/services/prismic.js
Labels: bug
