Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2018-10, with the labels that each got.

#3389 Serial navigation
  common/model/article-schedule-items.js
  common/model/multi-content.js
  common/views/components/ArticleCard/ArticleCard.js
  common/views/components/CompactCard/CompactCard.js
  common/views/components/EventCard/EventCard.js
  common/views/components/PartNumberIndicator/PartNumberIndicator.js
  common/views/components/SearchResults/SearchResults.js
  common/views/components/SeriesNavigation/SeriesNavigation.js
  common/yarn.lock
  content/webapp/pages/article.js
Labels: improvement

#3417 Accessibility redirect
  router/redirects.conf
Labels: bug

#3409 Message
  cardigan/stories/components/Message.js
  common/views/components/BasePage/EventPage.js
  common/views/components/Message/Message.js
  common/views/components/Message/README.md
  content/webapp/pages/event.js
Labels: feature

#3402 add newsletter to content app
  content/webapp/pages/newsletter.js
Labels: improvement

#3396 add MIT license
  LICENSE
Labels: improvement

#3422 Standfirst
  common/data/the-pharmacy-of-colour.js
  common/model/generic-content-fields.js
  common/services/prismic/parsers.js
  common/views/components/BasePage/EventSeriesPage.js
  common/views/components/BasePage/InstallationPage.js
  common/views/components/Body/Body.js
  common/views/components/PageHeaderStandfirst/PageHeaderStandfirst.js
  content/webapp/pages/article-series.js
  content/webapp/pages/article.js
  content/webapp/pages/exhibition.js
  prismic-model/js/articles.js
  prismic-model/js/parts/body.js
  prismic-model/json/articles.json
  prismic-model/json/books.json
  prismic-model/json/event-series.json
  prismic-model/json/events.json
  prismic-model/json/exhibitions.json
  prismic-model/json/installations.json
  prismic-model/json/pages.json
  prismic-model/json/places.json
  prismic-model/json/series.json
  prismic-model/yarn.lock
Labels: improvement

#3418 add routes for site sections to content terraform
  content/terraform/terraform.tf
  content/webapp/server.js
Labels: improvement

#3412 Message on schedule
  common/views/components/EventScheduleItem/EventScheduleItem.js
  common/yarn.lock
  content/webapp/yarn.lock
Labels: improvement

#3398 add places to content app
  common/services/prismic/places.js
  content/webapp/pages/place.js
  content/webapp/server.js
Labels: improvement

#3395 move books over to content app
  common/services/prismic/books.js
  content/webapp/pages/book.js
  content/webapp/server.js
Labels: improvement

#3427 Caters for normal closed day being part of an exceptional closed period
  content/webapp/pages/opening-times.js
  server/views/pages/opening-times.njk
Labels: bug

#3426 name pages routes correctly
  content/terraform/terraform.tf
Labels: bug

#3430 Series schedule
  common/model/article-schedule-items.js
  common/model/article-series.js
  common/model/articles.js
  common/model/color-selections.js
  common/services/prismic/article-series.js
  common/services/prismic/articles.js
  common/views/components/ArticleCard/ArticleCard.js
  common/views/components/CompactCard/CompactCard.js
  common/views/components/EventCard/EventCard.js
  common/views/components/ImagePlaceholder/ImagePlaceholder.js
  common/views/components/PartNumberIndicator/PartNumberIndicator.js
  common/views/components/SearchResults/SearchResults.js
  common/views/components/SeriesNavigation/SeriesNavigation.js
  content/webapp/pages/article-series.js
  content/webapp/pages/article.js
Labels: improvement

#3436 Add issue templates to main issue template
  .github/ISSUE_TEMPLATE.md
Labels: improvement

#3440 ubiqitously apply quotes pulled, and reviewed
  common/services/prismic/parsers.js
  prismic-model/js/parts/body.js
  prismic-model/json/books.json
  prismic-model/json/event-series.json
  prismic-model/json/events.json
  prismic-model/json/exhibitions.json
  prismic-model/json/installations.json
  prismic-model/json/pages.json
  prismic-model/json/places.json
  prismic-model/json/series.json
Labels: improvement

#3437 stop using strings for tracking
  common/views/components/ImageViewer/ImageViewer.js
Labels: bug

#3435 add some semantic structure to how the article page is built
  common/views/components/BasePage/BasePage.js
  content/webapp/pages/article.js
Labels: improvement

#3450 Embeds
  common/services/prismic/parsers.js
  common/styles/content.scss
  common/views/components/Body/Body.js
  prismic-model/js/parts/article-body.js
  prismic-model/js/parts/body.js
  prismic-model/json/articles.json
  prismic-model/json/books.json
  prismic-model/json/event-series.json
  prismic-model/json/events.json
  prismic-model/json/exhibitions.json
  prismic-model/json/installations.json
  prismic-model/json/pages.json
  prismic-model/json/places.json
  prismic-model/json/series.json
  server/services/prismic-body-parser.js
Labels: improvement

#3456 add wordpress article redirects
  router/redirects.conf
Labels: improvement

#3453 add contributors to article series
  common/services/prismic/articles.js
  content/webapp/pages/article-series.js
Labels: improvement

#3451 add WobblyEdge to HeaderBackground
  common/views/components/BaseHeader/HeaderBackground.js
Labels: bug

#3466 Installations in next
  common/services/prismic/installations.js
  content/terraform/terraform.tf
  content/webapp/pages/event.js
  content/webapp/pages/installation.js
  content/webapp/server.js
Labels: improvement

#3469 don't show part # on articles that aren't in series
  content/webapp/pages/article.js
Labels: bug

#3458 Exhibitions q
  common/styles/components/_quote.scss
  common/views/components/BasePage/BasePage.js
  common/views/components/ImageGalleryV2/ImageGalleryV2.js
  common/views/components/SearchResults/SearchResults.js
  content/webapp/pages/exhibition.js
  server/package.json
  server/yarn.lock
Labels: improvement

#3474 Event past dates
  common/services/prismic/events.js
  common/views/components/BasePage/EventPage.js
Labels: bug

#3446 add DeprecatedImageList component
  common/services/prismic/parsers.js
  common/views/components/Body/Body.js
  common/views/components/DeprecatedImageList/DeprecatedImageList.js
  common/views/components/Images/Images.js
Labels: improvement

#3467 add NewsletterPromo to DefaultPageLayout
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
Labels: improvement

#3465 add some spacing below full event details
  common/views/components/EventScheduleItem/EventScheduleItem.js
  common/views/components/EventbriteButton/EventbriteButton.js
Labels: bug

#3475 only use serial label if there is a schedule on the series
  common/services/prismic/article-series.js
Labels: bug

#3477 Gif video
  common/package.json
  common/services/prismic/parsers.js
  common/styles/content.scss
  common/utils/tracking.js
  common/views/components/Body/Body.js
  common/views/components/GifVideo/GifVideo.js
  common/yarn.lock
  flow-typed/npm/lodash.throttle_vx.x.x.js
Labels: wip

#3476 only use deprecated description if there is no body on article series
  common/services/prismic/article-series.js
  prismic-model/js/series.js
  prismic-model/json/series.json
Labels: improvement

#3243 [do not merge] catalogue back to next.js
  catalogue/terraform/terraform.tf
Labels: improvement

#3492 do a combo of promo and drupalised promo for pages
  common/services/prismic/pages.js
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
Labels: bug

#3490 make catalogue service use 200 namespace for router listeners
  catalogue/terraform/terraform.tf
Labels: improvement

#3489 make sure next asset cache is stronger than HTML cache
  router/terraform/cloudfront.tf
Labels: improvement

#3486 serve all pages and exhibitions from content app
  content/terraform/terraform.tf
Labels: improvement

#3485 Webcomic series parsers
  common/model/articles.js
  common/services/prismic/article-series.js
  common/services/prismic/articles.js
  common/services/prismic/multi-content.js
  common/views/components/ImageGalleryV2/ImageGalleryV2.js
  common/views/components/SeriesNavigation/SeriesNavigation.js
  content/webapp/pages/article.js
  prismic-model/js/webcomic-series.js
  prismic-model/json/webcomic-series.json
Labels: improvement

#3500 hackfix in pagesize until we have pagination on SearchResults with compact cards
  content/webapp/pages/article-series.js
Labels: improvement

#3499 proposing an article redirect
  router/redirects.conf
Labels: improvement

#3501 add period routes to content app
  common/services/prismic/exhibitions.js
  common/views/components/CardGrid/CardGrid.js
  common/views/components/LayoutPaginatedResults/LayoutPaginatedResults.js
  common/views/components/Pagination/Pagination.js
  content/webapp/pages/exhibitions.js
  content/webapp/server.js
  whats_on/app/views/pages/exhibitions.njk
Labels: improvement

#3495 Event promo
  common/model/events.js
  common/views/components/BasePage/EventPage.js
  common/views/components/CardGrid/CardGrid.js
  common/views/components/DailyTourPromo/DailyTourPromo.js
  common/views/components/DateRange/DateRange.js
  common/views/components/EventDateRange/EventDateRange.js
  common/views/components/EventPromo/EventPromo.js
  common/views/components/EventsByMonth/EventsByMonth.js
  common/views/components/StatusIndicator/StatusIndicator.js
  common/yarn.lock
  content/webapp/pages/event.js
  whats_on/app/views/pages/events.njk
  whats_on/app/yarn.lock
Labels: improvement

#3507 deploy the smarticles
  content/terraform/terraform.tf
Labels: improvement

#3497 make sure we deserialise the serialised date from getInitialProps
  content/webapp/pages/page.js
Labels: improvement

#3514 add preview to test
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
  content/terraform/terraform.tf
  content/webapp/server.js
Labels: improvement

#3515 get the preview up and running
  common/styles/components/_prismic_toolbar.scss
  common/styles/content.scss
  content/terraform/terraform.tf
  content/webapp/package.json
  content/webapp/server.js
  content/webapp/yarn.lock
Labels: bug

#3516 reinstate scroll analytics across the next apps
  common/utils/analytics.js
Labels: bug

#3512 use correct index maths to workout whether to show part 1 in a series
  content/webapp/pages/article.js
Labels: bug

#3513 add contributor to webcomic graphQL
  common/services/prismic/articles.js
Labels: bug

#3518 use isPreview cookie and stop relying on Prismic's preview implementation
  common/package.json
  common/services/prismic/api.js
  common/services/prismic/articles.js
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
  common/yarn.lock
  content/webapp/server.js
Labels: improvement

#3524 use series order for ordering of serials
  common/services/prismic/article-series.js
Labels: bug

#3523 prevent error when parsing article
  common/services/prismic/parsers.js
Labels: bug

#3526 return
  common/utils/json-ld.js
Labels: bug

#3522 Dropping the cap
  common/package.json
  common/services/prismic/html-serialisers.js
  common/services/prismic/link-resolver.js
  common/services/prismic/parsers.js
  common/styles/utilities/_root-scope-classes.scss
  common/views/components/Body/Body.js
  common/views/components/PrismicHtmlBlock/PrismicHtmlBlock.js
  common/yarn.lock
  content/webapp/package.json
  content/webapp/server.js
  content/webapp/yarn.lock
Labels: improvement

#3528 delete troublesome prismic cookie
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
  content/webapp/server.js
Labels: bug

#3529 daily tours link fix
  common/views/components/DailyTourPromo/DailyTourPromo.js
Labels: bug

#3536 make sure drop cap serialises serialises all text
  common/services/prismic/html-serialisers.js
  router/redirects.conf
Labels: bug

#3533 add healthchecks to nextjs apps
  catalogue/terraform/terraform.tf
  catalogue/webapp/server.js
  content/terraform/terraform.tf
  content/webapp/server.js
Labels: improvement

#3521 allow no promo on exhibitions
  common/services/prismic/exhibitions.js
Labels: bug

#3503 Render scheduled in on events pages
  common/services/prismic/events.js
  content/terraform/terraform.tf
  content/webapp/pages/event.js
Labels: improvement

#3527 render breadcrumbs LD
  common/utils/json-ld.js
  common/views/components/Breadcrumb/Breadcrumb.js
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
  content/webapp/pages/article-series.js
  content/webapp/pages/article.js
  content/webapp/pages/book.js
  content/webapp/pages/event.js
  content/webapp/pages/exhibition.js
  content/webapp/pages/installation.js
  content/webapp/pages/place.js
Labels: improvement

#3532 apply drop cap to first instance of text slice in body
  common/styles/utilities/_root-scope-classes.scss
  common/views/components/Body/Body.js
Labels: bug

#3535 Move toggles readme over to repo
  toggles/README.md
Labels: improvement

#3552 add our voice our way installation
  common/data/our-voice-our-way.js
  server/controllers/content.js
  server/views/pages/homepage.njk
  whats_on/app/controllers.js
  whats_on/app/views/pages/whats-on.njk
Labels: improvement

#3548 add past to past exhibitions title
  content/webapp/pages/exhibitions.js
Labels: bug

#3547 Event series
  common/services/prismic/event-series.js
  content/webapp/pages/event-series.js
  content/webapp/server.js
Labels: bug

#3541 Update opening times before launch
  content/webapp/pages/opening-times.js
  content/webapp/server.js
Labels: improvement

#3560 add base outro component
  cardigan/stories/components/Outro.js
  cardigan/yarn.lock
  common/views/components/Outro/Outro.js
  common/views/components/Outro/README.md
Labels: feature

#3563 Outro ui actually
  cardigan/stories/components/Outro.js
  common/views/components/Outro/Outro.js
Labels: improvement

#3562 remove BaseHeader in favour of PageHeader
  cardigan/.storybook/config.js
  cardigan/stories/components/BaseHeader.js
  cardigan/stories/pages/Base.js
  common/views/components/BaseHeader/BaseHeader.js
  common/views/components/BasePage/BasePage.js
  common/views/components/BasePage/EventPage.js
  common/views/components/BasePage/EventSeriesPage.js
  common/views/components/BasePage/InstallationPage.js
  common/views/components/BasePage/Page.js
  common/views/components/BasePage/PlacePage.js
  common/views/components/HeaderBackground/HeaderBackground.js
  common/views/components/PageHeader/PageHeader.js
  content/webapp/pages/article-series.js
  content/webapp/pages/event-series.js
  content/webapp/pages/event.js
  content/webapp/pages/installation.js
  content/webapp/pages/page.js
  content/webapp/pages/place.js
Labels: bug

#3561 parse JSON event dates in event series
  content/webapp/pages/event-series.js
  content/webapp/pages/event.js
Labels: bug

#3567 use object.keys not object.entries for IE11
  common/services/prismic/search.js
Labels: bug

#3568 Outro toggle
  common/model/articles.js
  common/model/multi-content.js
  common/services/prismic/articles.js
  common/services/prismic/exhibitions.js
  common/services/prismic/multi-content.js
  common/services/prismic/types.js
  common/views/components/BasePage/BasePage.js
  common/views/components/Outro/Outro.js
  content/webapp/pages/article.js
  content/webapp/server.js
  prismic-model/js/articles.js
  prismic-model/js/parts/single-line-text.js
  prismic-model/json/articles.json
  prismic-model/json/series.json
Labels: improvement

#3569 use consistent language around links
  whats_on/app/views/partials/mixed_exhibition_event_promos.njk
  whats_on/app/views/partials/separate_exhibition_event_promos.njk
Labels: bug

#3575 redirect the outsiders serials to the new Prismic versions
  router/redirects.conf
Labels: improvement

#3571 update openseadragon
  common/package.json
  common/yarn.lock
Labels: bug

#3573 Render homepage from content app
  common/data/our-voice-our-way.js
  common/model/periods.js
  common/services/prismic/articles.js
  common/services/prismic/utils.js
  common/views/components/CardGrid/CardGrid.js
  content/webapp/pages/homepage.js
  content/webapp/server.js
Labels: improvement

#3577 Track opening of the image galleries
  common/views/components/Body/Body.js
  common/views/components/ImageGalleryV2/ImageGalleryV2.js
Labels: analytics

#3580 encode query for works
  catalogue/webapp/services/catalogue/works.js
Labels: bug

#3574 route traffic for whats_on and homepage to content app
  content/terraform/terraform.tf
Labels: improvement

#3582 add body to webcomics
  README.md
  prismic-model/js/webcomics.js
  prismic-model/json/webcomics.json
Labels: improvement

#3576 add outro properties to article graph query
  common/model/multi-content.js
  common/model/weblinks.js
  common/services/prismic/articles.js
  common/services/prismic/exhibitions.js
  common/services/prismic/types.js
  common/styles/utilities/_root-scope-classes.scss
  common/views/components/Outro/Outro.js
Labels: wip

#3587 check for widescreen image before we use it
  common/views/components/PageHeader/PageHeader.js
Labels: bug

#3595 add installations to outro types
  common/services/prismic/articles.js
Labels: bug

#3599 allow pages on outro
  common/services/prismic/articles.js
Labels: bug

#3586 add basic pa11y dashboard app
  .gitignore
  pa11y/.DS_Store
  pa11y/webapp/.DS_Store
  pa11y/webapp/babel.config.js
  pa11y/webapp/package.json
  pa11y/webapp/pages/index.js
  pa11y/webapp/write-report.js
  pa11y/webapp/yarn.lock
  package.json
Labels: accessibility, improvement

#3600 Force size on contributor org image
  common/views/components/Contributor/Contributor.js
Labels: bug

#3601 move polyfill io into default page layout
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
  common/views/pages/_document.js
Labels: bug

#3597 Booking required
  common/model/events.js
  common/services/prismic/events.js
  common/views/components/DailyTourPromo/DailyTourPromo.js
  content/webapp/pages/event.js
  prismic-model/js/event-policies.js
  prismic-model/js/events.js
  prismic-model/json/events.json
  server/content-model/events.js
  server/services/prismic-parsers.js
Labels: improvement

#3602 change outro copy to be more generic
  common/views/components/Outro/Outro.js
Labels: improvement

#3605 add pa11y to circle
  .circleci/config.yml
  pa11y/webapp/next.config.js
  pa11y/webapp/package.json
Labels: improvement

#3593 convert JSON events to typed events before render
  content/webapp/pages/events.js
Labels: bug

#3608 allow userenabled switches to be set to public via app
  catalogue/webapp/server.js
  common/services/unleash/feature-toggles.js
  content/webapp/server.js
Labels: improvement

#3589 serve articles from content app
  common/model/articles.js
  common/views/components/CardGrid/CardGrid.js
  common/views/components/LayoutPaginatedResults/LayoutPaginatedResults.js
  common/views/components/StoryPromo/StoryPromo.js
  content/webapp/pages/articles.js
  content/webapp/server.js
  server/controllers/async-controllers.js
Labels: improvement

#3591 Stories list from content app
  content/webapp/pages/articles.js
  content/webapp/pages/stories.js
Labels: improvement

#3611 add ab strategy to unleash
  common/services/unleash/feature-toggles.js
  content/webapp/server.js
Labels: improvement

#3594 route all events to content app
  content/terraform/terraform.tf
Labels: improvement

#3614 Re-add first sentence to story page description
  content/webapp/pages/stories.js
Labels: bug

#3618 Re-add underline under what's on for exhibitions
  content/webapp/pages/exhibition.js
Labels: bug

#3623 Show article series on outros
  common/model/article-series.js
  common/model/multi-content.js
  common/services/prismic/article-series.js
  common/services/prismic/multi-content.js
  common/views/components/SeriesNavigation/SeriesNavigation.js
Labels: bug

#3592 add /stories and /articles listeners to content app
  content/terraform/terraform.tf
Labels: improvement

#3613 get global alert on server
  common/koa-middleware/withGlobalAlert.js
  common/services/prismic/opening-times.js
  content/webapp/server.js
Labels: accessibility, improvement

#3635 get priorities straight for content listeners
  content/terraform/terraform.tf
Labels: bug

#3638 Add infra for ab_testing lambda@edge
  build/nginx.conf
  nginx-proxy/nginx.conf
  nginx_webapp/nginx.conf
  router/terraform/ab_testing.tf
  router/terraform/cloudfront.tf
  router/terraform/terraform.tf
  router/webapp/ab_testing.js
  router/webapp/test_event_request.json
  router/webapp/test_event_response.json
Labels: improvement

#3647 parse date range as date on events from getInitialProps
  content/webapp/pages/event.js
Labels: bug

#3640 add simpler toggles
  common/koa-middleware/withToggles.js
  content/webapp/server.js
Labels: improvement

#3644 remove routes from server app
  server/package.json
  server/routes/index.js
  server/test/_structured-data-testing-tool.js
  server/test/app/app.js
  server/test/mocks/dom-nodes.js
  server/test/mocks/explore-api.json
  server/test/mocks/wellcomecollection-api.json
  server/test/mocks/wp-api.json
  server/test/query-object.js
  server/test/util/body-parser.js
Labels: improvement

#3643 remove whats_on app from code
  .circleci/config.yml
  build/whats_on_webapp.yml
  deploy/deploy_service.js
  greenkeeper.json
  whats_on/app/.babelrc
  whats_on/app/app.js
  whats_on/app/controllers.js
  whats_on/app/jest.config.js
  whats_on/app/package.json
  whats_on/app/routes.js
  whats_on/app/setup-app.js
  whats_on/app/test/app.test.js
  whats_on/app/utils.js
  whats_on/app/views/components/exhibits/exhibits.njk
  whats_on/app/views/components/whats-on-list-header/whats-on-list-header.njk
  whats_on/app/views/pages/event-series.njk
  whats_on/app/views/pages/event.njk
  whats_on/app/views/pages/events.njk
  whats_on/app/views/pages/exhibition.njk
  whats_on/app/views/pages/exhibitions.njk
  whats_on/app/views/pages/installation.njk
  whats_on/app/views/pages/whats-on.njk
  whats_on/app/views/partials/date_range.njk
  whats_on/app/views/partials/mixed_exhibition_event_promos.njk
  whats_on/app/views/partials/separate_exhibition_event_promos.njk
  whats_on/app/webpack.config.js
  whats_on/app/yarn.lock
Labels: improvement

#3649 add stories route to server to get globalAlert
  common/koa-middleware/withToggles.js
  content/webapp/server.js
Labels: bug

#3579 Use message for fully booked
  common/views/components/BasePage/EventPage.js
  common/views/components/EventBookingButton/EventBookingButton.js
  content/webapp/pages/event.js
Labels: improvement

#3655 send pageState down the pipes
  common/utils/analytics.js
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
Labels: bug

#3656 retrieve global alert
  common/views/components/PageWrapper/PageWrapper.js
Labels: bug

#3660 dont report on empty page state
  common/utils/analytics.js
Labels: bug
