Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2018-05, with the labels that each got.

#2563 add tag list pages
  common/services/prismic/multi-content.js
  server/controllers/content.js
  server/routes/index.js
Labels: feature

#2566 add drupal export data to exhibitions
  prismic-model/js/exhibitions.js
  prismic-model/json/exhibitions.json
Labels: feature

#2567 Style eventbrite button correctly
  eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
Labels: bug

#2569 Remove unnecessary styles
  common/styles/components/_back-to-top.scss
Labels: bug

#2568 add drupal migration info to exhibitions
  common/services/prismic/exhibitions.js
Labels: feature

#2571 Press releases
  common/services/prismic/multi-content.js
  common/services/prismic/types.js
  server/controllers/content.js
  server/routes/index.js
Labels: feature

#2570 add date published to basic pages for press releases
  prismic-model/js/info-pages.js
  prismic-model/json/info-pages.json
Labels: feature

#2574 add webcomic series tag to body squabbles
  server/controllers/content.js
  server/views/pages/article.njk
Labels: test

#2576 only look for article tags if we have an article
  server/controllers/content.js
Labels: bug

#2577 make accessability link secondary
  whats_on/app/views/pages/exhibition.njk
Labels: bug

#2573 add backfillQuery and requiredCount to content list
  common/services/prismic/parsers.js
  common/views/components/ContentList/ContentList.js
  prismic-model/js/parts/body.js
  prismic-model/json/info-pages.json
  server/controllers/async-controllers.js
Labels: feature

#2580 plainify content list promos
  common/views/components/BasicBody/BasicBody.js
  common/views/components/BasicPromo/BasicPromo.js
  common/views/components/ContentList/ContentList.js
  common/views/components/ContentList/ContentListItems.js
Labels: feature

#2581 add support for promos without images
  common/services/prismic/parsers.js
  common/views/components/BasicPromo/BasicPromo.js
Labels: health

#2583 a few fixes to installations
  common/model/installations.js
  common/services/prismic/installations.js
  common/services/prismic/parsers.js
  prismic-model/js/installations.js
  prismic-model/js/parts/captioned-image-gallery-slice.js
  prismic-model/json/installations.json
  whats_on/app/views/pages/installation.njk
Labels: bug

#2588 check if exhibit link is broken
  common/services/prismic/exhibitions.js
Labels: bug

#2584 convert all models if model not given
  prismic-model/convert.js
  prismic-model/json/collection-venues.json
  prismic-model/json/info-pages.json
Labels: techprofit

#2589 add books model
  prismic-model/js/books.js
  prismic-model/js/info-pages.js
  prismic-model/json/books.json
  prismic-model/json/info-pages.json
Labels: feature

#2590 refactor info-pages to pages
  common/model/multi-content.js
  common/model/pages.js
  common/services/prismic/fetch-links.js
  common/services/prismic/multi-content.js
  common/services/prismic/pages.js
  common/services/prismic/parsers.js
  common/views/components/ContentList/ContentListItems.js
  prismic-model/js/pages.js
  prismic-model/js/parts/body.js
  prismic-model/js/parts/uid.js
  prismic-model/json/installations.json
  prismic-model/json/pages.json
  router/nginx.conf
  server/controllers/content.js
  server/routes/index.js
  server/services/prismic-parsers.js
Labels: health, techprofit

#2592 put the installation into the basic page template
  common/styles/utilities/_root-scope-classes.scss
  common/views/components/DateRange/DateRange.js
  common/views/components/HTMLDate/HTMLDate.js
  common/views/components/Index/index.js
  common/views/components/PageHeaders/BasicHeader/BasicHeader.js
  common/views/components/PageHeaders/FramedHeader/FramedHeader.js
  common/views/components/StatusIndicator/StatusIndicator.js
  common/views/components/Templates/BasicPage/BasicPage.js
  common/views/components/Templates/BasicPage/InstallationPage.js
  common/views/components/Templates/README.md
  whats_on/app/views/pages/installation.njk
Labels: feature

#2586 Decouple dynamic and manual content lists
  .eslintrc.json
  common/package.json
  common/services/prismic/multi-content.js
  common/services/prismic/parsers.js
  common/services/prismic/search.js
  common/test/services/prismic/search.test.js
  common/views/components/BasicBody/BasicBody.js
  common/views/components/ContentList/ContentList.js
  common/views/components/Index/index.js
  common/views/components/SearchResults/AsyncSearchResults.js
  common/views/components/SearchResults/SearchResults.js
  common/yarn.lock
  flow-typed/npm/search-query-parser_vx.x.x.js
  package.json
  prismic-model/js/parts/body.js
  prismic-model/json/pages.json
  server/controllers/async-controllers.js
  server/package.json
  server/routes/index.js
  server/yarn.lock
  yarn.lock
Labels: feature

#2593 support wordpress quotes
  common/views/components/Quote/Quote.js
Labels: bug

#2594 use tag URL to not pollute the existing URL on v1
  server/routes/index.js
Labels: health

#2595 put tags behind a beta tab
  prismic-model/js/pages.js
  prismic-model/json/books.json
  prismic-model/json/pages.json
Labels: health

#2598 remove checklist from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: health

#2596 use isDocumentLink over isEmptyObject
  common/services/prismic/parsers.js
Labels: bug

#2597 add contributors to installation page"
  common/model/contributors.js
  common/services/prismic/parsers.js
  common/views/components/Contributor/Contributor.js
  common/views/components/Templates/BasicPage/BasicPage.js
  common/views/components/Templates/BasicPage/InstallationPage.js
Labels: feature

#2607 make basic page background a passable component
  common/views/components/Templates/BasicPage/BasicPage.js
  common/views/components/Templates/BasicPage/InstallationPage.js
  common/views/components/Templates/BasicPage/WobblyBackground.js
Labels: health

#2608 remove promo images from pages body
  common/services/prismic/pages.js
Labels: health

#2610 fix the exhibits list on exhibition pages
  common/services/prismic/installations.js
  common/views/components/InstallationPromo/InstallationPromo.js
  whats_on/app/views/components/exhibits/exhibits.njk
Labels: bug

#2606 add basic body quote
  common/model/exhibitions.js
  common/services/prismic/exhibitions.js
  common/services/prismic/parsers.js
  common/styles/utilities/_root-scope-classes.scss
  common/views/components/BasicBody/BasicBody.js
  common/views/components/Body/Body.config.json
  common/views/components/Body/Standfirst/Standfirst.config.js
  common/views/components/Body/Standfirst/Standfirst.js
  common/views/components/FeaturedText/FeaturedText.js
  common/views/components/Index/index.js
  common/views/components/Quote/Quote.config.js
  common/views/components/Quote/Quote.js
  common/views/components/ShameQuote/ShameQuote.config.js
  common/views/components/ShameQuote/ShameQuote.js
  common/views/components/Templates/BasicPage/BasicPage.js
  prismic-model/js/parts/body.js
  prismic-model/json/books.json
  prismic-model/json/installations.json
  prismic-model/json/pages.json
  server/services/prismic-body-parser.js
  server/views/components/article-body/article-body.njk
  whats_on/app/views/pages/exhibition.njk
Labels: feature

#2611 Add tags and part of to installations
  common/services/prismic/exhibitions.js
  common/views/components/PageHeaders/BasicHeader/BasicHeader.js
  common/views/components/Tags/Tags.js
  common/views/components/Templates/BasicPage/BasicPage.js
  common/views/components/Templates/BasicPage/InstallationPage.js
  server/controllers/async-controllers.js
  whats_on/app/controllers.js
  whats_on/app/routes.js
Labels: health

#2613 parse WP standfirst in prismic style
  server/utils/body-parser.js
  server/views/components/article-body/article-body.njk
Labels: bug

#2615 use normal tags for installations
  common/styles/utilities/_root-scope-classes.scss
  common/views/components/PageHeaders/BasicHeader/BasicHeader.js
  common/views/components/Templates/BasicPage/BasicPage.js
  common/views/components/Templates/BasicPage/InstallationPage.js
  router/terraform/cloudfront.tf
  whats_on/app/controllers.js
Labels: health

#2616 remove exhibitsOnExhibitions flag
  whats_on/app/views/pages/exhibition.njk
Labels: health

#2618 add nkobs to story book
  build_and_deploy_cardigan.sh
  cardigan_beta/.storybook/addons.js
  cardigan_beta/package.json
  cardigan_beta/stories/index.js
  cardigan_beta/yarn.lock
Labels: feature

#2612 use basigcpage for pages
  common/model/pages.js
  common/services/prismic/pages.js
  common/views/components/Index/index.js
  common/views/components/Templates/BasicPage/BasicPage.js
  common/views/components/Templates/BasicPage/Page.js
  server/controllers/content.js
  server/model/basic-page.js
  server/services/prismic-parsers.js
  server/services/prismic.js
  server/views/pages/page.njk
Labels: health

#2620 Only show TASL if at least one necessary piece of info present
  common/views/components/Tasl/Tasl.js
Labels: bug

#2622 use react babel plugin
  cardigan_beta/.storybook/.babelrc
  cardigan_beta/.storybook/webpack.config.js
  cardigan_beta/package.json
  yarn.lock
Labels: bug

#2625 first pass of basic inline links
  common/views/components/BasicBody/BasicBody.js
  common/views/components/BasicPromo/BasicPromo.js
  common/views/components/Image/Image.js
  common/views/components/SearchResults/SearchResults.js
Labels: feature

#2627 Event series in multi content
  common/model/event-series.js
  common/model/events.js
  common/model/multi-content.js
  common/services/prismic/events.js
  common/services/prismic/fetch-links.js
  common/services/prismic/multi-content.js
  common/services/prismic/pages.js
  common/services/prismic/parsers.js
  common/views/components/SearchResults/SearchResults.js
  events/app/controllers.js
Labels: feature

#2628 fix url used for event series on search results
  common/views/components/SearchResults/SearchResults.js
Labels: bug

#2630 allow imageless BasicPromos
  common/views/components/BasicPromo/BasicPromo.js
Labels: bug

#2631 Page template headers
  common/views/components/PageHeaders/BasicHeader/BasicHeader.js
  common/views/components/Templates/BasicPage/BasicPage.js
  common/views/components/Templates/BasicPage/Page.js
  common/views/components/Templates/BasicPage/TexturedBackground.js
  prismic-model/json/installations.json
Labels: feature

#2636 prepping works for prime time
  catalogue/terraform/terraform.tf
  catalogue/webapp/next.config.js
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  catalogue/webapp/server.js
  catalogue/webapp/yarn.lock
  common/styles/works.scss
  router/terraform/services.tf
Labels: feature

#2641 add root press redirect
  server/routes/index.js
Labels: feature

#2640 Redirect from drupal path
  common/services/prismic/pages.js
  router/nginx.conf
  server/controllers/content.js
  server/routes/index.js
Labels: feature

#2639 add nextjs listeners to the catalogue app
  catalogue/terraform/terraform.tf
Labels: feature

#2642 put pagination on the bottom of works
  catalogue/webapp/pages/works.js
  common/views/components/Pagination/Pagination.js
Labels: bug

#2646 add padding to basic page title
  common/views/components/PageHeaders/BasicHeader/BasicHeader.js
Labels: bug

#2629 Links in story book
  cardigan_beta/.storybook/addons.js
  cardigan_beta/.storybook/config.js
  cardigan_beta/package.json
  cardigan_beta/stories/Links.js
  cardigan_beta/stories/index.js
  cardigan_beta/yarn.lock
Labels: feature

#2658 make sure we specify a v1 route
  router/nginx.conf
Labels: bug

#2657 add VideoEmbed parser
  cardigan_beta/.storybook/config.js
  cardigan_beta/stories/BasicBody.js
  cardigan_beta/stories/PageHeaders.js
  cardigan_beta/stories/content.js
  cardigan_beta/stories/utils.js
  common/services/prismic/parsers.js
  common/views/components/BasicBody/BasicBody.js
  common/views/components/Templates/BasicPage/Page.js
  prismic-model/js/parts/body.js
  prismic-model/js/parts/embed.js
  prismic-model/json/books.json
  prismic-model/json/installations.json
  prismic-model/json/pages.json
Labels: feature

#2656 Search results ordering
  common/services/prismic/multi-content.js
  common/views/components/Templates/BasicPage/BasicPage.js
  common/views/components/Templates/BasicPage/InstallationPage.js
  common/views/components/Templates/BasicPage/Page.js
Labels: feature

#2663 pagination regression fix
  common/views/components/Pagination/Pagination.js
Labels: accessibility

#2665 add basic root routes
  server/routes/index.js
Labels: feature

#2664 add dynamic orderings to search results
  common/services/prismic/multi-content.js
  common/services/prismic/search.js
  common/views/components/BasicBody/BasicBody.js
  common/views/components/SearchResults/AsyncSearchResults.js
  prismic-model/js/parts/body.js
Labels: bug

#2655 Fix tags spacing for BasicHeader
  cardigan_beta/.storybook/config.js
  cardigan_beta/stories/PageHeaders.js
  cardigan_beta/stories/index.js
  common/views/components/PageHeaders/BasicHeader/BasicHeader.js
Labels: bug

#2666 loosely type site section
  common/model/pages.js
  common/services/prismic/pages.js
  server/controllers/content.js
  server/views/layout/default.njk
Labels: health

#2644 books. barely.
  common/model/books.js
  common/services/prismic/books.js
  common/views/components/Index/index.js
  common/views/components/Templates/BasicPage/BookPage.js
  server/controllers/content.js
  server/routes/index.js
  server/services/prismic-parsers.js
  server/views/pages/book.njk
Labels: feature

#2671 add basic metadata to books
  common/model/books.js
  common/services/prismic/books.js
  common/views/components/Templates/BasicPage/BookPage.js
  server/controllers/content.js
  server/views/pages/book.njk
Labels: feature

#2670 Use /newsletter instead of /pages/newsletter
  common/views/components/NewsletterPromo/NewsletterPromo.js
  common/views/components/NewsletterSignup/NewsletterSignup.js
  router/nginx.conf
Labels: bug

#2668 redirect pages that had visit-us or what-we-do in the URL
  router/nginx.conf
Labels: feature

#2667 use promo text as description universally
  events/app/views/pages/event.njk
  server/views/pages/page.njk
  whats_on/app/views/pages/exhibition.njk
  whats_on/app/views/pages/installation.njk
Labels: health

#2675 Whats on hotfix
  server/services/prismic-parsers.js
Labels: bug

#2682 check for linked content data before parsing it
  common/services/prismic/parsers.js
Labels: bug

#2686 remove whats_on tests from circle
  .circleci/config.yml
Labels: bug

#2684 Do the divider nth-child dance at the correct breakpoint
  common/styles/grids/_grid_dividers.scss
Labels: bug

#2687 add validator bar instead of showing nonsense contet to live userse
  common/services/prismic/exhibitions.js
  common/views/components/ExhibitionPromo/ExhibitionPromo.js
  server/views/layout/default.njk
  whats_on/app/views/pages/exhibition.njk
Labels: health

#2672 make opening times a combo of a page and opening hours
  common/model/pages.js
  common/services/prismic/api.js
  common/services/prismic/exhibitions.js
  common/services/prismic/opening-times.js
  common/services/prismic/pages.js
  common/views/components/OpeningHours/OpeningHours.js
  prismic-model/js/pages.js
  router/nginx.conf
  server/controllers/content.js
  server/routes/index.js
  server/views/pages/opening-times.njk
  server/views/pages/page.njk
  whats_on/app/views/components/whats-on-list-header/whats-on-list-header.njk
Labels: feature

#2688 Base
  cardigan_beta/.storybook/config.js
  cardigan_beta/stories/Base.js
  cardigan_beta/stories/Body.js
  common/views/components/BaseHeader/BaseHeader.js
  common/views/components/BaseHeader/TexturedBackground.js
  common/views/components/BaseHeader/WobblyBackground.js
  common/views/components/BasePage/BasePage.js
  common/views/components/BasePage/BookPage.js
  common/views/components/BasePage/InstallationPage.js
  common/views/components/BasePage/Page.js
  common/views/components/BasePromo/BasePromo.js
  common/views/components/Body/Body.js
  common/views/components/Index/index.js
Labels: health

#2708 add book list with 16:9 promos
  common/model/books.js
  common/model/multi-content.js
  common/services/prismic/books.js
  common/services/prismic/fetch-links.js
  common/services/prismic/multi-content.js
  common/views/components/SearchResults/SearchResults.js
  server/controllers/content.js
  server/routes/index.js
Labels: feature

#2705 update cafe link and remove friday late link from opening times
  server/views/pages/opening-times.njk
Labels: health

#2693 Books featured image
  common/model/books.js
  common/services/prismic/books.js
  common/services/prismic/parsers.js
  common/styles/base/_responsive-defaults.scss
  common/styles/utilities/_root-scope-classes.scss
  common/views/components/BaseHeader/BaseHeader.js
  common/views/components/BasePage/BasePage.js
  common/views/components/BasePage/BookPage.js
  common/views/components/Body/Body.js
  common/views/components/Images/Images.js
  server/views/pages/book.njk
Labels: feature

#2643 nextjs pagination on works
  common/views/components/Buttons/Control/Control.js
  common/views/components/Pagination/Pagination.js
  common/views/components/Tags/Tags.js
Labels: bug

#2710 nicer textured background ratio
  common/views/components/BaseHeader/TexturedBackground.js
Labels: health

#2712 add heading3 to body text
  prismic-model/js/parts/body.js
  prismic-model/json/articles.json
  prismic-model/json/books.json
  prismic-model/json/installations.json
  prismic-model/json/pages.json
Labels: feature

#2706 route root domains to V2
  router/nginx.conf
Labels: feature

#2716 use width on responsive images
  common/styles/base/_responsive-defaults.scss
Labels: bug

#2661 push all /press through to v2
  router/nginx.conf
Labels: feature

#2714 add padding where padding once was (frame header)
  events/app/views/pages/event-series.njk
  events/app/views/partials/event_with_schedule.njk
Labels: bug

#2694 Books contributors
  common/model/contributors.js
  common/model/people.js
  common/services/prismic/books.js
  common/views/components/BasePage/BookPage.js
  common/views/components/BasePage/InstallationPage.js
  common/views/components/Contributors/Contributors.js
Labels: feature

#2707 route homepage through to V2
  router/nginx.conf
Labels: feature

#2719 remove old drupal links
  common/model/events.js
  server/content-model/events.js
  server/data/facility-promos.js
  server/data/works.js
  server/views/pages/opening-times.njk
  whats_on/app/views/pages/exhibition.njk
Labels: health

#2722 add a bit of padding to whats_on
  whats_on/app/views/components/whats-on-list-header/whats-on-list-header.njk
  whats_on/app/views/pages/whats-on.njk
Labels: health

#2723 add books to root routes
  common/views/components/BasePage/BookPage.js
  router/nginx.conf
Labels: health

#2725 route visit us and what we do properly
  router/nginx.conf
Labels: bug

#2731 don't route /exhibitions/* to V2
  router/nginx.conf
Labels: bug

#2737 order books by pubished date
  server/controllers/content.js
Labels: health

#2738 Ignore 'blocked a frame' error in sentry
  server/views/partials/monitoring.njk
Labels: health

#2739 add books to what we do section
  server/controllers/content.js
Labels: health

#2727 use micro-proxy for devappy
  devappy/Dockerfile
  devappy/README.md
  devappy/docker-compose.yml
  devappy/nginx.conf
  devappy/package.json
  devappy/rules.json
  devappy/yarn.lock
  yarn.lock
Labels: techprofit

#2745 usse JSON.stringify for tracking on image viewer controls
  common/views/components/ImageViewer/ImageViewer.js
Labels: bug

#2747 raven upgrade
  server/package.json
  server/views/partials/monitoring.njk
  server/yarn.lock
Labels: techprofit

#2741 add link property to promo
  common/model/image-promo.js
  common/services/prismic/parsers.js
  common/views/components/BasicPromo/BasicPromo.js
  common/views/components/SearchResults/SearchResults.js
  prismic-model/js/parts/image.js
  prismic-model/js/parts/promo.js
  prismic-model/json/books.json
  prismic-model/json/exhibitions.json
  prismic-model/json/installations.json
  prismic-model/json/pages.json
Labels: feature

#2743 Image consolidation
  common/model/captioned-image.js
  common/model/tasl.js
  common/services/prismic/exhibitions.js
  common/services/prismic/parsers.js
  common/utils/prismic.js
  common/views/components/ImageGallery/ImageGallery.js
  common/views/components/Images/Images.js
  common/views/components/Index/index.js
  common/views/components/StaticWorksContent/StaticWorksContent.js
  common/views/components/Tasl/Tasl.js
  server/data/works.js
  server/views/pages/search.njk
Labels: health

#2752 use the right image sizes on exhibitions pages
  whats_on/app/views/pages/exhibition.njk
Labels: bug

#2744 Image isolation article body
  common/services/prismic/parsers.js
  common/views/components/BasePage/Page.js
  common/views/components/Body/Body.js
  server/services/prismic-body-parser.js
  server/test/util/body-parser.js
  server/utils/body-parser.js
  server/views/components/article-body/article-body.njk
Labels: health

#2754 put events model into JS
  prismic-model/js/events.js
  prismic-model/js/installations.js
  prismic-model/js/parts/boolean.js
  prismic-model/json/events.json
Labels: techprofit

#2751 add Body to storybook
  cardigan_beta/.storybook/addons.js
  cardigan_beta/.storybook/config.js
  cardigan_beta/.storybook/preview-head.html
  cardigan_beta/package.json
  cardigan_beta/stories/components/BaseHeader.js
  cardigan_beta/stories/components/Body.js
  cardigan_beta/stories/components/Links.js
  cardigan_beta/stories/content.js
  cardigan_beta/yarn.lock
  common/views/components/Body/Body.js
Labels: feature

#2755 Use the new UiImage on event
  common/views/components/Index/index.js
  events/app/views/partials/event_with_schedule.njk
  events/app/views/partials/event_without_schedule.njk
Labels: techprofit

#2757 add excerpt
  common/views/components/Excerpt/Excerpt.js
  common/views/components/Index/index.js
  server/services/prismic-body-parser.js
  server/views/components/article-body/article-body.njk
Labels: bug

#2756 parse quote footer correctly
  server/services/prismic-body-parser.js
Labels: bug

#2758 check for caption before stripping it's tags
  server/utils/body-parser.js
Labels: bug
