Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2018-08, with the labels that each got.

#3100 Allow Prismic preview on the event-series page
  events/app/controllers.js
  server/services/prismic-parsers.js
Labels: bug

#3050 Remove description from event series
  common/model/event-series.js
  common/services/prismic/event-series.js
  prismic-model/js/event-series.js
  prismic-model/json/event-series.json
Labels: health

#3075 Send WI urls containing newline character straight to /works
  router/nginx.conf
Labels: bug

#3103 simplify error handling
  common/services/prismic/event-series.js
  common/services/prismic/events.js
  server/middleware/error.js
  server/setup-app.js
  whats_on/app/controllers.js
Labels: bug

#3104 serve event series from whats_on service
  events/terraform/services.tf
  whats_on/terraform/services.tf
Labels: feature

#3102 Work results as list
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  catalogue/webapp/services/catalogue/works.js
  catalogue/webapp/test/WorkPage.test.js
  catalogue/webapp/test/WorksPage.test.js
  catalogue/webapp/utils/remap-v2-to-v1.js
Labels: feature

#3106 use promoImage and promoText over a seperate promo property
  common/model/generic-content-fields.js
  common/services/prismic/parsers.js
  common/views/components/BasePage/EventSeriesPage.js
  common/views/components/BasePage/InstallationPage.js
  server/views/layout/default.njk
  whats_on/app/views/pages/event-series.njk
  whats_on/app/views/pages/installation.njk
Labels: bug

#3107 add fully booked info to events without eventbrite IDs
  eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
  events/app/views/partials/event_without_schedule.njk
Labels: bug

#3109 use page link for shop promo
  server/data/facility-promos.js
Labels: bug

#3110 use alb priority properly and add https listners to whats_on service
  events/terraform/services.tf
  whats_on/terraform/services.tf
Labels: bug

#3118 remove featured image list
  prismic-model/json/articles.json
  server/views/pages/article.njk
Labels: health

#3117 remove njk image component from exhibition
  whats_on/app/views/pages/exhibition.njk
Labels: health

#3116 make facility promo jsxy
  common/views/components/FacilityPromo/FacilityPromo.js
  common/views/components/Index/index.js
  server/views/components/facility-promo/facility-promo.njk
  whats_on/app/views/pages/whats-on.njk
Labels: health

#3114 clean up switches
  server/views/layout/default.njk
  server/views/pages/newsletter.njk
Labels: health

#3112 add event series tag
  common/views/components/BasePage/EventSeriesPage.js
Labels: health

#3119 remove njk image component from ifram component
  server/views/components/iframe/iframe.njk
Labels: health

#3122 add items and production to work
  catalogue/webapp/pages/work.js
Labels: improvement

#3121 remove image.njk
  server/views/components/image/image.config.js
  server/views/components/image/image.njk
Labels: health

#3126 fix preview links
  common/services/prismic/api.js
  server/middleware/error.js
Labels: bug

#3127 match on right request object property
  common/services/prismic/api.js
Labels: bug

#3128 update link resolver
  common/services/prismic/parsers.js
Labels: bug

#3132 put available links in content list model
  prismic-model/js/pages.js
  prismic-model/js/parts/body.js
  prismic-model/json/books.json
  prismic-model/json/event-series.json
  prismic-model/json/installations.json
  prismic-model/json/pages.json
  prismic-model/json/places.json
Labels: health

#3133 tidy infra package.json
  infra/package.json
  infra/packer/node6.json
  infra/yarn.lock
Labels: health

#3135 fix a few works page bugs
  catalogue/webapp/pages/work.js
  common/services/prismic/api.js
Labels: bug

#3140 add body to events
  common/services/prismic/events.js
  prismic-model/js/events.js
  prismic-model/json/events.json
Labels: health

#3148 use storybook as default cardigan
  .circleci/config.yml
  build_and_deploy_cardigan.sh
  cardigan/.babelrc
  cardigan/.gitignore
  cardigan/.storybook/.babelrc
  cardigan/.storybook/addons.js
  cardigan/.storybook/config.js
  cardigan/.storybook/manager-head.html
  cardigan/.storybook/preview-head.html
  cardigan/.storybook/webpack.config.js
  cardigan/build-cardigan.js
  cardigan/cardigan-theme/assets/favicon.ico
  cardigan/cardigan-theme/assets/images/cardigan.jpg
  cardigan/cardigan-theme/assets/images/cardigan.svg
  cardigan/cardigan-theme/assets/images/temp/books.jpg
  cardigan/cardigan-theme/assets/images/temp/gallery.jpg
  cardigan/cardigan-theme/assets/images/temp/objects.jpg
  cardigan/cardigan-theme/assets/images/temp/reviews.jpg
  cardigan/cardigan-theme/assets/images/wellcome_collection_black.svg
  cardigan/cardigan-theme/partials/browser/panel-notes.nunj
  cardigan/cardigan-theme/partials/head.nunj
  cardigan/cardigan-theme/partials/header.nunj
  cardigan/config/statuses.js
  cardigan/docs/BodyBlock.config.js
  cardigan/docs/BodyBlock.jsx
  cardigan/docs/index.config.js
  cardigan/docs/index.jsx
  cardigan/docs/principles.config.js
  cardigan/docs/principles.jsx
  cardigan/docs/promos.config.js
  cardigan/docs/promos.jsx
  cardigan/docs/visual-architecture.config.js
  cardigan/docs/visual-architecture.jsx
  cardigan/fractal.js
  cardigan/package.json
  cardigan/stories/components/BaseHeader.js
  cardigan/stories/components/Body.js
  cardigan/stories/components/Contributors.js
  cardigan/stories/components/Label.js
  cardigan/stories/components/LabelsList.js
  cardigan/stories/components/LinkLabels.js
  cardigan/stories/components/Links.js
  cardigan/stories/components/Promos.js
  cardigan/stories/components/SectionHeader.js
  cardigan/stories/content.js
  cardigan/stories/docs/index.js
  cardigan/stories/global/icons/README.md
  cardigan/stories/global/icons/icons.js
  cardigan/stories/global/palette/README.md
  cardigan/stories/global/palette/palette.js
  cardigan/stories/global/typography/README.md
  cardigan/stories/global/typography/typography.js
  cardigan/stories/pages/Base.js
  cardigan/stories/wip/BookPromo.js
  cardigan/terraform/terraform.tf
  cardigan/yarn.lock
  cardigan_beta/package.json
  cardigan_beta/yarn.lock
Labels: bug

#3146 include fields that are lists in catalogue app
  catalogue/webapp/services/catalogue/works.js
Labels: health

#3144 render events page from whats_on service
  common/services/prismic/event-series.js
  common/services/prismic/events.js
  common/views/components/EventPromo/EventPromo.js
  server/middleware/error.js
  whats_on/app/controllers.js
  whats_on/app/routes.js
  whats_on/app/views/pages/events.njk
Labels: health

#3145 remove event series from events service
  events/app/controllers.js
  events/app/routes.js
Labels: health

#3142 add eventbrite widget to the bottom of the eventpage
  common/views/components/BasePage/EventPage.js
  devappy/rules.json
  eventbrite/app/controllers.js
  eventbrite/app/routes.js
Labels: improvement

#3149 remove events list from events service
  events/app/controllers.js
  events/app/routes.js
  events/app/views/pages/event-series.njk
  events/app/views/pages/events.njk
  events/terraform/services.tf
  whats_on/terraform/services.tf
Labels: health

#3151 💀 events service
  .circleci/config.yml
  app_cluster/terraform/asg.tf
  build/events_webapp.yml
  events/app/.babelrc
  events/app/Dockerfile
  events/app/app.js
  events/app/controllers.js
  events/app/package.json
  events/app/routes.js
  events/app/setup-app.js
  events/app/test/app.test.js
  events/app/views/pages/event.njk
  events/app/views/partials/event_with_schedule.njk
  events/app/views/partials/event_without_schedule.njk
  events/app/webpack.config.js
  events/app/yarn.lock
  events/terraform/iam.tf
  events/terraform/locals.tf
  events/terraform/services.tf
  events/terraform/terraform.tf
  events/terraform/topics.tf
  events/terraform/variables.tf
Labels: health

#3154 route events preview correctly and check for promo correctly
  common/views/components/BasePage/EventPage.js
  server/controllers/content.js
  server/middleware/error.js
Labels: bug

#3157 remove events from deploy script
  deploy/deploy_service.js
Labels: health

#3159 make sure we get data through from prismic before we try parse it as …
  common/services/prismic/parsers.js
Labels: bug

#3158 Scroll on internal link
  catalogue/webapp/components/WorkMedia/WorkMedia.js
  catalogue/webapp/pages/work.js
  common/utils/ga.js
  common/views/components/BasePage/EventPage.js
  common/views/components/Buttons/Button/Button.js
  common/views/components/Buttons/Control/Control.js
  common/views/components/ImageViewer/ImageViewer.js
  common/views/components/Links/PrimaryLink/PrimaryLink.js
  common/views/components/Links/SecondaryLink/SecondaryLink.js
  common/views/components/PageHeaders/Hero/Hero.js
  common/views/components/WorkMedia/WorkMedia.js
  common/views/components/WorkMedia/WorkMedia2.js
  server/views/pages/search.njk
  server/views/pages/work.njk
Labels: improvement

#3160 Use square image for default contributor fallback
  common/services/prismic/parsers.js
Labels: bug

#3171 only return series if there is a series
  common/services/prismic/event-series.js
Labels: bug

#3172 fetch links on books
  common/services/prismic/books.js
Labels: bug

#3137 Card organisation
  cardigan_beta/stories/components/Cards.js
  common/model/weight.js
  common/views/components/Card/Card.js
  common/views/components/Card/README.md
  common/views/components/CompactCard/CompactCard.js
  common/views/components/CompactCard/README.md
  common/views/components/EventCard/EventCard.js
  common/views/components/FeaturedCard/FeaturedCard.js
  common/views/components/FeaturedCard/README.md
  common/views/components/Promo/Promo.config.js
  common/views/components/Promo/Promo.js
  common/views/components/SearchResults/SearchResults.js
  server/controllers/content.js
  server/model/weight.js
  server/views/pages/curated-lists.njk
Labels: feature

#3162 add body to exhibition to be able to remap description onto it
  common/model/exhibitions.js
  common/services/prismic/exhibitions.js
  prismic-model/js/exhibitions.js
  prismic-model/json/events.json
  prismic-model/json/exhibitions.json
  whats_on/app/views/pages/exhibition.njk
Labels: health

#3170 add greenkeeper monorepo config
  dash/pa11y_dashboard/Dockerfile
  dash/pa11y_dashboard/Makefile
  dash/pa11y_dashboard/README.md
  dash/pa11y_dashboard/docker-compose.yml
  dash/pa11y_dashboard/docker-entrypoint.sh
  dash/pa11y_dashboard/terraform/iam.tf
  dash/pa11y_dashboard/terraform/locals.tf
  dash/pa11y_dashboard/terraform/services.tf
  dash/pa11y_dashboard/terraform/task_definition.json.template
  dash/pa11y_dashboard/terraform/terraform.tf
  dash/pa11y_dashboard/terraform/topics.tf
  dash/terraform/ami.tf
  dash/terraform/asg.tf
  dash/terraform/ecs.tf
  dash/terraform/iam.tf
  dash/terraform/locals.tf
  dash/terraform/terraform.tf
  dash/terraform/topics.tf
  dash/terraform/userdata.tf
  dash/terraform/variables.tf
  greenkeeper.json
Labels: feature

#3167 add one classname function to rule them all
  common/utils/classnames.js
Labels: improvement

#3173 eventbrite widget loading is now more correct
  common/styles/components/_buttons.scss
  common/views/components/BasePage/EventPage.js
  server/views/layout/default.njk
Labels: improvement

#3174 deprecate exhibitions intro
  whats_on/app/views/pages/exhibition.njk
Labels: bug

#3176 use package.json checksum for circle cache as greenkeeper doesn't upd…
  .circleci/config.yml
Labels: bug

#3164 Remove readme from storybook
  cardigan/.storybook/addons.js
  cardigan/package.json
  cardigan/stories/components/Promos.js
  cardigan/stories/components/SectionHeader.js
  cardigan/stories/docs/index.js
  cardigan/stories/global/icons/icons.js
  cardigan/stories/global/palette/palette.js
  cardigan/stories/global/typography/typography.js
  cardigan/stories/wip/BookPromo.js
  cardigan/yarn.lock
Labels: improvement

#3178 don't thinkk we can infer language about an event location
  common/views/components/BasePage/EventPage.js
Labels: improvement

#3182 Hide broken 'E' link
  common/styles/components/_buttons.scss
  eventbrite/app/controllers.js
Labels: bug

#3183 Event status
  common/views/components/CompactCard/CompactCard.js
  common/views/components/EventCard/EventCard.js
  common/views/components/EventPromo/EventPromo.js
  common/views/components/SearchResults/SearchResults.js
  whats_on/app/views/pages/events.njk
Labels: bug

#3188 Event policies ui
  common/model/events.js
  common/model/exhibitions.js
  common/model/installations.js
  common/model/label-field.js
  common/model/place.js
  common/model/places.js
  common/services/prismic/events.js
  common/services/prismic/exhibitions.js
  common/services/prismic/fetch-links.js
  common/services/prismic/installations.js
  common/services/prismic/parsers.js
  common/services/prismic/places.js
  common/views/components/BasePage/EventPage.js
  common/views/components/BasePage/PlacePage.js
  common/views/components/InfoBox/InfoBox.js
  server/services/prismic-parsers.js
Labels: improvement

#3193 parse contribution description better
  common/services/prismic/parsers.js
Labels: bug

#3191 Header background
  cardigan/stories/components/BaseHeader.js
  common/views/components/BaseHeader/BaseHeader.js
  common/views/components/BaseHeader/HeaderBackground.js
  common/views/components/BaseHeader/TexturedBackground.js
  common/views/components/BaseHeader/WobblyBackground.js
  common/views/components/BasePage/BookPage.js
  common/views/components/BasePage/EventPage.js
  common/views/components/BasePage/EventSeriesPage.js
  common/views/components/BasePage/InstallationPage.js
  common/views/components/BasePage/PlacePage.js
Labels: improvement

#3192 add urls back to facility promos
  whats_on/app/views/pages/whats-on.njk
Labels: bug

#3189 Hide booking info schedule / reorder schedule
  common/views/components/BasePage/EventPage.js
  common/views/components/EventScheduleItem/EventScheduleItem.js
Labels: bug

#3194 make sure we check isBroken === false not !isBroken
  common/services/prismic/events.js
  common/services/prismic/parsers.js
Labels: bug

#3199 make sure you can only interact with the check tickets button once th…
  common/views/components/BasePage/EventPage.js
  server/middleware/error.js
Labels: bug

#3201 Label parser fix
  common/services/prismic/parsers.js
Labels: bug

#3200 Add metadaata to whats on
  common/utils/json-ld.js
  server/utils/json-ld.js
  server/views/layout/default.njk
  whats_on/app/views/pages/event-series.njk
  whats_on/app/views/pages/event.njk
  whats_on/app/views/pages/exhibition.njk
  whats_on/app/views/pages/installation.njk
Labels: health

#3197 update catalogue yarn lock
  catalogue/webapp/yarn.lock
Labels: health

#3198 add cards back into cardigan
  cardigan/stories/components/Cards.js
  cardigan/stories/components/Promos.js
Labels: improvement

#3207 use the placeholder for the image in a captioned image
  common/services/prismic/parsers.js
Labels: bug

#3210 add some extra fields to the JSON LD for events
  common/model/events.js
  common/services/prismic/events.js
  common/services/prismic/parsers.js
  common/utils/json-ld.js
  common/views/components/BasePage/EventPage.js
  common/views/components/EventScheduleItem/EventScheduleItem.js
  prismic-model/json/events.json
  server/utils/json-ld.js
Labels: health

#3209 have "no events" mesaging on event series, and cap list to 3 events
  common/services/prismic/event-series.js
  common/views/components/BasePage/EventSeriesPage.js
Labels: health

#3215 Rmove has event description
  common/views/components/BasePage/EventPage.js
  common/views/components/EventScheduleItem/EventScheduleItem.js
Labels: health

#3206 Daterange on events
  cardigan/stories/components/EventDateRange.js
  common/model/date-range.js
  common/model/events.js
  common/services/prismic/events.js
  common/test/services/prismic/parsers.test.js
  common/test/utils/dates.test.js
  common/utils/dates.js
  common/views/components/BasePage/EventPage.js
  common/views/components/DateRange/DateRange.js
  common/views/components/EventCard/EventCard.js
  common/views/components/EventDateRange/EventDateRange.js
  common/views/components/EventDateRange/README.md
  common/views/components/EventPromo/EventPromo.js
Labels: improvement

#3211 add logic to order exhibitions
  common/model/exhibitions.js
  common/services/prismic/exhibitions.js
  prismic-model/js/exhibitions.js
  prismic-model/json/exhibitions.json
  whats_on/app/controllers.js
  whats_on/app/routes.js
  whats_on/app/views/partials/mixed_exhibition_event_promos.njk
  whats_on/app/views/partials/separate_exhibition_event_promos.njk
Labels: improvement

#3216 move ticketSalesStart to reservation section in primic
  prismic-model/js/events.js
  prismic-model/json/events.json
Labels: improvement

#3213 check results size before rendering series
  server/services/prismic.js
Labels: bug

#3217 jsxy segmented control
  common/views/components/Index/index.js
  common/views/components/SegmentedControl/SegmentedControl.js
  server/services/prismic.js
  whats_on/app/controllers.js
  whats_on/app/routes.js
  whats_on/app/views/components/segmented-control/segmented-control.njk
  whats_on/app/views/components/whats-on-list-header/whats-on-list-header.njk
  whats_on/app/views/pages/whats-on.njk
  whats_on/app/views/partials/separate_exhibition_event_promos.njk
Labels: improvement

#3221 make sure we fetch contributors for event series
  common/services/prismic/events.js
Labels: bug

#3218 move contributors and add info box to events
  common/views/components/BasePage/EventPage.js
Labels: bug

#3222 s/the/this
  server/services/prismic.js
Labels: bug

#3227 Re-align labels
  common/views/components/BasePage/EventPage.js
Labels: bug

#3229 Align bulleted lists better
  common/styles/components/_body_text.scss
Labels: bug

#3224 Exhibition drupal redirect
  .circleci/config.yml
  common/services/prismic/exhibitions.js
  server/controllers/content.js
  server/package.json
  server/yarn.lock
Labels: improvement

#3232 s/Events/component in tracking code
  common/views/components/BasePage/EventPage.js
Labels: bug

#3220 Use new event and exhibition services for whats-on
  common/model/events.js
  common/model/exhibitions.js
  common/model/periods.js
  common/services/prismic/api.js
  common/services/prismic/event-series.js
  common/services/prismic/events.js
  common/services/prismic/exhibitions.js
  common/services/prismic/utils.js
  common/utils/classnames.js
  common/utils/dates.js
  common/views/components/CardGrid/CardGrid.js
  common/views/components/DailyTourPromo/DailyTourPromo.js
  common/views/components/EventsByMonth/EventsByMonth.js
  common/views/components/ExhibitionsAndEvents/ExhibitionsAndEvents.js
  common/views/components/Index/index.js
  common/views/components/SectionHeader/SectionHeader.js
  common/views/components/SegmentedControl/SegmentedControl.js
  whats_on/app/controllers.js
  whats_on/app/routes.js
  whats_on/app/views/components/whats-on-list-header/whats-on-list-header.njk
  whats_on/app/views/pages/whats-on.njk
  whats_on/app/views/partials/date_range.njk
  whats_on/app/views/partials/mixed_exhibition_event_promos.njk
  whats_on/app/views/partials/separate_exhibition_event_promos.njk
Labels: improvement

#3238 dont show dates on perm exhibitions
  whats_on/app/views/pages/exhibition.njk
Labels: bug

#3239 add past exhibitions and events
  router/nginx.conf
  whats_on/app/views/partials/mixed_exhibition_event_promos.njk
  whats_on/app/views/partials/separate_exhibition_event_promos.njk
Labels: bug

#3246 first stab at error page
  common/views/components/BasePage/ErrorPage.js
  common/views/components/Index/index.js
  server/views/pages/error.njk
Labels: improvement

#3247 add archive content to error page
  common/views/components/BasePage/ErrorPage.js
  common/views/components/ErrorPage/ErrorPage.js
Labels: improvement

#3250 replace nbsp on wordpress standfirst
  server/utils/body-parser.js
Labels: bug

#3252 Add redirects json file
  redirects/config.json
Labels: health

#3242 use polyfill with next app
  common/views/pages/_document.js
Labels: bug

#3249 improve contributing labels
  CONTRIBUTING.md
Labels: improvement

#3245 Default to v2 and provide popular v1 content on v1
  router/nginx.conf
  server/controllers/content.js
  server/services/interval-cache.js
  server/services/redirects-lookup.js
Labels: health

#3251 tidy up links in cardy
  cardigan/stories/components/Links.js
Labels: improvement

#3260 Get correct events for current-and-upcoming
  common/services/prismic/utils.js
  server/test/app/app.js
Labels: bug

#3261 Add new Quote to article body
  common/services/prismic/parsers.js
  prismic-model/js/parts/article-body.js
  prismic-model/json/articles.json
  server/services/prismic-body-parser.js
  server/views/components/article-body/article-body.njk
Labels: improvement
