Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2018-07, with the labels that each got.

#2919 type up DefaultPageLayout and PageWrapper
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
  common/views/components/ErrorPage/ErrorPage.js
  common/views/components/Footer/Footer.js
  common/views/components/PageWrapper/PageWrapper.js
Labels: health

#2933 70vh for book images
  common/styles/utilities/_root-scope-classes.scss
  common/views/components/BaseHeader/BaseHeader.js
  common/views/components/BasePage/BookPage.js
  common/views/components/BasePage/EventPage.js
  common/views/components/BasePage/InstallationPage.js
  common/views/components/BasePage/Page.js
  common/views/components/BasePage/PlacePage.js
Labels: bug

#2927 Use a polyfill for 'closest' that works
  client/js/polyfills.js
Labels: bug

#2929 Check localStorage i/o before use
  client/js/tracking.js
  client/js/util.js
  common/utils/analytics.js
  server/views/partials/analytics.njk
Labels: bug

#2931 Account for the possibility that a clicked element's parent no longer exists
  client/js/util.js
Labels: bug

#2932 Target the correct elements
  client/js/components/segmented-control.js
Labels: bug

#2935 Polyfill Arry.from
  client/js/app.js
Labels: bug

#2942 move handle with care to the top of the list on the homepage
  server/controllers/content.js
  server/views/pages/homepage.njk
Labels: test

#2946 QA extras
  common/views/components/BaseHeader/BaseHeader.js
  common/views/components/SectionHeader/SectionHeader.js
Labels: bug

#2948 client sourcemaps
  client/webpack.config.js
Labels: bug

#2941 user controlled feature toggles
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  catalogue/webapp/server.js
  common/services/unleash/feature-toggles.js
  common/views/components/PageWrapper/PageWrapper.js
  docs/feature-toggles.md
  router/terraform/cloudfront.tf
Labels: feature

#2957 Increase basic promo image size
  common/views/components/BasicPromo/BasicPromo.js
Labels: bug

#2955 Jest
  catalogue/webapp/.babelrc
  catalogue/webapp/components/ImageViewer/ImageViewer.js
  catalogue/webapp/components/ImageViewer/ImageViewerImage.js
  catalogue/webapp/components/WorkCredit/WorkCredit.js
  catalogue/webapp/components/WorkEmbed/WorkEmbed.js
  catalogue/webapp/components/WorkMedia/WorkMedia.js
  catalogue/webapp/package.json
  catalogue/webapp/pages/embed.js
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  catalogue/webapp/services/catalogue/works.js
  catalogue/webapp/test/WorkPage.test.js
  catalogue/webapp/test/WorksPage.test.js
  catalogue/webapp/test/services/catalogue/__snapshots__/works.test.js.snap
  catalogue/webapp/test/services/catalogue/works.test.js
  catalogue/webapp/yarn.lock
  common/package.json
  common/views/components/PageWrapper/PageWrapper.js
  common/yarn.lock
  flow-typed/npm/jest_v23.x.x.js
  flow-typed/npm/react-test-renderer_v16.x.x.js
  package.json
  yarn.lock
Labels: feature

#2960 Check for presence of close button on info-banner
  client/js/components/info-banner.js
Labels: bug

#2959 Check for descriptionEl existence
  server/views/layout/default.njk
Labels: bug

#2963 tidy gitignore
  .gitignore
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
Labels: techprofit

#2966 Use appendChild instead of append
  client/js/components/newsletter-signup.js
Labels: bug

#2968 Use a regex instead of a string to filter ToString error
  server/views/partials/monitoring.njk
Labels: bug

#2970 remove §
  catalogue/webapp/pages/works.js
  catalogue/webapp/yarn.lock
Labels: bug

#2973 Tidy feature-test function
  client/js/util.js
Labels: bug

#2902 add contributors heading to model
  prismic-model/js/installations.js
  prismic-model/js/parts/heading.js
  prismic-model/json/installations.json
Labels: feature

#2984 remove homepage promo placement a/b test
  server/controllers/content.js
  server/services/prismic-parsers.js
  server/services/prismic.js
Labels: health

#2974 add blank storybook contributors
  cardigan_beta/.storybook/config.js
  cardigan_beta/package.json
  cardigan_beta/stories/components/Contributors.js
  cardigan_beta/stories/components/Links.js
  cardigan_beta/yarn.lock
  common/views/components/Contributors/README.md
  flow-typed/npm/@storybook/react_v3.x.x.js
Labels: improvement

#2985 Use root 'docs' directory for all docs
  cardigan_beta/stories/docs/index.js
  docs/principles.md
Labels: health

#2964 simplify babel configs
  .circleci/config.yml
  catalogue/webapp/next.config.js
  catalogue/webapp/package.json
  catalogue/webapp/yarn.lock
  common/.babelrc
  common/next/next.config.js
  common/next/timezones.json
  common/package.json
  common/yarn.lock
  whats_on/app/package.json
  whats_on/app/yarn.lock
Labels: techprofit

#3010 Sanitize tracking data prior to JSON stringifying
  catalogue/webapp/pages/work.js
  server/views/pages/work.njk
Labels: bug

#2994 account for IE in next app
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  common/next/next.config.js
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
  common/views/components/PageWrapper/PageWrapper.js
  common/views/pages/_document.js
Labels: bug

#3016 move to using only testA and testB
  build/nginx.conf
  nginx-proxy/nginx.conf
  nginx_webapp/nginx.conf
Labels: health

#2988 add contributors logic / vis to storybook
  cardigan_beta/stories/components/BaseHeader.js
  cardigan_beta/stories/components/Contributors.js
  cardigan_beta/stories/content.js
  common/styles/utilities/_root-scope-classes.scss
  common/utils/classnames.js
  common/utils/style.js
  common/views/components/Avatar/Avatar.js
  common/views/components/Contributor/Contributor.js
  common/views/components/Contributors/Contributors.js
  common/views/components/Image/Image.js
Labels: improvement

#3023 use square image from prismic for contributors
  common/services/prismic/parsers.js
Labels: health

#2997 add event series basepage skeleton
  common/package.json
  common/services/prismic/events.js
  common/services/prismic/types.js
  common/views/components/BasePage/EventSeriesPage.js
  common/views/components/EventPromo/EventPromo.js
  common/views/components/Index/index.js
  common/yarn.lock
  server/middleware/error.js
  whats_on/app/controllers.js
  whats_on/app/routes.js
  whats_on/app/views/pages/event-series.njk
Labels: improvement

#2991 Jiggle the min promo height
  common/styles/utilities/_root-scope-classes.scss
Labels: bug

#3024 change CMS label for contribution context
  prismic-model/js/parts/contributors.js
  prismic-model/json/books.json
  prismic-model/json/events.json
  prismic-model/json/exhibitions.json
  prismic-model/json/installations.json
Labels: health

#2947 Base heading
  common/styles/components/_highlighted_heading.scss
  common/styles/non-critical.scss
  common/views/components/BaseHeader/BaseHeader.js
  common/views/components/HighlightedHeading/HighlightedHeading.js
Labels: bug

#3025 check for image before getting it's square
  common/services/prismic/parsers.js
Labels: bug

#3026 add whats-on subdomain
  router/terraform/cloudfront.tf
  whats_on/terraform/services.tf
Labels: health

#3027 fix width issue on contributors
  common/styles/utilities/_root-scope-classes.scss
  common/views/components/Contributor/Contributor.js
Labels: bug

#3028 use actual route for events in whats_on service
  whats_on/app/routes.js
Labels: health

#3029 send request URI not request from nginx
  router/nginx.conf
Labels: bug

#3032 Move ul bullet code into body_text partial
  common/styles/components/_body_part.scss
  common/styles/components/_body_text.scss
Labels: bug

#3031 use the same service to render event series
  common/services/prismic/event-series.js
  events/app/controllers.js
  events/app/views/pages/event-series.njk
  prismic_remapper/README.md
  server/index.js
Labels: improvement

#3033 Event series parse and render body
  common/services/prismic/event-series.js
  common/views/components/BasePage/EventSeriesPage.js
  events/app/controllers.js
  events/app/views/pages/event-series.njk
Labels: improvement

#3039 don't throw error before render
  server/middleware/error.js
Labels: bug

#3040 check for body before looking for it's lenght in event series
  common/services/prismic/event-series.js
Labels: bug

#3042 Use same raven-js as catalogue app
  server/views/partials/monitoring.njk
Labels: health

#3041 remap event series description to body
  prismic_remapper/README.md
  prismic_remapper/event_series_description_to_body/after.json
  prismic_remapper/event_series_description_to_body/before.json
  prismic_remapper/event_series_description_to_body/premapped/W0dMzyYAACYAZuDf$468e7ab2-887d-43d4-a982-5ba9330ed489.json
  prismic_remapper/event_series_description_to_body/premapped/WiAsdScAAH8F2VJJ$954fe16e-9ec0-4354-af14-9aca9f3be2fe.json
  prismic_remapper/event_series_description_to_body/premapped/WiAsvycAAIMF2VOW$20075789-a591-4bad-8d0f-7fa0133c79ff.json
  prismic_remapper/event_series_description_to_body/premapped/WifrbikAAGSyDtHk$954d3d26-ef4d-493c-8e47-17a049980d80.json
  prismic_remapper/event_series_description_to_body/premapped/WlYT4yQAACQAWcaw$670db46a-39d6-4905-ae55-db6d2b811901.json
  prismic_remapper/event_series_description_to_body/premapped/WlYT_SQAACcAWccj$1009fee3-d75c-42f0-b663-ab0447e6e4f4.json
  prismic_remapper/event_series_description_to_body/premapped/WlYUDCQAACQAWcdt$dd0595d7-0bc2-4ef9-abd9-53fa7ba43b42.json
  prismic_remapper/event_series_description_to_body/premapped/WlYVPyQAACcAWczA$42b46b26-43ba-4f2e-966d-db8f068c8259.json
  prismic_remapper/event_series_description_to_body/premapped/Wn28GCoAACkAIYol$fe66af57-0077-4ebb-8671-302b186227e7.json
  prismic_remapper/event_series_description_to_body/premapped/Wo1YeCoAACoAZFoN$48e94f62-759e-4bf7-9b74-c08006cc1a82.json
  prismic_remapper/event_series_description_to_body/premapped/WoK-NioAACkANeWK$5373db47-2098-4b3f-b79a-f1d072424767.json
  prismic_remapper/event_series_description_to_body/premapped/WoLgbSoAACgANnxB$3c61b785-8387-4557-a18f-61568050768f.json
  prismic_remapper/event_series_description_to_body/premapped/Wp1WGSUAAM8VKCLz$40d70885-b028-44f2-ab0c-f19d55bb7929.json
  prismic_remapper/event_series_description_to_body/premapped/Ws8XgiUAAN0dkYan$40ba654f-715c-4289-a1be-bf749bb45fae.json
  prismic_remapper/event_series_description_to_body/remap.js
  prismic_remapper/package.json
  prismic_remapper/remap.js
  prismic_remapper/yarn.lock
Labels: improvement

#3046 Bail out of renderExhibits if there aren't any IDs
  whats_on/app/controllers.js
Labels: bug

#3045 Test raven data.request.url for 'googleusercontent'
  server/views/partials/monitoring.njk
Labels: bug

#3047 use book cover as promo
  common/services/prismic/books.js
  common/services/prismic/parsers.js
  common/views/components/BasePage/BookPage.js
  server/controllers/content.js
Labels: bug

#3044 skeloton for BaseResult
  common/views/components/BasePromo/BasePromo.js
  common/views/components/BasicPromo/BasicPromo.js
  common/views/components/ContentCard/ContentCard.js
  common/views/components/Labels/Labels.js
  common/views/components/SearchResults/SearchResults.js
  server/middleware/error.js
Labels: improvement

#3056 Append query to works title if it's there
  catalogue/webapp/pages/works.js
Labels: bug

#3052 Add pharmacy of colour promo to 'try these too' on the what's on page
  common/views/components/InstallationPromo/InstallationPromo.js
  server/services/prismic.js
  server/views/pages/homepage.njk
  whats_on/app/views/pages/whats-on.njk
Labels: feature

#3070 Remove A/B test that changes event images
  server/services/prismic-parsers.js
  server/services/prismic.js
Labels: health

#3076 Limit height of comic based on viewport
  server/views/pages/article.njk
Labels: bug
