Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2018-02, with the labels that each got.

#2188 s/-/–
  server/data/facility-promos.js
Labels: bug

#2186 add hearing loop icon
  common/icons/hearing_loop.js
  common/icons/index.js
  server/views/icons/hearing_loop.svg
Labels: bug

#2187 move place to the top of access in prismic
  prismic-model/events.json
Labels: health

#2192 organise event by booking info / event description
  eventbrite/app/controllers.js
  eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
  events/app/views/pages/event.njk
  prismic-model/interpretation-types.json
  server/content-model/events.js
  server/services/prismic-parsers.js
  server/services/prismic.js
Labels: feature

#2196 remove the oxford comma
  server/data/facility-promos.js
Labels: bug

#2195 add UI for partners on events
  events/app/views/pages/event.njk
Labels: feature

#2200 {format} for {audience}
  server/views/components/event-promo/event-promo.njk
Labels: health

#2202 Wedge series title into the tags at the top
  events/app/controllers.js
  events/app/views/pages/event.njk
  server/views/components/tags/tags.njk
Labels: bug

#2208 add new waiting list messaging
  eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
Labels: feature

#2201 add for audience on event page
  events/app/views/pages/event.njk
  server/content-model/events.js
Labels: health

#2199 mark exhibitions as to whether they are permanent or current
  server/filters/format-date.js
  server/views/components/exhibition-promo/exhibition-promo.njk
Labels: feature

#2210 use absolute URLs for v1 content
  events/app/views/pages/events.njk
  exhibitions/app/views/pages/exhibitions.njk
  server/data/facility-promos.js
Labels: bug

#2211 use absolute URL for opening hours
  whats_on/app/views/components/whats-on-list-header/whats-on-list-header.njk
Labels: bug

#2213 Remove "on" from eventbrite ticket
  eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
Labels: bug

#2215 add body content styling to all body content on events
  events/app/controllers.js
  events/app/views/pages/event.njk
  server/services/prismic-parsers.js
Labels: feature

#2206 add message for ticketed and non-ticketed limited seating
  eventbrite/app/controllers.js
  eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
  events/app/views/pages/event.njk
  server/filters/format-date.js
  yarn.lock
Labels: feature

#2219 update event ticket info
  events/app/views/pages/event.njk
Labels: health

#2221 Costly events
  events/app/views/pages/event.njk
  prismic-model/events.json
  server/content-model/events.js
  server/services/prismic-parsers.js
Labels: feature

#2220 Event twitter info
  events/app/views/pages/event.njk
  exhibitions/app/views/pages/exhibition.njk
Labels: bug

#2222 Changes to how the booking info is displayed and hide booking info if sold out
  client/js/components/eventbrite-ticket-button.js
  eventbrite/app/controllers.js
  eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
  events/app/views/pages/event.njk
  server/views/components/event-promo/event-promo.njk
Labels: health

#2217 send 1% of people to v2 of whats on
  router/nginx.conf
Labels: feature

#2225 Wedge for what-on content to redirect to root
  whats_on/app/routes.js
Labels: health

#2227 ramp up what's on to 50%
  router/nginx.conf
Labels: feature

#2230 make event cost a string
  events/app/views/pages/event.njk
  prismic-model/events.json
  server/content-model/events.js
Labels: health

#2229 100% to whats on v2
  router/nginx.conf
Labels: health

#2231 fix grammar around ticketing info for concessions
  events/app/views/pages/event.njk
Labels: bug

#2235 don't cache HTML
  server/config/index.js
  server/controllers/content.js
  server/middleware/set-cache-control.js
Labels: bug

#2223 auto approve terraform update via deploy scripts
  deploy/terraform_apply_service.sh
  infra/apply_task_definition.sh
Labels: health

#2234 Use router for redirecting what's on
  router/nginx.conf
  whats_on/app/routes.js
Labels: health

#2237 ordering of events reverse startDate
  events/app/controllers.js
  server/services/prismic.js
Labels: health

#2176 Add JSX tags
  cardy/yarn.lock
  common/views/components/Tags/Tags.config.js
  common/views/components/Tags/Tags.js
Labels: health

#2224 use next-plugin for transpiling modules
  .scripts/webapp/development/package.json
  catalogue/webapp/next.config.js
  catalogue/webapp/yarn.lock
Labels: health

#2242 event series page v1 added
  events/app/controllers.js
  events/app/routes.js
  events/app/views/pages/event.njk
  events/app/views/pages/events.njk
  server/index.js
  server/services/prismic-parsers.js
  server/services/prismic.js
Labels: feature

#2246 use more specific version for nginx webapp
  build/Dockerfile_nginx
  exhibitions/nginx/Dockerfile
  exhibitions/nginx/nginx.conf
Labels: health

#2249 Add search box
  common/views/components/HTMLInput/HTMLInput.js
  common/views/components/Index/index.js
  common/views/components/SearchBox/SearchBox.config.js
  common/views/components/SearchBox/SearchBox.js
  server/views/pages/search.njk
Labels: health

#2251 Show delisted events
  server/services/prismic.js
Labels: feature

#2203 Add a contributing and code of conduct docs
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  package.json
  yarn.lock
Labels: feature

#2247 add correct speedtracker endpoints
  build-speedtracker.sh
Labels: health

#2253 hide event archive link on event series
  events/app/controllers.js
  events/app/views/pages/events.njk
Labels: bug

#2254 add preview for event series
  server/controllers/content.js
Labels: health

#2261 remove cache from /eventbrite/*
  router/terraform/cloudfront.tf
Labels: health

#2262 remove free ticket messaging from eventbrite button
  eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
Labels: bug

#2252 allow multiline events titles
  client/scss/utilities/_root-scope-classes.scss
  events/app/controllers.js
  events/app/views/pages/events.njk
  prismic-model/event-series.json
  server/index.js
  server/services/prismic.js
  server/views/components/list-header/list-header.njk
Labels: health

#2258 add skeleton of what be a nicer prismic world
  common/package.json
  common/services/prismic/api.js
  common/services/prismic/article.js
  common/services/prismic/types.js
  common/yarn.lock
  flow-typed/npm/cookies_vx.x.x.js
  flow-typed/npm/prismic-javascript_vx.x.x.js
  package.json
  yarn.lock
Labels: techprofit

#2259 rename controllers in server to be more specific
  server/controllers/utils.js
  server/controllers/wordpress.js
  server/routes/index.js
Labels: techprofit

#2256 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: health

#2273 decapitalise promo type and pull in positionInSeries
  client/scss/components/_promo.scss
  common/views/components/Promo/Promo.js
  server/views/components/numbered-list/numbered-list.njk
  server/views/components/promo/promo.njk
  server/views/pages/curated-lists.njk
  server/views/pages/list.njk
Labels: bug

#2271 introduce the concept of fully booked to event times
  common/.flowconfig
  events/app/controllers.js
  events/app/views/pages/event.njk
  prismic-model/events.json
  server/content-model/events.js
  server/data/facility-promos.js
  server/services/prismic-parsers.js
  server/services/prismic.js
  server/views/components/event-promo/event-promo.njk
Labels: feature

#2275 add koa server to catalogue webapp
  .scripts/webapp/development/package.json
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  catalogue/webapp/server.js
  catalogue/webapp/yarn.lock
Labels: feature

#2276 use range property on event times
  events/app/views/pages/event.njk
Labels: bug

#2278 remove waitinglist messaging from paid events
  eventbrite/app/controllers.js
  eventbrite/app/views/components/eventbrite-button/eventbrite-button.njk
  server/views/components/event-promo/event-promo.njk
Labels: bug

#2279 update analytics on catalogue and add appVersion
  catalogue/webapp/pages/works.js
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
  server/views/partials/analytics.njk
Labels: techprofit
