Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2018-09, with the labels that each got.

#3259 Ga server event
  server/controllers/content.js
  server/test/app/app.js
  server/yarn.lock
Labels: improvement

#3234 use new whats_on services on homepage
  common/data/the-pharmacy-of-colour.js
  common/model/installations.js
  common/services/prismic/installations.js
  common/services/prismic/utils.js
  common/views/components/CardGrid/CardGrid.js
  common/views/components/ExhibitionsAndEvents/ExhibitionsAndEvents.js
  common/views/components/InstallationPromo/InstallationPromo.js
  server/controllers/content.js
  server/index.js
  server/services/prismic.js
  server/views/pages/homepage.njk
  whats_on/app/controllers.js
  whats_on/app/utils.js
  whats_on/app/views/pages/whats-on.njk
  whats_on/app/views/partials/date_range.njk
Labels: improvement

#3264 add /explore => /stories redirect
  README.md
  build-speedtracker.sh
  common/views/components/BasePage/ErrorPage.js
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
  common/views/components/FooterNav/FooterNav.js
  router/nginx.conf
  server/controllers/content.js
  server/routes/index.js
  server/test/app/app.js
  server/views/docs/index.njk
  server/views/docs/visual-architecture.njk
  server/views/layout/default.njk
  server/views/pages/homepage.njk
Labels: improvement

#3255 Article contributors reindex
  prismic-model/js/articles.js
  prismic-model/json/articles.json
  prismic_remapper/article_contributors_remodel/after.json
  prismic_remapper/article_contributors_remodel/before.json
  prismic_remapper/article_contributors_remodel/remap.js
  server/services/prismic-parsers.js
Labels: improvement

#3270 add skeleton article to content service
  common/services/prismic/article.js
  common/services/prismic/articles.js
  content/webapp/package.json
  content/webapp/pages/article.js
  content/webapp/server.js
  content/webapp/test/articles.test.js
  content/webapp/yarn.lock
  flow-typed/npm/node-mocks-http_vx.x.x.js
Labels: improvement

#3266 Add grouped event schedule.
  common/services/prismic/events.js
  common/test/services/prismic/events.test.js
  common/views/components/BasePage/EventPage.js
  common/views/components/EventSchedule/EventSchedule.js
  common/views/components/EventSchedule/README.md
  common/views/components/EventScheduleItem/EventScheduleItem.config.js
Labels: improvement

#3262 add nicer logging to remapper
  prismic_remapper/README.md
  prismic_remapper/remap.js
Labels: improvement

#3258 remove list from article body
  prismic-model/js/parts/article-body.js
  prismic-model/json/articles.json
Labels: improvement

#3263 remove old quote
  common/views/components/Index/index.js
  common/views/components/ShameQuote/ShameQuote.config.js
  common/views/components/ShameQuote/ShameQuote.js
  prismic-model/js/parts/article-body.js
  prismic-model/json/articles.json
  server/services/prismic-body-parser.js
  server/views/components/article-body/article-body.njk
Labels: improvement

#3275 Fix nav underline for stories content
  server/controllers/content.js
  server/controllers/wordpress.js
Labels: bug

#3277 add author to article header
  cardigan/stories/components/LinkLabels.js
  common/services/prismic/articles.js
  common/views/components/Contributor/Contributor.js
  common/views/components/LinkLabels/LinkLabels.js
  content/webapp/pages/article.js
Labels: improvement

#3283 add images to genericfields
  common/data/the-pharmacy-of-colour.js
  common/model/generic-content-fields.js
  common/services/prismic/parsers.js
  common/views/components/BasePage/EventSeriesPage.js
  common/views/components/BasePage/InstallationPage.js
  content/webapp/pages/exhibition.js
Labels: improvement

#3288 add crops to article body slices
  prismic-model/js/parts/article-body.js
  prismic-model/json/articles.json
Labels: bug

#3286 Image => ImageType
  common/model/books.js
  common/model/captioned-image.js
  common/model/contributors.js
  common/model/events.js
  common/model/exhibitions.js
  common/model/generic-content-fields.js
  common/model/image.js
  common/model/people.js
  common/services/prismic/parsers.js
  common/views/components/FacilityPromo/FacilityPromo.js
  common/views/components/Images/Images.js
Labels: improvement

#3276 make thumbnail same as promo
  server/services/prismic-parsers.js
Labels: bug

#3287 Image crops
  common/data/the-pharmacy-of-colour.js
  common/model/image.js
  common/services/prismic/exhibitions.js
  common/services/prismic/parsers.js
  common/views/components/BasePage/BookPage.js
  common/views/components/DailyTourPromo/DailyTourPromo.js
  common/views/components/EventPromo/EventPromo.js
  common/views/components/ExhibitionPromo/ExhibitionPromo.js
  common/views/components/StaticWorksContent/StaticWorksContent.js
  common/views/components/WorkImage/WorkImage.js
Labels: improvement

#3291 filter out blank times from Prismic
  common/services/prismic/events.js
Labels: bug

#3293 add some redirects for 404s
  router/nginx.conf
Labels: improvement

#3300 exclude articles with wordpress tag
  server/services/prismic.js
Labels: bug

#3301 attach organisation description onto contributor parser
  common/services/prismic/fetch-links.js
  common/services/prismic/parsers.js
Labels: bug

#3282 add skeleton component for ImageWithWobblyBottom
  cardigan/stories/components/WobblyBottom.js
  cardigan_beta/stories/components/Cards.js
  common/services/prismic/articles.js
  common/services/prismic/types.js
  common/views/components/Body/Body.js
  common/views/components/Picture/Picture.js
  common/views/components/WobblyBottom/README.md
  common/views/components/WobblyBottom/WobblyBottom.js
  content/webapp/pages/article.js
  content/webapp/test/articles.test.js
Labels: feature

#3302 Article image
  common/services/prismic/parsers.js
  common/views/components/Body/Body.js
  common/views/components/FullWidthLayout/FullWidthLayout.js
  common/views/components/Header/Header.js
  common/views/components/ImageLayout/ImageLayout.js
  common/views/components/Index/index.js
  common/views/components/Layout/Layout.js
  common/views/components/PageHeaders/ExhibitionPageHeader/ExhibitionPageHeader.config.js
  common/views/components/PageHeaders/ExhibitionPageHeader/ExhibitionPageHeader.js
  common/views/components/PageHeaders/Hero/Hero.config.js
  common/views/components/PageHeaders/Hero/Hero.js
  common/views/components/TextLayout/TextLayout.js
  common/views/components/layout/Container.js
  common/views/components/layout/Grid.js
  common/views/components/layout/layout.config.js
  common/views/components/layout/preview-no-container.js
  common/views/components/layout/preview.js
  content/webapp/pages/article.js
Labels: improvement

#3307 Filter out irrelevant event times from schedule
  common/services/prismic/events.js
Labels: bug

#3305 add my.articles.series.series to search
  common/model/multi-content.js
  common/package.json
  common/services/prismic/articles.js
  common/services/prismic/fetch-links.js
  common/services/prismic/multi-content.js
  common/services/prismic/parsers.js
  common/services/prismic/search.js
  common/test/services/unleash/feature-flags.test.js
  common/views/components/SearchResults/AsyncSearchResults.js
  common/views/components/SearchResults/SearchResults.js
  common/yarn.lock
  content/webapp/package.json
  content/webapp/pages/article.js
  devappy/rules.json
  prismic-model/js/articles.js
  prismic-model/json/articles.json
  server/package.json
  server/yarn.lock
Labels: improvement

#3308 Content in circle
  .circleci/config.yml
  catalogue/webapp/next.config.js
  common/next/next.config.js
  content/terraform/terraform.tf
  content/webapp/next.config.js
  deploy/deploy_service.js
  router/terraform/asg.tf
  router/terraform/cloudfront.tf
Labels: feature

#3313 Exhibition header update
  cardigan/stories/components/WobblyBottom.js
  common/data/the-pharmacy-of-colour.js
  common/model/exhibitions.js
  common/model/generic-content-fields.js
  common/services/prismic/exhibitions.js
  common/services/prismic/parsers.js
  common/views/components/BaseHeader/BaseHeader.js
  common/views/components/BasePage/BasePage.js
  common/views/components/BasePage/EventSeriesPage.js
  common/views/components/BasePage/InstallationPage.js
  common/views/components/Body/Body.js
  common/views/components/ExhibitionHeader/ExhibitionHeader.js
  common/views/components/Header/Header.js
  common/views/components/Index/index.js
  common/views/components/Layout/Layout.js
  common/views/components/WobblyBottom/WobblyBottom.js
  content/webapp/pages/exhibition.js
Labels: improvement

#3292 Order upcoming/past event series events
  common/views/components/BasePage/EventSeriesPage.js
Labels: wip

#3317 Next error
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
  common/views/components/PageWrapper/PageWrapper.js
  content/webapp/pages/article.js
  content/webapp/pages/exhibition.js
Labels: improvement

#3315 add metadata to articles in content service
  content/webapp/pages/article.js
Labels: improvement

#3318 add relaxed performances onto events
  common/model/events.js
  common/services/prismic/events.js
  common/views/components/BasePage/BasePage.js
  common/views/components/BasePage/EventPage.js
  prismic-model/js/events.js
  prismic-model/json/articles.json
  prismic-model/json/events.json
Labels: improvement

#3324 Get rid of excess container
  common/views/components/Body/Body.js
Labels: bug

#3325 get article format from prismic
  common/services/prismic/articles.js
  common/services/prismic/parsers.js
Labels: improvement

#3320 Adding the breadcrumb to all pages
  cardigan/stories/components/BaseHeader.js
  cardigan/stories/components/Breadcrumb.js
  common/views/components/BaseHeader/BaseHeader.js
  common/views/components/BasePage/BookPage.js
  common/views/components/BasePage/ErrorPage.js
  common/views/components/BasePage/EventPage.js
  common/views/components/BasePage/EventSeriesPage.js
  common/views/components/BasePage/InstallationPage.js
  common/views/components/BasePage/Page.js
  common/views/components/BasePage/PlacePage.js
  common/views/components/Breadcrumb/Breadcrumb.js
  common/views/components/Breadcrumb/Readme.md
  common/views/components/ExhibitionHeader/ExhibitionHeader.js
  common/views/components/Header/Header.js
  common/views/components/HeaderText/HeaderText.js
  content/webapp/pages/article.js
Labels: improvement

#3335 s/Readme/README
  common/views/components/Breadcrumb/README.md
Labels: bug

#3337 only exclude on delist tag
  server/services/prismic.js
Labels: bug

#3332 add audience to events listing promos
  whats_on/app/views/pages/events.njk
Labels: bug

#3334 Page header exhibitions
  cardigan/stories/components/ExhibitionHeader.js
  common/styles/utilities/_root-scope-classes.scss
  common/views/components/Body/Body.js
  common/views/components/Breadcrumb/Breadcrumb.js
  common/views/components/ExhibitionHeader/ExhibitionHeader.js
  common/views/components/ExhibitionHeader/README.md
  common/views/components/HeaderText/HeaderText.js
  common/views/components/Layout10/Layout10.js
  common/views/components/PageHeader/PageHeader.js
  content/webapp/pages/article.js
  content/webapp/pages/exhibition.js
Labels: improvement

#3336 add body_text scss to content app
  common/styles/content.scss
Labels: bug

#3330 Page header article
  common/views/components/BasePage/EventPage.js
  content/webapp/pages/article.js
Labels: improvement

#3352 use DateRange component on DateList
  common/views/components/BasePage/EventPage.js
Labels: improvement

#3353 localise eventbrite widget opener
  common/views/components/EventbriteButton/EventbriteButton.js
Labels: bug

#3349 add field to suppress link on event schedule items
  common/model/events.js
  common/services/prismic/events.js
  common/views/components/BasePage/EventPage.js
  common/views/components/EventSchedule/EventSchedule.js
  common/views/components/EventScheduleItem/EventScheduleItem.js
  prismic-model/js/events.js
  prismic-model/json/events.json
Labels: improvement

#3346 Page header trilogy
  cardigan/stories/components/Links.js
  common/styles/content.scss
  common/views/components/BaseHeader/HeaderBackground.js
  common/views/components/BasePage/BookPage.js
  common/views/components/BasePage/ErrorPage.js
  common/views/components/BasePage/EventPage.js
  common/views/components/BasePage/EventSeriesPage.js
  common/views/components/BasePage/InstallationPage.js
  common/views/components/BasePage/Page.js
  common/views/components/BasePage/PlacePage.js
  common/views/components/Body/Body.js
  common/views/components/DateAndStatusIndicator/DateAndStatusIndicator.js
  common/views/components/Links/SecondaryLink/SecondaryLink.js
  common/views/components/PageHeader/PageHeader.js
  content/webapp/pages/exhibition.js
Labels: improvement

#3338 get article series on articles via prismic
  common/model/article-series.js
  common/model/articles.js
  common/model/multi-content.js
  common/services/prismic/api.js
  common/services/prismic/article-series.js
  common/services/prismic/articles.js
  common/services/prismic/event-series.js
  content/webapp/pages/article.js
Labels: improvement

#3361 add isFree back to events and exhibitions
  common/views/components/BasePage/EventPage.js
  content/webapp/pages/exhibition.js
Labels: bug

#3364 add all the new generic fields to an article series
  prismic-model/js/series.js
  prismic-model/json/events.json
  prismic-model/json/series.json
Labels: improvement

#3367 only show event booking button if tickets are on sale
  common/views/components/EventScheduleItem/EventScheduleItem.js
Labels: bug

#3366 put schedule as a field on the model
  prismic-model/js/series.js
  prismic-model/json/series.json
Labels: bug

#3374 add nginx redirects to router
  router/Dockerfile
  router/nginx.conf
  router/redirects.conf
Labels: improvement

#3372 add contributorProps to BasePage and implement on articles
  common/views/components/BasePage/BasePage.js
  common/views/components/Contributors/Contributors.js
  content/webapp/pages/article.js
Labels: improvement

#3370 Image weights
  common/services/prismic/parsers.js
  common/styles/utilities/_root-scope-classes.scss
  common/views/components/BaseHeader/BaseHeader.js
  common/views/components/BasePage/BasePage.js
  common/views/components/Body/Body.js
  common/views/components/Images/Images.js
  common/views/components/Layout12/Layout12.js
  common/views/components/Layout8/Layout8.js
Labels: improvement

#3368 add workLd
  catalogue/webapp/pages/work.js
Labels: improvement

#3369 tidy up some body spacing
  common/views/components/Body/Body.js
Labels: improvement

#3355 link back to event that an event is scheduled in async
  common/views/components/BasePage/EventPage.js
  common/views/components/PageHeader/PageHeader.js
  whats_on/app/controllers.js
  whats_on/app/routes.js
Labels: improvement

#3344 Added related exhibition content fields
  common/model/exhibitions.js
  common/model/multi-content.js
  common/services/prismic/api.js
  common/services/prismic/exhibitions.js
  common/services/prismic/multi-content.js
  common/services/prismic/types.js
  common/views/components/EventCard/EventCard.js
  common/views/components/SearchResults/SearchResults.js
  content/webapp/pages/exhibition.js
  prismic-model/js/exhibitions.js
  prismic-model/json/exhibitions.json
Labels: wip

#3381 Article series nav
  common/services/prismic/article-series.js
  common/services/prismic/articles.js
  common/views/components/SeriesNavigation/SeriesNavigation.js
  content/webapp/pages/article.js
Labels: improvement

#3380 Creamy body
  common/views/components/BasePage/BasePage.js
  common/views/components/Body/Body.js
  common/views/components/Contributors/Contributors.js
  content/webapp/pages/article.js
  content/webapp/pages/series.js
Labels: improvement

#3385 Event in content
  common/services/prismic/events.js
  content/webapp/pages/article-series.js
  content/webapp/pages/event.js
  content/webapp/server.js
Labels: improvement

#3386 Json ld articles events
  common/utils/json-ld.js
  content/webapp/pages/article.js
  content/webapp/pages/event.js
Labels: improvement

#3388 make max-heighted images width: auto
  common/styles/utilities/_root-scope-classes.scss
Labels: bug

#3387 add some spacing to article series
  common/services/prismic/event-series.js
  common/services/prismic/events.js
  common/views/components/BasePage/BasePage.js
  common/views/components/Contributors/Contributors.js
  common/views/components/SearchResults/SearchResults.js
  content/webapp/pages/article.js
  content/webapp/pages/event.js
Labels: improvement

#3383 Generic labels
  common/data/the-pharmacy-of-colour.js
  common/model/generic-content-fields.js
  common/model/labels.js
  common/services/prismic/article-series.js
  common/services/prismic/articles.js
  common/services/prismic/books.js
  common/services/prismic/event-series.js
  common/services/prismic/events.js
  common/services/prismic/exhibitions.js
  common/services/prismic/installations.js
  common/services/prismic/parsers.js
  common/services/prismic/places.js
  common/views/components/BasePage/BookPage.js
  common/views/components/BasePage/EventPage.js
  common/views/components/BasePage/EventSeriesPage.js
  common/views/components/BasePage/InstallationPage.js
  common/views/components/EventCard/EventCard.js
  common/views/components/EventScheduleItem/EventScheduleItem.js
  common/views/components/Label/Label.js
  common/views/components/LabelsList/LabelsList.js
  common/views/components/PageHeader/PageHeader.js
  common/views/components/SearchResults/SearchResults.js
  content/webapp/pages/article-series.js
  content/webapp/pages/article.js
  content/webapp/pages/exhibition.js
Labels: improvement

#3405 Remove JS enhanced EB iframe (just use link)
  common/views/components/EventbriteButton/EventbriteButton.js
Labels: bug

#3393 add pages to content app
  common/model/pages.js
  common/services/prismic/multi-content.js
  common/services/prismic/pages.js
  common/services/prismic/search.js
  common/views/components/CompactCard/CompactCard.js
  common/views/components/SearchResults/AsyncSearchResults.js
  content/webapp/pages/page.js
  content/webapp/server.js
  router/redirects.conf
Labels: improvement

#3410 add ALB listener rule to serve pages from content app
  content/terraform/terraform.tf
  shared-infra/terraform/service_alb_listener/alb_listener.tf
Labels: improvement
