Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2019-03, with the labels that each got.

#4137 update common/content/catalogue to next@8
  catalogue/webapp/package.json
  common/next/next.config.js
  common/package.json
  content/webapp/package.json
  yarn.lock
Labels: ✨improvement

#4195 little-el-tise
  catalogue/webapp/components/WorkCard/WorkCard.js
  catalogue/webapp/components/WorkCompactCard/WorkCompactCard.js
  catalogue/webapp/components/WorkDetails/WorkDetails.js
  catalogue/webapp/pages/PROGRESS_NOTES.md
  catalogue/webapp/pages/work.js
  common/views/components/WorkHeader/WorkHeader.js
Labels: ✨improvement

#4204 add item page
  catalogue/webapp/app.js
  catalogue/webapp/package.json
  catalogue/webapp/pages/item.js
  catalogue/webapp/pages/work.js
  common/services/catalogue/urls.js
Labels: ✨improvement

#4197 add e-books and don't filter out non-digitised works
  catalogue/webapp/components/SearchForm/SearchForm.js
Labels: ✨improvement

#4206 Show captions on captioned images when there's no JS
  common/views/components/Images/Images.js
Labels: 🐛bug

#4207 make search query logic simpler by making parameters nullable
  catalogue/webapp/components/SearchForm/SearchForm.js
  catalogue/webapp/components/WorkCard/WorkCard.js
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  common/services/catalogue/urls.js
Labels: ✨improvement

#4209 Work type filters as a segmented control
  catalogue/webapp/components/SearchForm/SearchForm.js
  catalogue/webapp/pages/works.js
  common/model/text-links.js
  common/views/components/TabNav/README.md
  common/views/components/TabNav/TabNav.js
  dash/webapp/pages/toggles.js
Labels: ✨improvement

#4213 add thumbnails for navigation to item page (no JS)
  catalogue/webapp/pages/item.js
  catalogue/webapp/pages/work.js
  common/model/iiif.js
  common/services/catalogue/urls.js
  common/views/components/RenderlessPaginator/RenderlessPaginator.js
Labels: ✨improvement

#4215 seperate toggles a little to prepare for testing of books release
  catalogue/webapp/pages/works.js
  common/views/components/Header/Header.js
  dash/webapp/pages/toggles.js
Labels: ✨improvement

#4220 add logic around how toggles affect filters on results
  catalogue/webapp/pages/works.js
Labels: 🐛bug

#4221 don't wrap betabar with style
  common/views/components/BetaBar/BetaBar.js
Labels: 🐛bug

#4219 add sierraId and canvas to cloudfront query params
  cache/cloudfront_dev.tf
  cache/cloudfront_prod.tf
Labels: ✨improvement

#4230 move results count to pagination
  catalogue/webapp/pages/works.js
  common/views/components/Paginator/Paginator.js
Labels: ✨improvement

#4232 use b number from manifest file for viewing items
  catalogue/webapp/pages/work.js
Labels: 🐛bug

#4231 hide the search header when there are results
  catalogue/webapp/pages/works.js
Labels: ✨improvement

#4174 SVG optimisation script
  icons/.svgo.yml
  icons/components/Archive.js
  icons/components/Audio.js
  icons/components/Book.js
  icons/components/DigitalImage.js
  icons/components/Journal.js
  icons/components/Maps.js
  icons/components/Music.js
  icons/components/Picture.js
  icons/components/Scroll.js
  icons/components/ThreeD.js
  icons/components/Video.js
  icons/components/Website.js
  icons/package.json
  icons/svgs/archive.svg
  icons/svgs/audio.svg
  icons/svgs/book.svg
  icons/svgs/digital_image.svg
  icons/svgs/journal.svg
  icons/svgs/maps.svg
  icons/svgs/music.svg
  icons/svgs/picture.svg
  icons/svgs/scroll.svg
  icons/svgs/three_d.svg
  icons/svgs/video.svg
  icons/svgs/website.svg
  icons/template.js
  icons/yarn.lock
Labels: 🌟feature

#4239 get the naming right on iiifPresentationLocation
  catalogue/webapp/pages/work.js
  common/utils/works.js
  common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
Labels: 🐛bug

#4241 be hyper conservative with event parsing
  common/services/prismic/articles.js
  common/services/prismic/events.js
  common/services/prismic/parsers.js
Labels: 🐛bug

#4238 Name the "explore our collections" toggle correctly
  catalogue/webapp/pages/works.js
Labels: 🐛bug

#4236 Use search context
  catalogue/webapp/components/SearchContext/SearchContext.js
  catalogue/webapp/components/SearchForm/SearchForm.js
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works-context.js
  catalogue/webapp/pages/works.js
Labels: ✨improvement

#4244 add updown / uptimerobot to dash index
  dash/webapp/pages/index.js
Labels: ✨improvement

#4245 use attrs(className) on BetaBar / TabNav
  common/views/components/BetaBar/BetaBar.js
  common/views/components/TabNav/TabNav.js
Labels: ✨improvement

#4247 spread initialState over defaultState to allow for null values
  catalogue/webapp/components/SearchContext/SearchContext.js
Labels: 🐛bug

#4251 Use work card over promo
  cache/edge_lambdas/toggler.js
  cardigan/stories/components/Promos.js
  catalogue/webapp/pages/works.js
  common/views/components/WorkPromo/README.md
  common/views/components/WorkPromo/WorkPromo.config.js
  common/views/components/WorkPromo/WorkPromo.js
  dash/webapp/pages/toggles.js
Labels: ✨improvement

#4254 make contributors LinkLabels on WorkHeader and tags in WorkDetails
  catalogue/webapp/components/WorkDetails/WorkDetails.js
  common/views/components/WorkHeader/WorkHeader.js
Labels: 🐛bug

#4256 remove unused consts
  common/views/components/EventbriteButton/EventbriteButton.js
  eventbrite/webapp/app.js
Labels: 🐛bug

#4248 s/visuals/pictures
  catalogue/webapp/pages/works.js
  dash/webapp/pages/toggles.js
Labels: 🐛bug

#4249 Use new syntax for styled component attrs
  catalogue/webapp/pages/item.js
  common/views/components/BetaBar/BetaBar.js
  common/views/components/TabNav/TabNav.js
Labels: 🐛bug

#4265 lint cache JS
  cache/edge_lambdas/redirector.js
  cache/edge_lambdas/redirector.test.js
  cache/edge_lambdas/toggler.test.js
  cache/edge_lambdas/wiRedirector.js
  cache/edge_lambdas/wiRedirector.test.js
Labels: ✨improvement

#4266 use max in main image in item viewer
  catalogue/webapp/pages/item.js
Labels: 🐛bug

#4270 Add SearchProvider to work
  catalogue/webapp/pages/work.js
Labels: 🐛bug

#4274 remove share heading
  catalogue/webapp/components/WorkDetails/WorkDetails.js
Labels: ✨improvement

#4273 use history.replace on item pagination
  catalogue/webapp/pages/item.js
Labels: ✨improvement

#4262 Add toggles service
  .circleci/config.yml
  common/koa-middleware/withToggles.js
  dash/webapp/pages/toggles.js
  terraform-modules/https_s3_website/cloudfront.tf
  toggles/.gitignore
  toggles/terraform/terraform.tf
  toggles/webapp/build.js
  toggles/webapp/defaults.json
  toggles/webapp/package.json
  toggles/webapp/toggles.js
Labels: 🌟feature

#4282 Janeway - Dante's Inferno: Consolidate the toggles for books release
  catalogue/webapp/components/SearchForm/SearchForm.js
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  common/views/components/Header/Header.js
  toggles/webapp/toggles.js
Labels: ✨improvement

#4284 preview is breaking if there is no table of contents
  common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
Labels: 🐛bug

#4293 add circleci aws policy
  .circleci/deploy_and_build_docker.py
  .circleci/terraform/terraform.tf
  .circleci/utils.py
Labels: ✨improvement

#4296 remove collectionsInMainNavigation toggle
  toggles/webapp/toggles.js
Labels: 🐛bug

#4299 swap out for architecture stories on stories page
  content/webapp/pages/stories.js
Labels: ✨improvement

#4292 [Example] Consolidate Prismic models
  prismic-model/js/interfaces/ContributedThing.js
  prismic-model/js/interfaces/LocatedThing.js
  prismic-model/js/interfaces/Thing.js
  prismic-model/js/interfaces/TimedThing.js
  prismic-model/js/types/event.js
  prismic-model/js/types/exhibition.js
  prismic-model/js/types/person.js
  prismic-model/js/types/place.js
  prismic-model/js/types/story.js
  prismic-model/json/types/articles.json
  prismic-model/json/types/event.json
  prismic-model/json/types/exhibition.json
  prismic-model/json/types/people.json
Labels: 🏗️wip

#4298 Janeway engage
  toggles/webapp/toggles.js
Labels: ✨improvement

#4307 recentre logo in header
  common/styles/components/_header.scss
  common/views/components/Header/Header.js
Labels: 🐛bug

#4308 maintain worktype state
  catalogue/webapp/components/SearchContext/SearchContext.js
  catalogue/webapp/pages/works.js
  common/views/components/TabNav/TabNav.js
Labels: 🐛bug

#4301 Forward ref typing
  cardigan/stories/components/Control.js
  catalogue/webapp/package.json
  catalogue/webapp/pages/item.js
  common/next/next.config.js
  common/package.json
  common/services/prismic/html-serialisers.js
  common/views/components/Buttons/Control/Control.js
  common/views/components/Paginator/Paginator.js
  content/webapp/package.json
  content/webapp/postcss.config.js
  flow-typed/npm/next_v7.x.x.js
  package.json
  rss/webapp/package.json
  yarn.lock
Labels: ✨improvement

#4309 actually attach the onclick handler to tabbed nav items
  catalogue/webapp/pages/works.js
  common/views/components/TabNav/TabNav.js
Labels: 🐛bug

#4315 add sierraId to canonical href of items
  catalogue/webapp/pages/item.js
Labels: 🐛bug

#4313 no JS view item link from work page
  catalogue/webapp/pages/work.js
  common/views/components/Buttons/Button/Button.js
  common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
Labels: 🐛bug

#4310 get pdf url from mediaSequences if it’s available
  common/model/iiif.js
  common/utils/works.js
Labels: 🐛bug

#4319 create new cache behaviour for /works
  cache/cloudfront_dev.tf
  cache/cloudfront_prod.tf
  cache/terraform.tf
Labels: 🐛bug

#4320 Viewer pdf
  catalogue/webapp/pages/item.js
  common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
Labels: 🐛bug

#4330 show button only if we haven't managed to load the page with JS
  catalogue/webapp/pages/item.js
  common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
Labels: 🐛bug

#4328 add error handling to IIIF images
  common/views/components/IIIFResponsiveImage/IIIFResponsiveImage.js
Labels: ✨improvement

#4332 remove works context page
  catalogue/webapp/components/SearchContext/SearchContext.js
  catalogue/webapp/pages/works-context.js
Labels: ✨improvement

#4343 Change 'Images' to 'Collections' in footer
  common/views/components/FooterNav/FooterNav.js
Labels: 🐛bug

#4348 remove IIIF components from prototype
  common/views/components/IIIFBookGrid/IIIFBookGrid.js
  common/views/components/IIIFBookPreview/IIIFBookPreview.js
  common/views/components/IIIFBookReader/IIIFBookReader.js
Labels: ✨improvement
