Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2019-01, with the labels that each got.

#3903 make sure we put yarn.lock into the Dockerfiles
  catalogue/webapp/Dockerfile
  content/webapp/Dockerfile
Labels: bug

#3902 Add noopener and noreferer to external link with target=‘_blank’
  common/views/components/OptimalSort/OptimalSort.js
Labels: bug

#3905 add medieval manuscripts redirect
  router/webapp/redirects.json
Labels: improvement

#3906 remove getInitialProps from dash app
  dash/webapp/next.config.js
  dash/webapp/pages/pa11y.js
  dash/webapp/pages/toggles.js
Labels: bug

#3911 set end of page range accurately
  common/views/components/Paginator/Paginator.js
Labels: bug

#3917 Shows correct display date on an event when grouped by month
  common/views/components/EventsByMonth/EventsByMonth.js
Labels: bug

#3918 create new events getter that only works with past and future events
  common/services/prismic/eventsV2.js
  content/webapp/pages/homepage.js
Labels: bug, wip

#3910 add wellcome images miro redirects to lambda@edge
  router/terraform/edge_lambdas.tf
  router/webapp/origin.js
  router/webapp/redirector.js
  router/webapp/redirects.js
  router/webapp/redirects.json
  router/webapp/wiRedirector.js
  router/webapp/wiRedirector.test.js
Labels: improvement

#3908 remove legacy linting issues
  package.json
Labels: improvement

#3922 make today and weekend filters programmatic
  common/services/prismic/eventsV2.js
  content/webapp/pages/whats-on.js
Labels: bug

#3933 add check to make sure event has a future date
  common/services/prismic/eventsV2.js
Labels: bug

#3934 don't filter dates that are on the same day
  common/services/prismic/eventsV2.js
Labels: bug

#3936 Check right event when ordering
  common/services/prismic/eventsV2.js
  common/views/components/CardGrid/CardGrid.js
  common/views/components/ExhibitionsAndEvents/ExhibitionsAndEvents.js
  content/webapp/pages/homepage.js
Labels: bug

#3929 Use correct id for month h2
  common/views/components/EventsByMonth/EventsByMonth.js
Labels: bug

#3935 add autofocus back to form
  catalogue/webapp/components/SearchForm/SearchForm.js
  catalogue/webapp/pages/works.js
  common/views/components/TextInput/TextInput.js
Labels: improvement

#3942 Fix outro description bug
  common/views/components/Outro/Outro.js
Labels: bug

#3945 remove v2 10 second engagement timer
  common/views/pages/_app.js
Labels: improvement

#3944 remove defaultpagelayout
  common/utils/analytics.js
  common/views/components/DefaultPageLayout/DefaultPageLayout.config.js
  common/views/components/DefaultPageLayout/DefaultPageLayout.js
Labels: improvement

#3943 remove old events fetcher, and use new one
  common/services/prismic/event-series.js
  common/services/prismic/events.js
  common/services/prismic/eventsV2.js
  content/webapp/pages/events.js
  content/webapp/pages/homepage.js
  content/webapp/pages/whats-on.js
Labels: improvement

#3952 readd domain to toggles cookie
  dash/webapp/pages/toggles.js
Labels: bug

#3957 update research issue template to reflect research card
  .github/ISSUE_TEMPLATE/research.md
Labels: improvement

#3961 set itemsLocationsLocationType from correct value
  catalogue/webapp/components/SearchForm/SearchForm.js
Labels: improvement

#3964 check for image before using it
  catalogue/webapp/pages/work.js
Labels: bug

#3965 s/uri/url
  router/webapp/ab_testing.js
Labels: bug

#3962 remap twitterHandle to sameAs
  prismic_remapper/people_remodel/after.json
  prismic_remapper/people_remodel/before.json
  prismic_remapper/people_remodel/remap.js
Labels: bug

#3951 Wellcome images redirects at edge
  router/nginx.conf
  router/webapp/wiRedirector.js
Labels: improvement

#3973 only include component that has openseadragon on the client
  common/views/components/ImageViewer/ImageViewer.js
Labels: bug

#3977 update prismic-javascript
  common/package.json
  content/webapp/package.json
  yarn.lock
Labels: improvement

#3971 Underline CompactCard titles in green on hover
  common/styles/utilities/_root-scope-classes.scss
Labels: bug

#3979 calculate datePublished consistently across webcomis and articles
  common/services/prismic/articles.js
Labels: bug

#3981 use 16:9 image as featured media if it exists on pages
  content/webapp/pages/page.js
Labels: bug

#3978 add basic RSS feed
  common/views/components/PageLayout/PageLayout.js
  content/webapp/pages/stories.js
  rss/webapp/now.json
  rss/webapp/package.json
  rss/webapp/stories/index.js
  rss/webapp/yarn.lock
Labels: improvement

#3984 use lodash.sortBy for consistent ordering in browser and on the server
  common/package.json
  common/services/prismic/events.js
  flow-typed/npm/lodash.sortby_vx.x.x.js
Labels: bug

#3985 simplify orderEventsByNextAvailableDate
  common/services/prismic/events.js
Labels: improvement

#3994 bump page count on whats-on
  content/webapp/pages/events.js
  content/webapp/pages/whats-on.js
Labels: ✨improvement

#3988 add universal terraform and rename shared-infra
  .gitignore
  client/terraform/terraform.tf
  content/terraform/terraform.tf
  static/terraform/terraform.tf
  terraform-modules/https_s3_website/cloudfront.tf
  terraform-modules/https_s3_website/s3-website-policy.json
  terraform-modules/https_s3_website/s3.tf
  terraform-modules/https_s3_website/variables.tf
  terraform-modules/service_alb_listener/alb_listener.tf
  terraform/.gitignore
  terraform/README.md
  terraform/account_iam.tf
  terraform/provider.tf
Labels: ✨improvement

#3997 account for empty arrays when tallying works metadata
  works_analysis/get_metadata_by_work_type_tally.py
Labels: 🐛bug

#3990 remove promoType field
  cardigan/stories/components/Cards.js
  common/views/components/ArticleCard/ArticleCard.js
  common/views/components/Card/Card.js
  common/views/components/CompactCard/CompactCard.js
  common/views/components/EventCard/EventCard.js
  common/views/components/FeaturedCard/FeaturedCard.js
  common/views/components/Outro/Outro.js
  common/views/components/SearchResults/SearchResults.js
Labels: ✨improvement

#4001 Edge lambda deploy
  .circleci/config.yml
  router/terraform/edge_lambdas.tf
Labels: ✨improvement

#3995 add RGB values to cardigan
  cardigan/.cache/325c8f456729b912b0d2134054eb7448-dfeeb2271cc2857eb0a45a5003c8bbee
  cardigan/stories/global/palette/palette.js
Labels: ✨improvement

#4009 add error message to works page
  catalogue/webapp/pages/works.js
Labels: ✨improvement

#3966 add more than simple rendering of iiif-presentation API data
  catalogue/webapp/components/IIIFPresentationDisplay/IIIFPresentationDisplay.js
  catalogue/webapp/pages/work.js
Labels: ✨improvement

#4011 Revert "add error message to works page"
  catalogue/webapp/pages/works.js
Labels: 🐛bug
