Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2019-02, with the labels that each got.

#4023 move IIIFPresentationDisplay to common
  catalogue/webapp/pages/work.js
  common/views/components/IIIFPresentationDisplay/IIIFPresentationDisplay.js
Labels: ✨improvement

#4024 add IIIFBookPreview
  common/model/iiif.js
  common/views/components/IIIFBookPreview/IIIFBookPreview.js
Labels: 🌟feature

#4026 add IIIFBookReader component
  common/views/components/IIIFBookReader/IIIFBookReader.js
Labels: 🌟feature

#4027 add IIIFBOOKGrid component
  common/views/components/IIIFBookGrid/IIIFBookGrid.js
Labels: 🌟feature

#4028 add IIIF types
  common/model/iiif.js
  common/views/components/IIIFBookGrid/IIIFBookGrid.js
  common/views/components/IIIFBookPreview/IIIFBookPreview.js
  common/views/components/IIIFBookReader/IIIFBookReader.js
Labels: 🌟feature

#4015 add getArticleColor function to do exactly that
  common/model/articles.js
  common/views/components/StoryPromo/StoryPromo.js
Labels: 🐛bug

#4030 use production label on works
  catalogue/webapp/components/WorkDetails/WorkDetails.js
  catalogue/webapp/components/WorkDetails/WorkDetailsNewDataGrouping.js
Labels: ✨improvement

#4037 remove not-working field search from works
  catalogue/webapp/components/WorkDetails/WorkDetails.js
  catalogue/webapp/components/WorkDetails/WorkDetailsNewDataGrouping.js
Labels: 🐛bug

#4004 Move edge lambdas
  .circleci/config.yml
  cache/README.md
  cache/cloudformation_dev.tf
  cache/cloudformation_prod.tf
  cache/edge_lambdas.tf
  cache/edge_lambdas/origin.js
  cache/edge_lambdas/origin.test.js
  cache/edge_lambdas/package.json
  cache/edge_lambdas/redirector.js
  cache/edge_lambdas/redirector.test.js
  cache/edge_lambdas/redirects.js
  cache/edge_lambdas/test_event_request.json
  cache/edge_lambdas/test_event_response.json
  cache/edge_lambdas/toggler.js
  cache/edge_lambdas/toggler.test.js
  cache/edge_lambdas/wiRedirector.js
  cache/edge_lambdas/wiRedirector.test.js
  cache/edge_lambdas/yarn.lock
  cache/terraform.tf
Labels: ✨improvement

#4044 update new cache to be more like old cache but better
  cache/cloudfront_dev.tf
  cache/cloudfront_prod.tf
Labels: ✨improvement

#4045 remove old cloudfront setup
  cache/cloudfront_prod.tf
  router/terraform/cloudfront.tf
  router/terraform/edge_lambdas.tf
Labels: ✨improvement

#4042 update storybook and addons
  cardigan/package.json
  cardigan/yarn.lock
Labels: ✨improvement

#4035 add images and books filter checkboxes
  catalogue/webapp/components/SearchForm/SearchForm.js
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
Labels: 🌟feature

#4049 convert classes and life cycle methods to functional comps and hooks
  common/views/components/ImageViewer/ImageViewer.js
Labels: ( ͡° ͜ʖ ͡°)

#4002 Make content the fallback app in the ALB
  catalogue/terraform/terraform.tf
  content/terraform/terraform.tf
  terraform-modules/service_alb_listener/alb_listener.tf
Labels: ✨improvement

#4053 Work header
  catalogue/webapp/pages/work.js
  common/icons/book.js
  common/icons/eye.js
  common/icons/index.js
  common/utils/works.js
  common/views/components/ContributorTextList/ContributorTextList.js
  common/views/components/LinkLabels/LinkLabels.js
  dash/webapp/pages/toggles.js
Labels: ✨improvement

#4057 s/path_name/path_pattern
  content/terraform/terraform.tf
Labels: 🐛bug

#4058 remove router service
  router/Dockerfile
  router/README.md
  router/docker-build.sh
  router/docker-push.sh
  router/nginx.conf
  router/terraform/asg.tf
  router/terraform/services.tf
  router/terraform/variables.tf
  router/webapp/ab_testing.js
  router/webapp/ab_testing.test.js
  router/webapp/origin.js
  router/webapp/origin.test.js
  router/webapp/package.json
  router/webapp/redirector.js
  router/webapp/redirector.test.js
  router/webapp/redirects.js
  router/webapp/test_event_request.json
  router/webapp/test_event_response.json
  router/webapp/wiRedirector.js
  router/webapp/wiRedirector.test.js
  router/webapp/yarn.lock
Labels: ✨improvement

#4064 add type to newletter button
  common/views/components/NewsletterSignup/NewsletterSignup.js
Labels: ✨improvement

#4059 Header improvements
  catalogue/webapp/components/WorkDetails/WorkDetails.js
  catalogue/webapp/components/WorkDetails/WorkDetailsNewDataGrouping.js
  catalogue/webapp/pages/work.js
  common/views/components/LinkLabels/LinkLabels.js
  common/views/components/WorkHeader/WorkHeader.js
Labels: ✨improvement

#4066 Static cors
  client/terraform/terraform.tf
  terraform-modules/https_s3_website/cloudfront.tf
Labels: ✨improvement

#4068 remove refs to old ALB and use new ALB for CloudWatch
  catalogue/terraform/terraform.tf
  content/terraform/terraform.tf
Labels: ⛩️infrastructure, ✨improvement

#4067 remove router from deployable services
  deploy/deploy_service.js
  package.json
Labels: ✨improvement

#4070 the initial setup of moving installations into the exhibitions fold
  common/services/prismic/api.js
  common/services/prismic/exhibitions.js
  common/views/components/CardGrid/CardGrid.js
  common/views/components/ExhibitionPromo/ExhibitionPromo.js
  content/webapp/components/Exhibition/Exhibition.js
  content/webapp/components/Installation/Installation.js
  content/webapp/pages/exhibition.js
Labels: ✨improvement

#4074 remap exhibitions to installations
  prismic_remapper/installations_to_exhibitions/after.json
  prismic_remapper/installations_to_exhibitions/before.json
  prismic_remapper/installations_to_exhibitions/premapped/W-K6iBUAAJqYxKMi$0743d833-015b-454f-a632-5309c32c35c0.json
  prismic_remapper/installations_to_exhibitions/premapped/W-K8VhUAAKOcxKsl$26bb4478-29f7-4995-b3a9-bb76ebc428fc.json
  prismic_remapper/installations_to_exhibitions/premapped/W-LESBUAAJ-dxM5y$948ba27b-f081-4aa4-91f5-b3050c4ec332.json
  prismic_remapper/installations_to_exhibitions/premapped/W3LDcCkAACcAEKqy$a8f91af1-5b4c-464a-8222-b1ebdc1d2f55.json
  prismic_remapper/installations_to_exhibitions/premapped/W5Y-NyYAACMALAdp$81b921be-f154-4eba-9dcd-3aedaebe402e.json
  prismic_remapper/installations_to_exhibitions/premapped/W78dJBEAAB8NpQle$45db05f9-e8e0-447c-9f39-2f7317f3d47c.json
  prismic_remapper/installations_to_exhibitions/premapped/W7T-FxAAADRy0mu0$e7c08027-0bda-42ac-9e69-d2e56d5a324d.json
  prismic_remapper/installations_to_exhibitions/premapped/W9sIhRUAANoQovHe$406c72dc-876d-4424-81f9-2f5f6b702f05.json
  prismic_remapper/installations_to_exhibitions/premapped/W9xNPBUAAO5nqHyO$c964cf57-9e79-4b06-b791-28a9038d301e.json
  prismic_remapper/installations_to_exhibitions/premapped/WqwC1iAAAB8AJgFB$9b5afa48-f5b6-430c-bf85-309b2ec29546.json
  prismic_remapper/installations_to_exhibitions/premapped/Wrynhx8AAAjk9XX-$c94dd47b-2a21-49f2-af38-38ad9fe5c277.json
  prismic_remapper/installations_to_exhibitions/premapped/WryoVx8AAAjk9Xmg$2f9a0c3d-f168-49f1-8a18-070e30225186.json
  prismic_remapper/installations_to_exhibitions/premapped/Wryoox8AAAjk9Xr0$e023a8cd-4220-4551-b56e-34276f7f360c.json
  prismic_remapper/installations_to_exhibitions/premapped/WthzICAAAOObLY5K$168afd46-abb3-4f64-ab10-215132d1711d.json
  prismic_remapper/installations_to_exhibitions/premapped/WyuWLioAACkACeYv$562e587b-ab4b-451f-bc00-c8b12faa3c46.json
  prismic_remapper/installations_to_exhibitions/remap.js
Labels: ✨improvement

#4073 update react
  cardigan/package.json
  cardigan/yarn.lock
  catalogue/webapp/package.json
  common/package.json
  content/webapp/package.json
  dash/webapp/package.json
  dash/webapp/yarn.lock
  yarn.lock
Labels: ✨improvement

#4071 Exhibitions in exhibitions
  common/services/prismic/exhibitions.js
  common/views/components/SearchResults/SearchResults.js
  prismic-model/js/exhibitions.js
  prismic-model/json/exhibitions.json
Labels: ✨improvement

#4091 add installation label to exhibition results
  common/services/prismic/exhibitions.js
  common/services/prismic/multi-content.js
Labels: ✨improvement

#4090 add installation => exhibition redirects
  cache/edge_lambdas/redirects.js
Labels: ✨improvement

#4092 run edge lambda deploy on master
  .circleci/config.yml
Labels: 🐛bug

#4093 bump lambda versions on prod cache
  cache/terraform.tf
Labels: ✨improvement

#4096 make use of theme values for styled component
  catalogue/webapp/components/WorkDetails/WorkDetailsNewDataGrouping.js
Labels: ✨improvement

#4062 add contributor, date and location data to result
  catalogue/webapp/components/WorkCompactCard.js/WorkCompactCard.js
  catalogue/webapp/pages/works.js
Labels: ✨improvement

#4060 allow works specific query parameters through the cache
  cache/cloudfront_dev.tf
  cache/cloudfront_prod.tf
Labels: ✨improvement

#4103 remove article scss
  common/styles/components/_article.scss
  common/styles/critical.scss
Labels: ✨improvement

#4095 remove references to installations
  common/data/our-voice-our-way.js
  common/data/the-pharmacy-of-colour.js
  common/model/exhibitions.js
  common/model/installations.js
  common/model/multi-content.js
  common/services/prismic/articles.js
  common/services/prismic/exhibitions.js
  common/services/prismic/fetch-links.js
  common/services/prismic/installations.js
  common/services/prismic/link-resolver.js
  common/services/prismic/multi-content.js
  common/services/prismic/types.js
  common/views/components/CardGrid/CardGrid.js
  common/views/components/ExhibitionPromo/ExhibitionPromo.js
  common/views/components/ExhibitionsAndEvents/ExhibitionsAndEvents.js
  common/views/components/Index/index.js
  common/views/components/InstallationPromo/InstallationPromo.js
  common/views/components/SearchResults/SearchResults.js
  content/webapp/app.js
  content/webapp/components/Installation/Installation.js
  content/webapp/pages/installation.js
  content/webapp/pages/whats-on.js
  devappy/rules.json
  prismic-model/js/exhibitions.js
  prismic-model/js/installations.js
  prismic-model/js/parts/body.js
  prismic-model/json/books.json
  prismic-model/json/event-series.json
  prismic-model/json/events.json
  prismic-model/json/exhibitions.json
  prismic-model/json/installations.json
  prismic-model/json/pages.json
  prismic-model/json/places.json
  prismic-model/json/series.json
  prismic-model/json/webcomics.json
Labels: ✨improvement

#4105 Toggles fix
  dash/webapp/pages/toggles.js
Labels: 🐛bug

#4097 bring the search bar size down a notch on /work/id
  catalogue/webapp/components/SearchForm/SearchForm.js
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  common/views/components/TextInput/TextInput.js
Labels: ✨improvement

#4102 show all dates/times on event compact card
  cardigan/stories/components/EventDateRange.js
  common/views/components/CompactCard/CompactCard.js
  common/views/components/EventCard/EventCard.js
Labels: ✨improvement

#4099 shrink vertical spacing on WorkHeader
  catalogue/webapp/pages/work.js
  common/views/components/WorkHeader/WorkHeader.js
Labels: ✨improvement

#4100 add contributors back to work details
  catalogue/webapp/components/WorkDetails/WorkDetailsNewDataGrouping.js
Labels: ✨improvement

#4108 don't show close button on standalone image gallery
  common/views/components/Body/Body.js
  common/views/components/ImageGallery/ImageGallery.config.js
  common/views/components/ImageGallery/ImageGallery.js
  common/views/components/ImageGalleryV2/ImageGalleryV2.js
Labels: 🐛bug

#4111 use moment to create dates on pharamacy of colour
  common/data/the-pharmacy-of-colour.js
Labels: 🐛bug

#4106 add new work locations toggle
  catalogue/webapp/components/SearchForm/SearchForm.js
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  common/views/components/WorkHeader/WorkHeader.js
  dash/webapp/pages/toggles.js
Labels: ✨improvement

#4122 add partof to exhibitions
  common/services/prismic/exhibitions.js
  content/webapp/components/Installation/Installation.js
Labels: ✨improvement

#4069 Remove alb
  infra/.gitignore
  infra/README.md
  infra/TODO.md
  infra/apply.sh
  infra/apply_task_definition.sh
  infra/deploy.py
  infra/package.json
  infra/plan.sh
  infra/setup.sh
  infra/terraform/container-definitions.json
  infra/terraform/network/vpc.tf
  infra/terraform/prod/terraform.tf
  infra/terraform/prod/wellcomecollection.tf
  infra/terraform/templates/alb.tf
  infra/terraform/templates/ec2.tf
  infra/terraform/templates/ecs.tf
  infra/terraform/templates/iam.tf
  infra/terraform/templates/s3.tf
  infra/terraform/templates/sg.tf
  infra/terraform/templates/vars.tf
  infra/yarn.lock
Labels: ✨improvement

#4132 set domain to root when setting cookies on toggler
  dash/webapp/pages/toggles.js
Labels: 🐛bug

#4139 Don’t display :before pseudo element when gallery is active
  common/styles/components/_image_gallery_v2.scss
Labels: 🐛bug

#4121 add release notes for feb 2019
  catalogue/webapp/pages/PROGRESS_NOTES.md
Labels: ✨improvement

#4143 don't show date label when there are no dates on work card
  catalogue/webapp/components/WorkCompactCard.js/WorkCompactCard.js
Labels: 🐛bug

#4142 remove simple query example from release notes
  catalogue/webapp/pages/PROGRESS_NOTES.md
Labels: ✨improvement

#4130 Bump NodeJS versions to 10.15.1 lts
  .circleci/config.yml
  build/Dockerfile_webapp
  catalogue/webapp/Dockerfile
  content/webapp/Dockerfile
  package.json
Labels: 🏗️wip

#4155 add imagelesssearchresult toggl
  catalogue/webapp/pages/works.js
  dash/webapp/pages/toggles.js
Labels: ✨improvement

#4153 add shortTitle to exhibitions
  common/model/exhibitions.js
  common/services/prismic/exhibitions.js
  content/webapp/components/Installation/Installation.js
  prismic-model/js/exhibitions.js
  prismic-model/js/parts/single-line-text.js
  prismic-model/json/exhibitions.json
Labels: ✨improvement

#4156 update designs on work card
  catalogue/webapp/components/WorkCompactCard.js/WorkCompactCard.js
  common/styles/utilities/_root-scope-classes.scss
Labels: ✨improvement

#4162 download dropdown to 100% thrusters
  cache/edge_lambdas/toggler.js
  cardigan/stories/components/License.js
  catalogue/webapp/components/Download/Download.js
  catalogue/webapp/components/Download/DownloadBeta.js
  catalogue/webapp/components/WorkDetails/WorkDetails.js
  catalogue/webapp/pages/work.js
  common/views/components/License/License.config.js
  common/views/components/License/License.js
  common/views/components/License/LicenseBeta.js
  dash/webapp/pages/toggles.js
Labels: ✨improvement

#4157 add worktype icons
  common/icons/archive.js
  common/icons/audio.js
  common/icons/book.js
  common/icons/digital_image.js
  common/icons/index.js
  common/icons/journal.js
  common/icons/map.js
  common/icons/music.js
  common/icons/picture.js
  common/icons/scroll.js
  common/icons/three_d.js
  common/icons/video.js
  common/icons/website.js
  common/utils/works.js
  icons/archive.svg
  icons/audio.svg
  icons/book.svg
  icons/digital_image.svg
  icons/journal.svg
  icons/maps.svg
  icons/music.svg
  icons/picture.svg
  icons/scroll.svg
  icons/three_d.svg
  icons/video.svg
  icons/website.svg
Labels: ✨improvement

#4154 Update filters interface
  catalogue/webapp/components/SearchForm/SearchForm.js
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  catalogue/webapp/services/catalogue/works.js
  common/model/catalogue.js
Labels: ✨improvement

#4164 Add generic work card A/B
  cache/edge_lambdas/toggler.js
  catalogue/webapp/components/WorkCard/WorkCard.js
  catalogue/webapp/pages/works.js
  dash/webapp/pages/toggles.js
Labels: 🔬a/b test

#4176 put feedback behind a toggle and remove pseudo filter of 'images'
  catalogue/webapp/components/SearchForm/SearchForm.js
  catalogue/webapp/pages/works.js
  dash/webapp/pages/toggles.js
Labels: ✨improvement

#4179 bump edge lambdas for A/B test
  cache/terraform.tf
Labels: ✨improvement

#4180 put museum and library LD on the pages
  common/model/opening-hours.js
  common/model/organization.js
  common/utils/json-ld.js
  common/views/components/FindUs/FindUs.js
  common/views/pages/_app.js
  common/views/pages/_document.js
Labels: 🐛bug

#4182 remove checkboxes from filters to be explicit about how they work
  catalogue/webapp/components/SearchForm/SearchForm.js
  catalogue/webapp/pages/works.js
Labels: ✨improvement

#4184 remove last years exceptional times from JSON+LD
  common/model/opening-hours.js
Labels: ✨improvement

#4185 Make work types more obviously (de)selectable
  catalogue/webapp/components/SearchForm/SearchForm.js
  common/styles/base/_icons.scss
  common/views/components/SelectableTags/README.md
  common/views/components/SelectableTags/SelectableTags.js
Labels: ✨improvement
