Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2019-04, with the labels that each got.

#4353 center full view text on Safari
  common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js
Labels: 🐛bug

#4349 add RFC for URL parameters
  docs/rfcs/001-url_parameters/README.md
  docs/rfcs/001-url_parameters/url_parameters_strategy.md
Labels: 🌟feature

#4357 move url parameters doc to root of docs
  docs/url_parameters_strategy.md
Labels: ✨improvement

#4336 use context for search state and don't persist it in the URL
  catalogue/webapp/components/SearchContext/SearchContext.js
  catalogue/webapp/components/SearchForm/SearchForm.js
  catalogue/webapp/components/WorkCard/WorkCard.js
  catalogue/webapp/pages/item.js
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  common/services/catalogue/urls.js
  common/views/components/BackToResults/BackToResults.js
  common/views/components/CatalogueSearchContext/CatalogueSearchContext.js
  common/views/components/IIIFViewer/IIIFViewer.js
  common/views/pages/_app.js
Labels: ✨improvement

#4369 remove Home breadcrumb
  common/styles/utilities/_root-scope-classes.scss
  common/views/components/Breadcrumb/Breadcrumb.js
  common/views/components/ErrorPage/ErrorPage.js
  content/webapp/pages/opening-times.js
  content/webapp/pages/page.js
Labels: ✨improvement

#4358 Selectable queries
  catalogue/webapp/components/SearchForm/SearchForm.js
  catalogue/webapp/pages/works.js
  common/services/catalogue/urls.js
  common/views/components/BackToResults/BackToResults.js
  common/views/components/CatalogueSearchContext/CatalogueSearchContext.js
  toggles/webapp/toggles.js
Labels: 🌟feature

#4373 refresh inputQuery state when query changes
  catalogue/webapp/components/SearchForm/SearchForm.js
Labels: 🐛bug

#4382 make selectable queries available upfront
  catalogue/webapp/components/SearchForm/SearchForm.js
Labels: ✨improvement

#4374 Segment search logger component as function
  catalogue/webapp/pages/item.js
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  common/views/components/CataloguePageLayout/CataloguePageLayout.js
  common/views/components/CatalogueSearchContext/CatalogueSearchContext.js
  common/views/components/PageLayout/PageLayout.js
  common/views/components/SearchLogger/SearchLogger.js
Labels: 🌟feature

#4375 s/embed/oembed
  catalogue/terraform/terraform.tf
  catalogue/webapp/app.js
Labels: 🐛bug

#4387 whitelist _queryType in cloudfront
  cache/cloudfront_dev.tf
  cache/cloudfront_prod.tf
Labels: 🐛bug

#4401 Event missing from homepage
  common/services/prismic/events.js
Labels: 🐛bug

#4377 make subdomains return a strict robots.txt
  router/terraform/alb.tf
  router/terraform/terraform.tf
Labels: ✨improvement

#4412 check for string before applying .trim
  common/views/components/SearchLogger/SearchLogger.js
Labels: 🐛bug

#4378 Relevance checker
  catalogue/webapp/pages/works.js
  common/views/components/CataloguePageLayout/CataloguePageLayout.js
  common/views/components/RelevanceRater/RelevanceRater.js
  common/views/components/Tracker/Tracker.js
  toggles/webapp/toggles.js
Labels: 🌟feature

#4422 check data property exists
  common/services/prismic/opening-times.js
Labels: 🐛bug

#4425 remove proven and unused toggles
  catalogue/webapp/components/SearchForm/SearchForm.js
  catalogue/webapp/pages/work.js
  common/views/components/FooterNav/FooterNav.js
  common/views/components/Header/Header.js
  toggles/webapp/toggles.js
Labels: ✨improvement

#4433 add toggle to allow access to stage API
  cardigan/stories/components/MessageBar.js
  catalogue/webapp/pages/work.js
  catalogue/webapp/pages/works.js
  catalogue/webapp/services/catalogue/works.js
  common/views/components/BetaBar/BetaBar.js
  common/views/components/MessageBar/MessageBar.js
  common/views/components/MessageBar/README.md
  toggles/webapp/toggles.js
Labels: 🌟feature

#4434 only show filters when there are results to filter
  catalogue/webapp/pages/works.js
Labels: 🐛bug
