Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2020-10, with the labels that each got.

#5584 Research_issue_template
  .github/ISSUE_TEMPLATE/research.md
Labels: data analysis

#5610 Add dynamic image collectionvenue for #5598
  cardigan/stories/components/VenueHours.js
  common/model/opening-hours.js
  common/services/prismic/fetch-links.js
  common/services/prismic/hardcoded-id.js
  common/services/prismic/opening-times.js
  common/views/components/VenueHours/VenueHours.js
  common/views/pages/_app.js
  content/webapp/pages/page.js
  prismic-model/js/collection-venues.js
  prismic-model/js/parts/image.js
  prismic-model/json/collection-venues.json
Labels: feature

#5596 #5588 - Button alignment issue on whats on this weekend or today.
  common/package.json
  common/views/components/CardGrid/CardGrid.js
  common/views/components/CardGrid/CardGrid.test.js
  common/views/components/CardGrid/__snapshots__/CardGrid.test.js.snap
Labels: bug 🐛

#5634 Not allow, Footer collection venue opening times names dynamic.
  cardigan/stories/components/Footer.js
  cardigan/stories/content.js
  common/model/opening-hours.ts
  common/services/prismic/hardcoded-id.js
  common/test/fixtures/components/opening-times.js
  common/views/components/Footer/Footer.js
  common/views/components/FooterOpeningTimes/FooterOpeningTimes.test.js
  common/views/components/FooterOpeningTimes/FooterOpeningTimes.tsx
  common/views/components/FooterOpeningTimes/__snapshots__/FooterOpeningTimes.test.js.snap
  common/views/components/LandingBody/VisitUsStaticContent.js
  common/views/components/VenueClosedPeriods/VenueClosedPeriods.js
  common/views/pages/_app.js
  content/webapp/pages/whats-on.js
Labels: bug 🐛

#5650 Media Object - Allow prismic to add media object
  cardigan/stories/components/MediaObject.js
  common/model/media-object.ts
  common/services/prismic/fetch-links.js
  common/services/prismic/parsers.js
  common/test/fixtures/components/compact-card.js
  common/test/fixtures/components/media-object-base.js
  common/test/fixtures/components/media-object.js
  common/test/services/prismic/parsers.test.js
  common/views/components/ArticleCard/ArticleCard.js
  common/views/components/Body/Body.js
  common/views/components/CompactCard/CompactCard.js
  common/views/components/CompactCard/CompactCard.test.js
  common/views/components/CompactCard/CompactCard.tsx
  common/views/components/CompactCard/__snapshots__/CompactCard.test.js.snap
  common/views/components/ContentPage/ContentPage.js
  common/views/components/EventCard/EventCard.js
  common/views/components/FeaturedCard/FeaturedCard.js
  common/views/components/MediaObject/MediaObject.test.js
  common/views/components/MediaObject/MediaObject.tsx
  common/views/components/MediaObject/README.md
  common/views/components/MediaObject/__snapshots__/MediaObject.test.js.snap
  common/views/components/MediaObjectBase/MediaObjectBase.test.js
  common/views/components/MediaObjectBase/MediaObjectBase.tsx
  common/views/components/MediaObjectBase/README.md
  common/views/components/MediaObjectBase/__snapshots__/MediaObjectBase.test.js.snap
  common/views/components/MediaObjectList/MediaObjectList.test.js
  common/views/components/MediaObjectList/MediaObjectList.tsx
  common/views/components/MediaObjectList/__snapshots__/MediaObjectList.test.js.snap
  common/views/components/Number/Number.tsx
  common/views/components/Outro/Outro.js
  common/views/components/PartNumberIndicator/PartNumberIndicator.js
  common/views/components/PartNumberIndicator/PartNumberIndicator.tsx
  common/views/components/SearchResults/SearchResults.js
  common/views/components/StoryPromo/StoryPromo.js
  common/views/components/WorkHeader/WorkHeader.js
  content/webapp/pages/article.js
  prismic-model/js/parts/body.js
  prismic-model/js/parts/media-object.js
  prismic-model/json/pages.json
Labels: feature, prismic

#5685 Compact card title is small - revert to original size
  common/views/components/CompactCard/__snapshots__/CompactCard.test.js.snap
  common/views/components/MediaObjectBase/MediaObjectBase.test.js
  common/views/components/MediaObjectBase/MediaObjectBase.tsx
  common/views/components/MediaObjectBase/__snapshots__/MediaObjectBase.test.js.snap
Labels: bug 🐛
