Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2020-11, with the labels that each got.

#5688 * Allow to enable / disable toggle features via query string params.
  cache/cloudfront_prod.tf
  cache/cloudfront_stage.tf
  common/koa-middleware/tests/withToggles.test.js
  common/koa-middleware/withToggles.js
Labels: feature

#5715 remove homepage banner and place the cream banner closure
  toggles/webapp/toggles.js
Labels: improvement ✨

#5747 Add message explaining there are no results for an image search if there are none #5738
  catalogue/webapp/components/SearchNoResults/SearchNoResults.test.js
  catalogue/webapp/components/SearchNoResults/SearchNoResults.tsx
  catalogue/webapp/package.json
  catalogue/webapp/pages/images.tsx
  catalogue/webapp/pages/works.js
  common/package.json
Labels: bug 🐛

#5778 Search Sort have to click twice instead of once to trigger the select option
  common/views/components/PrototypePortal/PrototypePortal.tsx
Labels: bug 🐛

#5776 Fix issue Flickering screen when displaying the scroll bar on the works viewer
  common/views/components/IIIFViewer/IIIFViewer.js
  common/views/components/IIIFViewer/parts/GridViewer.js
  common/views/components/InfoBanner/InfoBanner.tsx
Labels: bug 🐛

#5783 remove unused covid icons and components as we have these in prismic
  common/views/components/CovidIcons/CovidIcons.tsx
  common/views/components/CovidSafetyMeasure/CovidSafetyMeasure.tsx
Labels: bug 🐛

#5798 Update a number of components in common flow javascript files into Typescript
  catalogue/webapp/components/Download/Download.js
  catalogue/webapp/components/WorkDetails/WorkDetails.js
  catalogue/webapp/components/WorkDetailsSection/WorkDetailsSection.js
  catalogue/webapp/pages/image.js
  catalogue/webapp/pages/item.js
  common/views/components/AudioPlayer/AudioPlayer.tsx
  common/views/components/Avatar/Avatar.tsx
  common/views/components/BetaBar/BetaBar.tsx
  common/views/components/BetaMessage/BetaMessage.tsx
  common/views/components/Body/Body.js
  common/views/components/BookPromo/BookPromo.tsx
  common/views/components/Breadcrumb/Breadcrumb.tsx
  common/views/components/CardGrid/CardGrid.js
  common/views/components/Contact/Contact.tsx
  common/views/components/Contributor/Contributor.js
  common/views/components/CookieNotice/CookieNotice.tsx
  common/views/components/Divider/Divider.js
  common/views/components/Divider/Divider.tsx
  common/views/components/LayoutPaginatedResults/LayoutPaginatedResults.js
  common/views/components/Outro/Outro.js
  common/views/components/PageHeader/PageHeader.js
  common/views/components/PageLayoutDeprecated/PageLayoutDeprecated.js
  common/views/components/VenueHours/VenueHours.js
  content/webapp/components/Exhibition/Exhibition.js
Labels: improvement ✨

#5814 Non JS search: Make search tab align together instead of a row
  common/views/components/BaseTabs/BaseTabs.tsx
Labels: bug 🐛

#5824 Non javascript: currently noscript images on search are not displaying correctly on live
  catalogue/webapp/components/ImageCard/ImageCard.js
Labels: bug 🐛

#5829 Fixes bug where tree control for the initially loaded work is not shown
  common/views/components/ArchiveTree/ArchiveTree.js
Labels: bug 🐛

#5820 * Hide the sorting for non js and fix issue with create portal not rendering when switching views
  catalogue/webapp/components/Work/Work.tsx
  catalogue/webapp/pages/images.tsx
  catalogue/webapp/pages/works.js
  common/views/components/DropdownButton/DropdownButton.tsx
  common/views/components/PrototypeSearchForm/PrototypeSearchForm.tsx
  common/views/components/SearchTabs/SearchTabs.tsx
Labels: bug 🐛

#5826 500 issue, fix issue with params items not a string and returning back an array on works.
  catalogue/webapp/pages/works.js
  common/utils/serialise-url.ts
Labels: bug 🐛
