Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2020-01, with the labels that each got.

#4969 add sound (i) and videorecordings (g) to defaultWorkTypes
  catalogue/webapp/test/search-params.test.js
  common/services/catalogue/search-params.js
Labels: bug 🐛

#4978 hack to not try render thumbnails that are PDFs
  catalogue/webapp/components/WorkCard/WorkCard.js
Labels: bug 🐛

#4979 Test for RadioNodeList to stop IE breaking
  catalogue/webapp/components/SearchForm/SearchForm.js
Labels: bug 🐛

#4991 Make checkbox filters work in IE11
  catalogue/webapp/components/SearchForm/SearchForm.js
  common/views/components/SearchFilters/SearchFiltersDesktop.js
Labels: bug 🐛

#4992 Fix IE radios
  catalogue/webapp/components/SearchForm/SearchForm.js
Labels: bug 🐛

#4996 redirect lowercase article URL to proper case
  cache/edge_lambdas/redirects.js
Labels: patch 🧰

#5004 add digitised filter for whole catalogue search
  catalogue/webapp/components/SearchForm/SearchForm.js
  common/views/components/SearchFilters/SearchFilters.js
  common/views/components/SearchFilters/SearchFiltersDesktop.js
  toggles/webapp/toggles.js
Labels: feature

#5014 Sentry errors
  catalogue/webapp/components/Download/ViewerDownload.js
  catalogue/webapp/components/WorkDetails/WorkDetails.js
  catalogue/webapp/pages/download.js
  common/utils/get-license-info.js
  common/views/components/IIIFViewer/IIIFViewer.js
Labels: bug 🐛

#5039 Bump header z-index to make sure it's above everything
  common/styles/components/_header.scss
Labels: bug 🐛

#5041 Move free sticker above desktop header
  common/views/components/FreeSticker/FreeSticker.js
Labels: bug 🐛
