Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2021-02, with the labels that each got.

#6039 Update Cardgrid.js to typescript and any files referencing
  common/views/components/CardGrid/CardGrid.tsx
  common/views/components/EventsByMonth/EventsByMonth.js
  common/views/components/ExhibitionsAndEvents/ExhibitionsAndEvents.js
  common/views/components/LayoutPaginatedResults/LayoutPaginatedResults.js
  content/webapp/pages/homepage.js
  content/webapp/pages/stories.js
  content/webapp/pages/whats-on.js
Labels: improvement ✨

#6041 Card.js to typescript and update any references & snapshot
  common/views/components/Card/Card.tsx
  common/views/components/CardGrid/__snapshots__/CardGrid.test.js.snap
  common/views/components/EventPromo/EventPromo.js
  common/views/components/ExhibitionPromo/ExhibitionPromo.js
  common/views/components/FacilityPromo/FacilityPromo.js
  common/views/components/LandingBody/LandingBody.js
  common/views/components/SimpleCardGrid/SimpleCardGrid.js
  common/views/components/StoryPromo/StoryPromo.js
Labels: improvement ✨

#6048 Update dot and dateRange js component to typescript.
  common/views/components/CardGrid/__snapshots__/CardGrid.test.js.snap
  common/views/components/DateAndStatusIndicator/DateAndStatusIndicator.js
  common/views/components/DateRange/DateRange.tsx
  common/views/components/Dot/Dot.tsx
  common/views/components/EventDateRange/EventDateRange.js
  common/views/components/EventPromo/EventPromo.js
  common/views/components/StatusIndicator/StatusIndicator.js
  content/webapp/components/Exhibition/Exhibition.js
Labels: improvement ✨

#6054 More Filters: Bug: Pressing Enter on keyboard makes modal pop up for MoreFilters
  common/views/components/SearchFiltersDesktop/SearchFiltersDesktop.tsx
Labels: bug 🐛

#6046 Content page js to ts and flow Reference
  common/utils/utility-types.ts
  common/views/components/Body/Body.tsx
  common/views/components/ContentPage/ContentPage.tsx
  common/views/components/ErrorPage/ErrorPage.js
  common/views/components/ImageGallery/ImageGallery.js
  content/webapp/components/Exhibition/Exhibition.js
  content/webapp/components/Installation/Installation.js
  content/webapp/pages/article-series.js
  content/webapp/pages/article.js
  content/webapp/pages/event-series.js
  content/webapp/pages/landing-page.js
  content/webapp/pages/page.js
  content/webapp/pages/place.js
Labels: improvement ✨

#6066 sort by alphabetical order for languages
  common/utils/filters.ts
  common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
  common/views/components/SearchFiltersDesktop/SearchFiltersDesktop.tsx
Labels: improvement ✨

#6073 More Filters: UI Genres & Subjects multiple selection , UI Improvements
  common/services/catalogue/routes.js
  common/services/catalogue/ts_api.ts
  common/services/catalogue/ts_routes.ts
  common/test/services/catalogue/routes.test.js
  common/utils/csv.ts
  common/utils/filters.ts
  common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
  common/views/components/ResetActiveFilters/ResetActiveFilters.tsx
  common/views/components/SearchFilters/SearchFilters.tsx
  common/views/components/SearchFiltersDesktop/SearchFiltersDesktop.tsx
  common/views/components/SearchFiltersMobile/SearchFiltersMobile.tsx
  common/views/components/SearchForm/SearchForm.tsx
Labels: feature, improvement ✨

#6096 More Filters: UI for multiple contributors filters
  catalogue/webapp/components/WorkDetails/WorkDetails.tsx
  catalogue/webapp/pages/works.tsx
  common/model/catalogue.ts
  common/services/catalogue/routes.js
  common/services/catalogue/ts_api.ts
  common/services/catalogue/ts_routes.ts
  common/test/services/catalogue/routes.test.js
  common/utils/filters.ts
  common/views/components/Body/CollectionsStaticContent.tsx
  common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
  common/views/components/ResetActiveFilters/ResetActiveFilters.tsx
  common/views/components/SearchFilters/SearchFilters.tsx
  common/views/components/SearchFiltersDesktop/SearchFiltersDesktop.tsx
  common/views/components/SearchFiltersMobile/SearchFiltersMobile.tsx
  common/views/components/SearchForm/SearchForm.tsx
  common/views/components/SearchToolbar/SearchToolbar.js
Labels: feature, improvement ✨

#6097 Combined UR/data analysis
  .github/ISSUE_TEMPLATE/research.md
Labels: data analysis, needs:research

#6099 More filters: Bug fixes changes and text changes
  common/views/components/CheckboxRadio/CheckboxRadio.tsx
  common/views/components/ModalMoreFilters/ModalMoreFilters.tsx
  common/views/components/SearchFiltersMobile/SearchFiltersMobile.tsx
Labels: bug 🐛

#6120 ensure Safari preloads initial frame of video
  common/views/components/GifVideo/GifVideo.js
Labels: bug 🐛
