Repository wellcomecollection/wellcomecollection.org, pull requests merged in 2025-06, with the labels that each got.

#11949 Remove link field in Teams content type
  common/customtypes/teams/index.json
  common/prismicio-types.d.ts
  content/webapp/components/Contact/index.tsx
  content/webapp/services/prismic/transformers/events.ts
  content/webapp/services/prismic/types/index.ts
  content/webapp/types/events.ts
Labels: Lower priority

#11998 Update "sticky" in page navigation post-QA
  cardigan/stories/components/OnThisPageAnchors/Sticky.stories.tsx
  content/webapp/components/OnThisPageAnchors/index.tsx
Labels: epic: concepts

#12017 Scroll toolbar when too big
  common/views/components/ApiToolbar/index.tsx
  content/webapp/components/ArchiveBreadcrumb/index.tsx
Labels: Lower priority

#12002 Split out A/B test creation steps into adding/removing
  cache/README.md
Labels: e2es not required
